[package]
name = "distill-pipeline-fixture"
version.workspace = true
edition = "2024"
license.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
distill-core = { path = "../../../../distill-core" }
distill-json = { path = "../../../../distill-json" }
distill-pipeline-api = { path = "../../../../distill-pipeline-api" }
newgameplus-api-macros = { path = "../../../../../../../newgameplus/newgameplus-api-macros" }

[build-dependencies]
ngp-source-hash = { path = "../../../../../../../newgameplus/ngp-source-hash" }
