//! The §4 runtime declarations, verbatim: `AssetType`,
//! `AssetRuntimeDescriptor`, `ErasedValue`, `EncodeSink`,
//! `EncodeContainer`, the `AssetRef`/`WeakAssetRef` native forms, and
//! the §15 `PlaceholderThunk`.

use core::marker::PhantomData;
use std::sync::{
    atomic::{AtomicU8, Ordering},
    Arc,
};

use distill_core::attestation::CompiledTypeRow;
use distill_core::id::{AssetUuid, LogicalHash, TypeUuid};
use distill_wire::native::{
    CallbackPanic, CtorTable, DropTable, NativeLayoutNode, SkipWriterTable,
};

/// Implemented by `#[asset]`; never hand-written (§4).
///
/// # Safety
///
/// `descriptor` must be the generated descriptor for exactly `Self`, and its
/// UUID, layout, callbacks, encoder, and finalizer must all describe `Self`.
pub unsafe trait AssetType: 'static {
    const TYPE_UUID: TypeUuid;
    /// The consuming binary's generated runtime descriptor — an
    /// associated fn, not a const, because the tables it borrows are
    /// statics, which consts cannot refer to (§4).
    fn descriptor() -> &'static AssetRuntimeDescriptor;
}

/// Everything a consuming binary needs to receive an artifact of this
/// type: generated by `#[asset]` alongside the tables it points into
/// (§4). The loader resolves a fetched artifact's `TypeUuid` to one of
/// these (§15).
pub struct AssetRuntimeDescriptor {
    pub type_uuid: TypeUuid,
    /// Cross-binary measured layout digest (§5): registration,
    /// pack-mount (§16), and connect (§17) comparisons.
    pub layout_digest: [u8; 32],
    /// Binary-local fixup-table identity (§5): the plan-cache key.
    /// Never compared across binaries.
    pub fixup_identity: [u8; 32],
    /// The logical hash this binary's type projects to — checked
    /// against artifact headers (§12: a mismatch is a registry
    /// disagreement, an error, never a migration trigger).
    pub logical_hash: LogicalHash,
    /// The type's `#[asset(build_only)]` policy bit (§9), exposed so
    /// load-policy validation is uniform across IO bases (§13, §15,
    /// §16). Deliberately absent from DSLH and DSNL (§5): policy is
    /// carried and compared, never hashed into layout identity.
    pub build_only: bool,
    /// Complete shared semantic attestation row. Consumers use this exact
    /// typed projection for module, pack, connect, and reattest gates.
    pub compiled_type: &'static CompiledTypeRow,
    /// The measured native layout tree (§12), table ids annotated in
    /// place — the native-side input to fixup-plan compilation.
    pub native_layout: &'static NativeLayoutNode,
    pub size: usize,
    pub align: usize,
    pub ctors: &'static CtorTable,              // §12
    pub drops: &'static DropTable,              // §12
    pub skip_writers: &'static SkipWriterTable, // §12
    /// Move a completed fixed-up value out of its plan-execution buffer
    /// into the owned, type-erased form `AssetStorage::update` consumes
    /// (§15). The buffer must hold a complete `T`; afterwards the
    /// buffer is uninitialized again. No-unwind (§3). `ErasedValue`,
    /// never a bare `Box<dyn Any>` (§4). No `Send + Sync` bounds,
    /// deliberately (§4, §15).
    pub finalize: unsafe fn(src: *mut u8, owner: EpochToken) -> Result<ErasedValue, CallbackPanic>,
    /// Lower a typed value into the neutral wire-builder vocabulary —
    /// the only form in which a processor output crosses the module
    /// boundary (§9's result binding, §12's encoder). A no-unwind
    /// generated visitor (§3's thunk rule): it walks the value and
    /// emits flat bytes, container begin/push/finish events in
    /// canonical order — maps and sets iterated in their deterministic
    /// §5 serialization order (encoded key/element bytes), never native
    /// iteration order — blob byte handoffs, and typed reference
    /// emissions (strong/weak + target uuid).
    pub encode:
        unsafe fn(value_ptr: *const u8, sink: &mut dyn EncodeSink) -> Result<(), CallbackPanic>,
}

/// The owned, type-erased form asset values take across the module
/// boundary (§4) — game-side storage (§15) holds exactly this, never a
/// `Box<dyn Any>`. Automatic Rust drop is suppressed (ManuallyDrop
/// semantics); the value is destroyed only through `drop_thunk`, a
/// generated no-unwind STATUS thunk. On Err the value is deliberately
/// leaked and the owning module epoch is poisoned (§15) — poisoning is
/// the observer's act; this type's contract is that the failure is
/// OBSERVABLE.
pub struct ErasedValue {
    ptr: *mut u8, // the value; ManuallyDrop by construction
    type_uuid: TypeUuid,
    drop_thunk: unsafe fn(*mut u8) -> Result<(), CallbackPanic>,
    owner: EpochToken,
}

/// A cloneable capability for one loaded module epoch. Every erased
/// value retains a clone, so the poison state and epoch identity outlive
/// every value made by that epoch. Epoch identifiers are minted by the
/// host and never reused (§3, §15).
#[derive(Clone)]
pub struct ModuleEpochToken(Arc<EpochState>);

/// Short compatibility spelling; the normative §4 name is
/// `ModuleEpochToken`.
pub type EpochToken = ModuleEpochToken;

struct EpochState {
    id: u64,
    poison_cause: AtomicU8,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum ModuleEpochPoisonCause {
    CallbackPanic = 1,
    CallbackRejected = 2,
}

impl ModuleEpochToken {
    pub fn new(id: u64) -> Self {
        Self(Arc::new(EpochState {
            id,
            poison_cause: AtomicU8::new(0),
        }))
    }

    pub fn id(&self) -> u64 {
        self.0.id
    }

    pub fn is_poisoned(&self) -> bool {
        self.poison_cause().is_some()
    }

    /// Compatibility spelling for a returned failure status. Callers that
    /// caught a panic use [`Self::poison_with`] to retain that distinction.
    pub fn poison(&self) {
        self.poison_with(ModuleEpochPoisonCause::CallbackRejected);
    }

    /// Fence this epoch permanently while latching its first typed cause.
    pub fn poison_with(&self, cause: ModuleEpochPoisonCause) {
        let _ = self.0.poison_cause.compare_exchange(
            0,
            cause as u8,
            Ordering::AcqRel,
            Ordering::Acquire,
        );
    }

    pub fn poison_cause(&self) -> Option<ModuleEpochPoisonCause> {
        match self.0.poison_cause.load(Ordering::Acquire) {
            0 => None,
            1 => Some(ModuleEpochPoisonCause::CallbackPanic),
            2 => Some(ModuleEpochPoisonCause::CallbackRejected),
            _ => unreachable!("ModuleEpochToken stores only closed poison-cause tags"),
        }
    }

    pub fn same_epoch(&self, other: &Self) -> bool {
        Arc::ptr_eq(&self.0, &other.0)
    }
}

impl core::fmt::Debug for ModuleEpochToken {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.debug_struct("EpochToken")
            .field("id", &self.id())
            .field("poisoned", &self.is_poisoned())
            .finish()
    }
}

impl ErasedValue {
    /// Erase an owned value of a `#[asset]` type. The status drop thunk
    /// is the generated one for `T` (§3's thunk rule): a panicking
    /// `Drop` is an `Err`, never an unwind, and the value stays leaked.
    pub fn new_in<T: AssetType>(value: T, owner: EpochToken) -> ErasedValue {
        ErasedValue {
            ptr: Box::into_raw(Box::new(value)).cast::<u8>(),
            type_uuid: T::TYPE_UUID,
            drop_thunk: crate::thunks::erased_drop_thunk::<T>,
            owner,
        }
    }

    /// Assemble from raw parts — generated code only.
    ///
    /// # Safety
    /// `ptr` must own a heap value whose true type matches both
    /// `type_uuid` and what `drop_thunk` destroys.
    pub unsafe fn from_raw(
        ptr: *mut u8,
        type_uuid: TypeUuid,
        drop_thunk: unsafe fn(*mut u8) -> Result<(), CallbackPanic>,
        owner: EpochToken,
    ) -> ErasedValue {
        ErasedValue {
            ptr,
            type_uuid,
            drop_thunk,
            owner,
        }
    }

    pub fn type_uuid(&self) -> TypeUuid {
        self.type_uuid
    }

    /// The erased value pointer — typed access is the caller's claim.
    pub fn as_ptr(&self) -> *const u8 {
        self.ptr
    }

    pub fn owner_epoch(&self) -> u64 {
        self.owner.id()
    }

    pub fn owner_token(&self) -> &EpochToken {
        &self.owner
    }

    /// Borrow the value as `T`. `None` on a type-uuid mismatch — never
    /// a blind cast.
    pub fn downcast_ref<T: AssetType>(&self) -> Option<&T> {
        if self.type_uuid == T::TYPE_UUID {
            // Safety: uuid match — the constructor's ownership claim.
            Some(unsafe { &*self.ptr.cast::<T>() })
        } else {
            None
        }
    }

    /// Destroy through the status drop thunk (the only destruction
    /// path). On `Err` the value has been deliberately leaked — the
    /// caller poisons the owning module epoch (§15).
    pub fn destroy(self) -> Result<(), CallbackPanic> {
        // Safety: constructor contract — ptr/thunk pairing.
        let result = unsafe { (self.drop_thunk)(self.ptr) };
        if result.is_err() {
            self.owner
                .poison_with(ModuleEpochPoisonCause::CallbackPanic);
        }
        result
    }
}

// No `Drop` impl, deliberately: ManuallyDrop semantics (§4) — dropping
// an `ErasedValue` without `destroy` leaks the value; automatic Rust
// drop would run module drop glue unwrapped across the unloadable-module
// boundary.

/// The daemon-side consumer of a generated encode visitor's events (§4)
/// — the neutral vocabulary is the whole interface, so no typed Rust
/// value ever crosses the module boundary on the output path.
pub trait EncodeSink {
    /// Flat value bytes (scalars, flat structs) at the current position.
    fn flat(&mut self, bytes: &[u8]);
    /// Container events, in canonical order (§5): the visitor — not the
    /// sink — owns iteration order, and emits map/set members sorted by
    /// their encoded bytes.
    fn begin(&mut self, kind: EncodeContainer, len: u32);
    fn push(&mut self);
    fn finish(&mut self);
    /// `#[asset(blob)]` payload handoff — the bytes, never a slot
    /// encoding.
    fn blob(&mut self, bytes: &[u8]);
    /// Typed reference emission: §9's result binding validates each one
    /// against the job's snapshot and records the TraceOp::RefCheck.
    fn reference(&mut self, strong: bool, target: AssetUuid, expected_terminal: TypeUuid);
}

/// Container kinds in the encode vocabulary (§4). `Variant(u32)` carries
/// the variant's canonical name-sorted index (§5's order — the same
/// index the §12 canonical wire tag holds).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EncodeContainer {
    Vec,
    Array,
    Set,
    Map,
    Option,
    Box,
    Arc,
    Str,
    Struct,
    Variant(u32),
}

/// Generated by the module-side `placeholder!` macro (§15) — not
/// constructible from a bare fn, so panic containment and automatic-
/// drop suppression cannot be forgotten (§3's thunk rule, §4's
/// `ErasedValue` contract).
pub struct PlaceholderThunk {
    pub type_uuid: TypeUuid,
    pub make: fn(EpochToken) -> Result<ErasedValue, CallbackPanic>,
}

/// 16 bytes native and wire (§12): the resolved UUID. The query
/// encodings of §4 exist only in bundle JSON; build import resolves
/// them. Typed by declaration; the pipeline map validates `T` at
/// build/read time.
#[repr(transparent)]
pub struct AssetRef<T: AssetType>(AssetUuid, PhantomData<fn() -> T>);

/// The non-gating variant (§4): same encodings, resolved with the same
/// recorded dependencies, but never entering load-dependency lists.
#[repr(transparent)]
pub struct WeakAssetRef<T: AssetType>(AssetUuid, PhantomData<fn() -> T>);

macro_rules! ref_impls {
    ($name:ident) => {
        impl<T: AssetType> $name<T> {
            pub fn new(uuid: AssetUuid) -> Self {
                $name(uuid, PhantomData)
            }
            pub fn uuid(&self) -> AssetUuid {
                self.0
            }
        }
        impl<T: AssetType> Clone for $name<T> {
            fn clone(&self) -> Self {
                *self
            }
        }
        impl<T: AssetType> Copy for $name<T> {}
        impl<T: AssetType> PartialEq for $name<T> {
            fn eq(&self, other: &Self) -> bool {
                self.0 == other.0
            }
        }
        impl<T: AssetType> Eq for $name<T> {}
        impl<T: AssetType> core::fmt::Debug for $name<T> {
            fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
                write!(f, concat!(stringify!($name), "({})"), self.0)
            }
        }
    };
}

ref_impls!(AssetRef);
ref_impls!(WeakAssetRef);
