//! Asset-namespace metadata (§13): `bundles` (with each one's primary
//! asset), `assets` + search tags, `schemas` — and bundle poison versus namespace errors.
//!
//! Bundle-scoped poison (§7, §13): a file that cannot be indexed
//! publishes a poison row *only when the current malformed bytes
//! themselves yield a fully validated, complete namespace skeleton* —
//! the outer envelope parses and every asset UUID, `local_id`, type
//! UUID, and tag value extracts and validates even though the file as a
//! whole fails. The skeleton's rows then REPLACE every prior
//! `bundles`/`assets` row for the file's UUIDs (never silently
//! retained, never silently dropped): resolves against those UUIDs
//! return a stable `Failed` naming the error, and tag queries whose
//! selectors match its entries fail naming the poisoned bundle. Anything
//! less than the complete skeleton takes §7's conservative
//! **namespace error** instead — *regardless of what prior
//! metadata exists*: a prior indexed row identifies what the OLD bytes
//! claimed, not what the malformed bytes might claim, so a poison is
//! scoped only by facts validated from the bytes being poisoned.

use std::collections::{BTreeMap, BTreeSet};

use distill_core::id::{AssetUuid, BundleUuid, ContentHash, LogicalHash, TypeUuid};
use rusqlite::OptionalExtension;

use crate::db::{InputTxn, Store, StoreReader};
use crate::error::StoreError;
use crate::files::RootId;

/// One `bundles` row (§13): the physical key, matching `files`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BundleMeta {
    pub bundle: BundleUuid,
    pub root: RootId,
    pub path: String,
    pub format_version: u32,
    pub content_hash: ContentHash,
    /// Directory-import provenance (§8, §13): present iff this bundle
    /// was generated by a directory import — derived at scan from the
    /// `DirectoryOrigin` record riding in the bundle's `$record` entry,
    /// never from precious rows. `None` means explicit import.
    pub origin: Option<DirectoryOrigin>,
    /// Whether the bundle's `$record` import record is watched (§8): derived
    /// at scan from the record, like `origin`.
    pub import_watched: bool,
}

/// A generated bundle's directory-import provenance (§2, §8, §13): who
/// owns it and which group produced it — what orphan tracking re-derives
/// ownership from after daemon-state loss.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct DirectoryOrigin {
    pub rules_bundle: BundleUuid,
    /// Stable authored UUID-style rule identity (R22/H7), never the
    /// rule's mutable position in `DirectoryImportRules.rules`.
    pub rule: DirectoryRuleId,
    /// The fold's group key as a rooted path (§8) — the root's
    /// persistent NAME (§18's named roots), never a numeric ordinal.
    pub group_root: String,
    pub group_path: String,
}

/// Stable identity of one authored directory-import rule. Kept local to
/// the store surface because it is provenance metadata, not an asset or
/// bundle identity domain.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct DirectoryRuleId(pub [u8; 16]);

impl std::fmt::Display for DirectoryRuleId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        for (i, byte) in self.0.iter().enumerate() {
            if matches!(i, 4 | 6 | 8 | 10) {
                f.write_str("-")?;
            }
            write!(f, "{byte:02x}")?;
        }
        Ok(())
    }
}

/// One `assets` row (§13) plus its search tags.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AssetRecord {
    pub asset: AssetUuid,
    pub bundle: BundleUuid,
    pub local_id: String,
    pub type_uuid: TypeUuid,
    pub logical_hash: LogicalHash,
    pub authoring_only: bool,
    pub tags: BTreeMap<String, Option<String>>,
    /// The terminal type of an entry the RPC namespace serves (see
    /// [`crate::served`]); `None` for a row it does not serve.
    pub terminal_type: Option<TypeUuid>,
}

/// The fully validated, complete namespace skeleton a malformed file's
/// CURRENT bytes yielded (§7, §13) — the precondition for bundle-scoped
/// poison. Every field is a fact validated from the bytes being
/// poisoned; the caller that could not extract all of them publishes
/// a namespace error instead.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NamespaceSkeleton {
    pub bundle: BundleUuid,
    pub root: RootId,
    pub path: String,
    pub format_version: u32,
    /// Hash of the malformed bytes themselves — what "fixing the file
    /// heals on the next version" compares against.
    pub content_hash: ContentHash,
    pub entries: Vec<SkeletonEntry>,
}

/// One asset entry of a [`NamespaceSkeleton`]: UUID, local id, type,
/// and tags — validated despite the whole-file failure. There is
/// deliberately no logical hash: the schema closure may be exactly what
/// failed.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SkeletonEntry {
    pub asset: AssetUuid,
    pub local_id: String,
    pub type_uuid: TypeUuid,
    pub authoring_only: bool,
    pub tags: BTreeMap<String, Option<String>>,
}

/// What `entry()` returns (§13's `EntryMeta`).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EntryMeta {
    pub asset: AssetUuid,
    pub bundle: BundleUuid,
    pub local_id: String,
    pub type_uuid: TypeUuid,
    pub logical_hash: LogicalHash,
    pub authoring_only: bool,
    pub tags: BTreeMap<String, Option<String>>,
}

/// Complete §10 tag-index publication for one asset: its current-schema
/// tags, or why it has none, and the module whose migration produced them.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TagIndexUpdate {
    pub asset: AssetUuid,
    pub tags: BTreeMap<String, Option<String>>,
    pub dylib_hash: Option<[u8; 32]>,
    pub poison: Option<String>,
}

/// An asset's tag state (its `tag_module` and `tag_poison`).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TagIndexState {
    pub dylib_hash: Option<[u8; 32]>,
    pub poison: Option<String>,
}

/// The tag poison of an asset whose tags a refinement has yet to compute.
const TAG_PENDING: &str = "tag indexing pending";

impl InputTxn<'_> {
    /// Publish (or republish) a bundle row. Clears any poison: fixing
    /// the file heals on the next version (§13). Healing republishes
    /// wholesale — a previously poisoned row's asset rows are the
    /// malformed file's skeleton, and their meaning dies with the
    /// poison, so they are dropped here before the caller re-indexes
    /// the fixed file's entries.
    pub fn upsert_bundle(&mut self, meta: &BundleMeta) -> Result<(), StoreError> {
        let was_poisoned: Option<Option<String>> = self
            .txn
            .query_row(
                "SELECT poison FROM bundles WHERE bundle_uuid = ?1",
                [meta.bundle.0.as_slice()],
                |r| r.get(0),
            )
            .optional()?;
        if matches!(was_poisoned, Some(Some(_))) {
            self.remove_owned_asset_rows(meta.bundle)?;
        }
        // The caller republishes the references of the bytes it indexes.
        self.clear_path_refs(meta.bundle)?;
        self.txn
            .prepare_cached(
                "INSERT INTO bundles(bundle_uuid, root_id, path, format_version, content_hash, poison,
                                 origin_rules_bundle, origin_rule, origin_group_root, origin_group_path,
                                 import_watched)
             VALUES (?1, ?2, ?3, ?4, ?5, NULL, ?6, ?7, ?8, ?9, ?10)
             ON CONFLICT(bundle_uuid) DO UPDATE SET
               root_id = excluded.root_id, path = excluded.path,
               format_version = excluded.format_version,
               content_hash = excluded.content_hash, poison = NULL,
               origin_rules_bundle = excluded.origin_rules_bundle,
               origin_rule = excluded.origin_rule,
               origin_group_root = excluded.origin_group_root,
               origin_group_path = excluded.origin_group_path,
               import_watched = excluded.import_watched, primary_asset = NULL",
            )?
            .execute(
                rusqlite::params![
                    meta.bundle.0.as_slice(),
                    meta.root.0,
                    meta.path,
                    meta.format_version,
                    meta.content_hash.0.as_slice(),
                    meta.origin.as_ref().map(|o| o.rules_bundle.0.as_slice().to_vec()),
                    meta.origin.as_ref().map(|o| o.rule.0.as_slice()),
                    meta.origin.as_ref().map(|o| o.group_root.as_str()),
                    meta.origin.as_ref().map(|o| o.group_path.as_str()),
                    meta.import_watched,
                ],
            )?;
        Ok(())
    }

    /// Drop what a bundle owns (assets, tags, path references) and keep its
    /// row, for the [`InputTxn::upsert_bundle`] or
    /// [`InputTxn::poison_bundle`] that rewrites it in this input.
    pub fn clear_bundle(&mut self, bundle: BundleUuid) -> Result<(), StoreError> {
        self.remove_owned_asset_rows(bundle)?;
        self.clear_path_refs(bundle)
    }

    /// Remove a bundle and everything it owns (assets, tags).
    pub fn remove_bundle(&mut self, bundle: BundleUuid) -> Result<bool, StoreError> {
        self.remove_owned_asset_rows(bundle)?;
        self.clear_path_refs(bundle)?;
        let n = self.txn
            .prepare_cached("DELETE FROM bundles WHERE bundle_uuid = ?1")?
            .execute([bundle.0.as_slice()])?;
        Ok(n > 0)
    }

    /// Record the logical path strings `bundle`'s reference fields name
    /// (§13's `bundle_path_refs`), replacing any it had. Call after
    /// [`InputTxn::upsert_bundle`], which clears them.
    pub fn set_bundle_path_refs<'a>(
        &mut self,
        bundle: BundleUuid,
        targets: impl IntoIterator<Item = &'a str>,
    ) -> Result<(), StoreError> {
        self.clear_path_refs(bundle)?;
        for target in targets {
            self.txn
                .prepare_cached(
                    "INSERT OR IGNORE INTO bundle_path_refs(bundle_uuid, target) VALUES (?1, ?2)",
                )?
                .execute(rusqlite::params![bundle.0.as_slice(), target])?;
        }
        Ok(())
    }

    fn clear_path_refs(&mut self, bundle: BundleUuid) -> Result<(), StoreError> {
        self.txn
            .prepare_cached("DELETE FROM bundle_path_refs WHERE bundle_uuid = ?1")?
            .execute([bundle.0.as_slice()])?;
        Ok(())
    }

    /// Drop every asset row a bundle owns, with their tags.
    fn remove_owned_asset_rows(&mut self, bundle: BundleUuid) -> Result<(), StoreError> {
        self.txn
            .prepare_cached(
                "DELETE FROM asset_tags WHERE asset_uuid IN
               (SELECT asset_uuid FROM assets WHERE bundle_uuid = ?1)",
            )?
            .execute([bundle.0.as_slice()])?;
        self.txn
            .prepare_cached("DELETE FROM assets WHERE bundle_uuid = ?1")?
            .execute([bundle.0.as_slice()])?;
        Ok(())
    }

    /// Publish (or republish) an asset row whose tags are `rec.tags`;
    /// tags replace wholesale.
    pub fn upsert_asset(&mut self, rec: &AssetRecord) -> Result<(), StoreError> {
        self.write_asset(rec, None)
    }

    /// Publish (or republish) an asset row whose tags a refinement in the
    /// same input computes (§10's two-phase publication): until then a tag
    /// query that could select it fails, never answers from no tags.
    pub fn upsert_pending_asset(&mut self, rec: &AssetRecord) -> Result<(), StoreError> {
        self.write_asset(rec, Some(TAG_PENDING))
    }

    fn write_asset(&mut self, rec: &AssetRecord, tag_poison: Option<&str>) -> Result<(), StoreError> {
        self.txn
            .prepare_cached(
                "INSERT INTO assets(
                 asset_uuid, bundle_uuid, local_id, type_uuid, logical_hash, authoring_only,
                 terminal_type, tag_poison
             ) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8)
             ON CONFLICT(asset_uuid) DO UPDATE SET
               bundle_uuid = excluded.bundle_uuid, local_id = excluded.local_id,
               type_uuid = excluded.type_uuid, logical_hash = excluded.logical_hash,
               authoring_only = excluded.authoring_only,
               terminal_type = excluded.terminal_type,
               tag_poison = excluded.tag_poison, tag_module = NULL",
            )?
            .execute(
                rusqlite::params![
                    rec.asset.0.as_slice(),
                    rec.bundle.0.as_slice(),
                    rec.local_id,
                    rec.type_uuid.0.as_slice(),
                    rec.logical_hash.0.as_slice(),
                    i64::from(rec.authoring_only),
                    rec.terminal_type.map(|terminal| terminal.0.to_vec()),
                    tag_poison,
                ],
            )?;
        self.txn
            .prepare_cached("DELETE FROM asset_tags WHERE asset_uuid = ?1")?
            .execute([rec.asset.0.as_slice()])?;
        for (tag, value) in &rec.tags {
            self.txn
                .prepare_cached(
                    "INSERT OR REPLACE INTO asset_tags(asset_uuid, tag, value) VALUES (?1, ?2, ?3)",
                )?
                .execute(rusqlite::params![rec.asset.0.as_slice(), tag, value])?;
        }
        Ok(())
    }

    /// Mark an asset's tags pending a refinement (the conservative half of
    /// a two-phase tag publication, see [`Self::upsert_pending_asset`]).
    pub fn set_tag_index_pending(&mut self, asset: AssetUuid) -> Result<(), StoreError> {
        self.txn
            .prepare_cached(
                "UPDATE assets SET tag_poison = ?2, tag_module = NULL WHERE asset_uuid = ?1",
            )?
            .execute(rusqlite::params![asset.0.as_slice(), TAG_PENDING])?;
        Ok(())
    }

    /// Name `asset`, a runtime entry of `bundle`, the asset the bundle's
    /// path resolves to (§9). Call after [`InputTxn::upsert_bundle`], which
    /// clears it, and the asset's own row.
    pub fn set_primary_asset(
        &mut self,
        bundle: BundleUuid,
        asset: AssetUuid,
    ) -> Result<(), StoreError> {
        let set = self
            .txn
            .prepare_cached(
                "UPDATE bundles SET primary_asset = ?2 WHERE bundle_uuid = ?1
                   AND (SELECT authoring_only FROM assets
                        WHERE asset_uuid = ?2 AND bundle_uuid = ?1) = 0",
            )?
            .execute(rusqlite::params![bundle.0.as_slice(), asset.0.as_slice()])?;
        if set == 1 {
            return Ok(());
        }
        let role: Option<i64> = self
            .txn
            .query_row(
                "SELECT authoring_only FROM assets WHERE asset_uuid = ?1",
                [asset.0.as_slice()],
                |row| row.get(0),
            )
            .optional()?;
        Err(match role {
            Some(1) => StoreError::RoleIneligible { asset },
            _ => StoreError::InvalidConfiguration {
                error: format!("bundle {bundle} has no runtime entry {asset} to make primary"),
            },
        })
    }

    /// Publish the bundle-scoped poison row (§7, §13). Scope is decided
    /// by the caller-supplied **validated skeleton** parsed from the
    /// CURRENT malformed bytes — never by prior metadata: the skeleton's
    /// rows replace every prior `bundles`/`assets` row for the file's
    /// UUIDs, so resolves against them (old and newly introduced alike)
    /// return the stable `Failed`, and queries whose selectors match the
    /// skeleton's entries fail naming this bundle. A caller that could
    /// not extract the complete skeleton publishes a file-scoped
    /// namespace error instead ([`InputTxn::set_namespace_errors`]).
    pub fn poison_bundle(
        &mut self,
        skeleton: &NamespaceSkeleton,
        error: &str,
    ) -> Result<(), StoreError> {
        // Replace, never retain: the prior rows describe the old bytes.
        self.remove_owned_asset_rows(skeleton.bundle)?;
        self.clear_path_refs(skeleton.bundle)?;
        self.txn
            .prepare_cached(
                "INSERT INTO bundles(bundle_uuid, root_id, path, format_version, content_hash, poison)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6)
             ON CONFLICT(bundle_uuid) DO UPDATE SET
               root_id = excluded.root_id, path = excluded.path,
               format_version = excluded.format_version,
               content_hash = excluded.content_hash, poison = excluded.poison,
               origin_rules_bundle = NULL, origin_rule = NULL,
               origin_group_root = NULL, origin_group_path = NULL,
               import_watched = 0, primary_asset = NULL",
            )?
            .execute(
                rusqlite::params![
                    skeleton.bundle.0.as_slice(),
                    skeleton.root.0,
                    skeleton.path,
                    skeleton.format_version,
                    skeleton.content_hash.0.as_slice(),
                    error,
                ],
            )?;
        for entry in &skeleton.entries {
            // Plain INSERT: a skeleton UUID colliding with another
            // bundle's row is a cross-file identity collision — §7 keeps
            // a namespace error for those, and the constraint
            // failure surfaces rather than silently reassigning the row.
            self.txn
                .prepare_cached(
                    "INSERT INTO assets(
                     asset_uuid, bundle_uuid, local_id, type_uuid, logical_hash, authoring_only
                 ) VALUES (?1, ?2, ?3, ?4, NULL, ?5)",
                )?
                .execute(
                    rusqlite::params![
                        entry.asset.0.as_slice(),
                        skeleton.bundle.0.as_slice(),
                        entry.local_id,
                        entry.type_uuid.0.as_slice(),
                        i64::from(entry.authoring_only),
                    ],
                )?;
            for (tag, value) in &entry.tags {
                self.txn
                    .prepare_cached(
                        "INSERT OR REPLACE INTO asset_tags(asset_uuid, tag, value) VALUES (?1, ?2, ?3)",
                    )?
                    .execute(rusqlite::params![entry.asset.0.as_slice(), tag, value])?;
            }
        }
        Ok(())
    }

}

impl Store {

    /// Complete tag extraction after the owning input transaction has made
    /// the candidate namespace readable but before that version is exposed by
    /// the RPC publication step. This deliberately does not
    /// advance the input version: a crash between the namespace transaction
    /// and this refinement leaves the conservative pending poison intact.
    /// The daemon runs it inside the input that publishes the namespace it
    /// read (`refine_tag_index` takes that input's proof), so the rows it
    /// writes are of the version they were read at.
    pub fn refine_unpublished_tag_index(
        &mut self,
        updates: &[TagIndexUpdate],
    ) -> Result<(), StoreError> {
        self.write_txn(|store| {
            let mut assets = BTreeSet::new();
            let txn: &rusqlite::Connection = &store.read.conn;
            for update in updates {
                if !assets.insert(update.asset) {
                    return Err(StoreError::InvalidConfiguration {
                        error: format!("duplicate tag-index update for {}", update.asset),
                    });
                }
                if update.poison.is_some() && !update.tags.is_empty() {
                    return Err(StoreError::InvalidConfiguration {
                        error: format!("poisoned tag-index update {} carried tags", update.asset),
                    });
                }
                txn
                    .prepare_cached("DELETE FROM asset_tags WHERE asset_uuid = ?1")?
                    .execute([update.asset.0.as_slice()])?;
                for (tag, value) in &update.tags {
                    txn
                        .prepare_cached(
                            "INSERT INTO asset_tags(asset_uuid, tag, value) VALUES (?1, ?2, ?3)",
                        )?
                        .execute(rusqlite::params![update.asset.0.as_slice(), tag, value])?;
                }
                let updated = txn
                    .prepare_cached(
                        "UPDATE assets SET tag_poison = ?2, tag_module = ?3 WHERE asset_uuid = ?1",
                    )?
                    .execute(rusqlite::params![
                        update.asset.0.as_slice(),
                        update.poison,
                        update.dylib_hash.map(|hash| hash.to_vec()),
                    ])?;
                if updated == 0 {
                    return Err(StoreError::InvalidConfiguration {
                        error: format!("tag-index update names missing asset {}", update.asset),
                    });
                }
            }
            Ok(())
        })
    }

    /// Record `epochs` as the tag epoch of every authored type, inside the
    /// open input, and mark pending the tag rows of each type whose epoch
    /// changed (see [`StoreReader::tag_epoch_changes`]): a refinement in the
    /// same input redoes exactly those. Returns the changed types. It costs
    /// the authored types plus the assets of the changed ones.
    pub fn replace_tag_epochs(
        &mut self,
        epochs: &BTreeMap<TypeUuid, [u8; 32]>,
    ) -> Result<BTreeSet<TypeUuid>, StoreError> {
        let changed = self.tag_epoch_changes(epochs)?;
        if changed.is_empty() {
            return Ok(changed);
        }
        self.write_txn(|store| {
            let txn: &rusqlite::Connection = &store.read.conn;
            for type_uuid in &changed {
                let type_uuid_bytes = type_uuid.0.as_slice();
                txn
                    .prepare_cached(
                        "UPDATE assets SET tag_poison = ?2, tag_module = NULL WHERE type_uuid = ?1",
                    )?
                    .execute(rusqlite::params![type_uuid_bytes, TAG_PENDING])?;
                txn
                    .prepare_cached("DELETE FROM tag_epochs WHERE type_uuid = ?1")?
                    .execute([type_uuid_bytes])?;
                if let Some(epoch) = epochs.get(type_uuid) {
                    txn
                        .prepare_cached("INSERT INTO tag_epochs(type_uuid, epoch) VALUES (?1, ?2)")?
                        .execute(rusqlite::params![type_uuid_bytes, epoch.as_slice()])?;
                }
            }
            Ok(())
        })?;
        Ok(changed)
    }
}

impl StoreReader {
    /// `asset`'s tag state; `None` when it has no row.
    pub fn tag_index_state(&self, asset: AssetUuid) -> Result<Option<TagIndexState>, StoreError> {
        Ok(self
            .conn
            .prepare_cached("SELECT tag_module, tag_poison FROM assets WHERE asset_uuid = ?1")?
            .query_row([asset.0.as_slice()], |row| {
                Ok(TagIndexState {
                    dylib_hash: row.get::<_, Option<Vec<u8>>>(0)?.map(blob32),
                    poison: row.get(1)?,
                })
            })
            .optional()?)
    }

    pub fn bundle_at(&self, root_name: &str, path: &str) -> Result<Option<BundleMeta>, StoreError> {
        let bundle = self
            .conn
            .query_row(
                "SELECT b.bundle_uuid FROM bundles b JOIN roots r USING (root_id)
                 WHERE r.name = ?1 AND b.path = ?2",
                rusqlite::params![root_name, path],
                |r| r.get::<_, Vec<u8>>(0),
            )
            .optional()?;
        match bundle {
            Some(bundle) => self.bundle(BundleUuid(blob16(bundle))),
            None => Ok(None),
        }
    }

    /// One bundle's physical row. Poisoned bundles still *have* a row —
    /// the poison is part of it.
    pub fn bundle(&self, bundle: BundleUuid) -> Result<Option<BundleMeta>, StoreError> {
        Ok(self
            .conn
            .prepare_cached(&format!(
                "SELECT {BUNDLE_COLUMNS} FROM bundles WHERE bundle_uuid = ?1"
            ))?
            .query_row([bundle.0.as_slice()], bundle_meta_row)
            .optional()?)
    }

    /// Complete deterministic bundle projection used to synthesize deletes
    /// during startup reconciliation and to hydrate the RPC metadata index.
    pub fn all_bundles(&self) -> Result<Vec<BundleMeta>, StoreError> {
        self.query_rows(
            &format!("SELECT {BUNDLE_COLUMNS} FROM bundles ORDER BY bundle_uuid"),
            [],
            bundle_meta_row,
        )
    }

    /// Visit every bundle row with its root's name, by bundle UUID: one
    /// streamed join, for a complete scan's publication.
    pub fn for_each_bundle_with_root_name(
        &self,
        mut visit: impl FnMut(String, BundleMeta) -> Result<(), StoreError>,
    ) -> Result<(), StoreError> {
        let mut statement = self.conn.prepare_cached(&format!(
            "SELECT {BUNDLE_COLUMNS}, r.name FROM bundles JOIN roots r USING (root_id)
             ORDER BY bundle_uuid"
        ))?;
        debug_assert_eq!(statement.column_count(), BUNDLE_COLUMN_COUNT + 1);
        let mut rows = statement.query([])?;
        while let Some(row) = rows.next()? {
            // The root name follows the bundle columns.
            visit(row.get(BUNDLE_COLUMN_COUNT)?, bundle_meta_row(row)?)?;
        }
        Ok(())
    }

    /// The bundle rows at logical `path` in any root, by bundle UUID.
    pub fn bundles_at_path(&self, path: &str) -> Result<Vec<BundleMeta>, StoreError> {
        self.query_rows(
            &format!("SELECT {BUNDLE_COLUMNS} FROM bundles WHERE path = ?1 ORDER BY bundle_uuid"),
            [path],
            bundle_meta_row,
        )
    }

    /// Every bundle a directory import generated (its row carries a
    /// [`DirectoryOrigin`]), by bundle UUID: a walk of the partial
    /// `bundles_by_origin`, whose rows are sorted after (the order alone
    /// would walk every bundle's primary key).
    pub fn generated_bundles(&self) -> Result<Vec<BundleMeta>, StoreError> {
        self.query_rows(
            &format!(
                "SELECT {BUNDLE_COLUMNS} FROM bundles INDEXED BY bundles_by_origin
                 WHERE origin_rules_bundle IS NOT NULL ORDER BY bundle_uuid"
            ),
            [],
            bundle_meta_row,
        )
    }

    /// The bundles whose import record is watched, by UUID: a walk of the
    /// partial `bundles_import_watched`.
    pub fn import_watched_bundles(&self) -> Result<Vec<BundleUuid>, StoreError> {
        self.bundle_ids(
            "SELECT bundle_uuid FROM bundles INDEXED BY bundles_import_watched
             WHERE import_watched ORDER BY bundle_uuid",
            [],
        )
    }

    /// Every poisoned bundle, by UUID.
    pub fn poisoned_bundles(&self) -> Result<Vec<BundleUuid>, StoreError> {
        self.bundle_ids(
            "SELECT bundle_uuid FROM bundles WHERE poison IS NOT NULL ORDER BY bundle_uuid",
            [],
        )
    }

    /// Every bundle whose reference fields name logical `path` (§13's
    /// `bundle_path_refs`), by UUID.
    pub fn bundles_referencing_path(&self, path: &str) -> Result<Vec<BundleUuid>, StoreError> {
        self.bundle_ids(
            "SELECT bundle_uuid FROM bundle_path_refs WHERE target = ?1 ORDER BY bundle_uuid",
            [path],
        )
    }

    /// The logical path strings `bundle`'s reference fields name.
    pub fn bundle_path_refs(&self, bundle: BundleUuid) -> Result<BTreeSet<String>, StoreError> {
        Ok(self
            .query_rows(
                "SELECT target FROM bundle_path_refs WHERE bundle_uuid = ?1 ORDER BY target",
                [bundle.0.as_slice()],
                |row| row.get::<_, String>(0),
            )?
            .into_iter()
            .collect())
    }

    fn bundle_ids<P: rusqlite::Params>(
        &self,
        sql: &str,
        params: P,
    ) -> Result<Vec<BundleUuid>, StoreError> {
        self.query_rows(sql, params, |row| {
            Ok(BundleUuid(blob16(row.get::<_, Vec<u8>>(0)?)))
        })
    }

    /// Whether an `assets` row (skeleton rows included) exists for `asset`.
    pub fn asset_exists(&self, asset: AssetUuid) -> Result<bool, StoreError> {
        Ok(self
            .conn
            .prepare_cached("SELECT EXISTS(SELECT 1 FROM assets WHERE asset_uuid = ?1)")?
            .query_row([asset.0.as_slice()], |row| row.get(0))?)
    }

    /// Raw deterministic identity set for one bundle, including poisoned
    /// skeleton rows. Incremental healing needs the prior UUID set without
    /// interpreting poisoned metadata or enumerating unrelated bundles.
    pub fn asset_ids_in_bundle(
        &self,
        bundle: BundleUuid,
    ) -> Result<BTreeSet<AssetUuid>, StoreError> {
        let mut statement = self
            .conn
            .prepare("SELECT asset_uuid FROM assets WHERE bundle_uuid = ?1 ORDER BY asset_uuid")?;
        let rows = statement.query_map([bundle.0.as_slice()], |row| row.get::<_, Vec<u8>>(0))?;
        rows.map(|row| row.map(|bytes| AssetUuid(blob16(bytes))))
            .collect::<Result<BTreeSet<_>, _>>()
            .map_err(StoreError::from)
    }

    /// Every bundle's primary asset by (logical path, root): several roots
    /// at one path remain several candidates; no root is selected here.
    pub fn all_path_entries(&self) -> Result<Vec<(String, RootId, AssetUuid)>, StoreError> {
        let mut statement = self
            .conn
            .prepare(PRIMARY_ASSETS)?;
        let rows = statement.query_map([], |row| {
            Ok((
                row.get(0)?,
                RootId(row.get(1)?),
                AssetUuid(blob16(row.get(2)?)),
            ))
        })?;
        rows.collect::<Result<Vec<_>, _>>()
            .map_err(StoreError::from)
    }

    /// Current logical candidates for one normalized path: the primaries of
    /// its bundles in every root. Ordinary watcher publications use this
    /// bounded lookup instead of enumerating every bundle.
    pub fn path_assets(&self, path: &str) -> Result<BTreeSet<AssetUuid>, StoreError> {
        let mut statement = self
            .conn
            .prepare_cached(PATH_PRIMARIES)?;
        let rows = statement.query_map([path], |row| row.get::<_, Vec<u8>>(0))?;
        rows.map(|row| row.map(|bytes| AssetUuid(blob16(bytes))))
            .collect::<Result<BTreeSet<_>, _>>()
            .map_err(StoreError::from)
    }

    /// Raw deterministic asset identity set, including poisoned skeleton rows.
    /// Startup reconciliation uses it only to remove identities absent from a
    /// healed full scan; it does not expose skeleton metadata.
    pub fn all_asset_ids(&self) -> Result<Vec<AssetUuid>, StoreError> {
        let mut statement = self
            .conn
            .prepare("SELECT asset_uuid FROM assets ORDER BY asset_uuid")?;
        let rows = statement.query_map([], |row| row.get::<_, Vec<u8>>(0))?;
        rows.map(|row| row.map(|bytes| AssetUuid(blob16(bytes))))
            .collect::<Result<Vec<_>, _>>()
            .map_err(StoreError::from)
    }

    /// The tag-index rows a refinement under the pipeline module
    /// `dylib_hash` (none when no module is loaded) must redo, each with its
    /// asset's bundle: poisoned rows (pending ones included, among them the
    /// rows of every type whose tag epoch changed, see
    /// [`Store::replace_tag_epochs`]) and migrated rows of another module.
    /// Every other row already holds what refining it would write. Each kind
    /// is one search of its index, so this costs the rows it returns.
    pub fn stale_tag_index_assets(
        &self,
        dylib_hash: Option<[u8; 32]>,
    ) -> Result<BTreeMap<AssetUuid, BundleUuid>, StoreError> {
        // No module: every migrated row is stale, and every blob sorts
        // after the empty one.
        let module = dylib_hash.map_or_else(Vec::new, |hash| hash.to_vec());
        let mut statement = self.conn.prepare_cached(
            "SELECT asset_uuid, bundle_uuid FROM assets INDEXED BY assets_tag_poisoned
             WHERE tag_poison IS NOT NULL
             UNION SELECT asset_uuid, bundle_uuid FROM assets INDEXED BY assets_tag_migrated
             WHERE tag_module < ?1
             UNION SELECT asset_uuid, bundle_uuid FROM assets INDEXED BY assets_tag_migrated
             WHERE tag_module > ?1",
        )?;
        let rows = statement.query_map(rusqlite::params![module], |row| {
            Ok((
                AssetUuid(blob16(row.get::<_, Vec<u8>>(0)?)),
                BundleUuid(blob16(row.get::<_, Vec<u8>>(1)?)),
            ))
        })?;
        rows.collect::<Result<BTreeMap<_, _>, _>>()
            .map_err(StoreError::from)
    }

    /// The types whose tag epoch in `epochs` differs from the one their tag
    /// rows were refined under; a type on one side only differs. One read of
    /// `tag_epochs`, whose size is the number of authored types.
    pub fn tag_epoch_changes(
        &self,
        epochs: &BTreeMap<TypeUuid, [u8; 32]>,
    ) -> Result<BTreeSet<TypeUuid>, StoreError> {
        let mut statement = self
            .conn
            .prepare_cached("SELECT type_uuid, epoch FROM tag_epochs")?;
        let stored = statement
            .query_map([], |row| {
                Ok((
                    TypeUuid(blob16(row.get::<_, Vec<u8>>(0)?)),
                    blob32(row.get::<_, Vec<u8>>(1)?),
                ))
            })?
            .collect::<Result<BTreeMap<_, _>, _>>()?;
        Ok(stored
            .keys()
            .chain(epochs.keys())
            .filter(|type_uuid| stored.get(type_uuid) != epochs.get(type_uuid))
            .copied()
            .collect())
    }

    /// The (root, path) of every bundle holding an asset of `type_uuid`
    /// (only the poisoned bundles when `poisoned`): one search of
    /// `assets_by_type`, so it costs that type's assets.
    pub fn bundle_sources_of_type(
        &self,
        type_uuid: TypeUuid,
        poisoned: bool,
    ) -> Result<BTreeSet<(String, String)>, StoreError> {
        let sql = if poisoned {
            "SELECT r.name, b.path FROM assets a JOIN bundles b USING (bundle_uuid)
             JOIN roots r USING (root_id)
             WHERE a.type_uuid = ?1 AND b.poison IS NOT NULL"
        } else {
            "SELECT r.name, b.path FROM assets a JOIN bundles b USING (bundle_uuid)
             JOIN roots r USING (root_id)
             WHERE a.type_uuid = ?1"
        };
        let mut statement = self.conn.prepare_cached(sql)?;
        let rows = statement.query_map([type_uuid.0.as_slice()], |row| {
            Ok((row.get::<_, String>(0)?, row.get::<_, String>(1)?))
        })?;
        rows.collect::<Result<BTreeSet<_>, _>>()
            .map_err(StoreError::from)
    }

    /// Raw deterministic asset-to-bundle projection, including poisoned
    /// skeleton rows. A whole-namespace bulk read no publication makes: the
    /// tests compare the bounded reads against it.
    pub fn all_asset_bundles(&self) -> Result<BTreeMap<AssetUuid, BundleUuid>, StoreError> {
        let mut statement = self
            .conn
            .prepare("SELECT asset_uuid, bundle_uuid FROM assets ORDER BY asset_uuid")?;
        let rows = statement.query_map([], |row| {
            Ok((
                AssetUuid(blob16(row.get::<_, Vec<u8>>(0)?)),
                BundleUuid(blob16(row.get::<_, Vec<u8>>(1)?)),
            ))
        })?;
        rows.collect::<Result<BTreeMap<_, _>, _>>()
            .map_err(StoreError::from)
    }

    /// Visit every asset row's (asset, bundle), skeleton rows included, in
    /// asset UUID order, without collecting them.
    pub fn for_each_asset_bundle(
        &self,
        mut visit: impl FnMut(AssetUuid, BundleUuid) -> Result<(), StoreError>,
    ) -> Result<(), StoreError> {
        let mut statement = self
            .conn
            .prepare_cached("SELECT asset_uuid, bundle_uuid FROM assets ORDER BY asset_uuid")?;
        let mut rows = statement.query([])?;
        while let Some(row) = rows.next()? {
            visit(
                AssetUuid(blob16(row.get::<_, Vec<u8>>(0)?)),
                BundleUuid(blob16(row.get::<_, Vec<u8>>(1)?)),
            )?;
        }
        Ok(())
    }

    /// Visit every asset row's (bundle, asset), skeleton rows included, in
    /// (bundle, asset) order: each bundle's assets arrive together, read
    /// from the `assets_by_bundle` index alone.
    pub fn for_each_bundle_asset(
        &self,
        mut visit: impl FnMut(BundleUuid, AssetUuid) -> Result<(), StoreError>,
    ) -> Result<(), StoreError> {
        let mut statement = self.conn.prepare_cached(
            "SELECT bundle_uuid, asset_uuid FROM assets ORDER BY bundle_uuid, asset_uuid",
        )?;
        let mut rows = statement.query([])?;
        while let Some(row) = rows.next()? {
            visit(
                BundleUuid(blob16(row.get::<_, Vec<u8>>(0)?)),
                AssetUuid(blob16(row.get::<_, Vec<u8>>(1)?)),
            )?;
        }
        Ok(())
    }

    /// Visit [`Self::all_path_entries`]'s rows in its (path, root) order
    /// without collecting them.
    pub fn for_each_path_entry(
        &self,
        mut visit: impl FnMut(String, RootId, AssetUuid) -> Result<(), StoreError>,
    ) -> Result<(), StoreError> {
        let mut statement = self
            .conn
            .prepare_cached(PRIMARY_ASSETS)?;
        let mut rows = statement.query([])?;
        while let Some(row) = rows.next()? {
            visit(row.get(0)?, RootId(row.get(1)?), AssetUuid(blob16(row.get(2)?)))?;
        }
        Ok(())
    }

    /// Every generated bundle a rules bundle owns (§2, §8): the
    /// scan-derived ownership index orphan tracking re-derives after
    /// daemon-state loss — never precious.
    pub fn bundles_owned_by(&self, rules: BundleUuid) -> Result<Vec<BundleUuid>, StoreError> {
        let mut stmt = self.conn.prepare(
            "SELECT bundle_uuid FROM bundles WHERE origin_rules_bundle = ?1 ORDER BY bundle_uuid",
        )?;
        let rows = stmt.query_map([rules.0.as_slice()], |r| r.get::<_, Vec<u8>>(0))?;
        let mut out = Vec::new();
        for row in rows {
            out.push(BundleUuid(blob16(row?)));
        }
        Ok(out)
    }

    /// Every rules bundle a generated bundle names (§8), in order, with
    /// its own (root, path) while it has a row: one seek of
    /// `bundles_by_origin` per rules bundle, however many bundles each
    /// generated.
    pub fn generating_rules_bundles(
        &self,
    ) -> Result<Vec<(BundleUuid, Option<(RootId, String)>)>, StoreError> {
        let mut next = self.conn.prepare_cached(NEXT_RULES_BUNDLE)?;
        let mut found = Vec::new();
        let mut after = Vec::new();
        loop {
            let row = next
                .query_row([&after], |row| {
                    Ok((
                        row.get::<_, Vec<u8>>(0)?,
                        row.get::<_, Option<i64>>(1)?,
                        row.get::<_, Option<String>>(2)?,
                    ))
                })
                .optional()?;
            let Some((rules, root, path)) = row else {
                return Ok(found);
            };
            let source = root.zip(path).map(|(root, path)| (RootId(root), path));
            found.push((BundleUuid(blob16(rules.clone())), source));
            after = rules;
        }
    }

    /// §13 `MetadataSnapshot::entry` semantics: `Ok(None)` is a
    /// recordable miss; a namespace error or a poisoned owning bundle is
    /// `Err`, never last-good metadata.
    pub fn entry(&self, asset: AssetUuid) -> Result<Option<EntryMeta>, StoreError> {
        Ok(self.entry_with_bundle(asset)?.map(|(entry, _)| entry))
    }

    /// [`Self::entry`] with its owning bundle's row (`None` when the asset
    /// row names a bundle with no row), in one statement ([`ENTRY`]).
    pub fn entry_with_bundle(
        &self,
        asset: AssetUuid,
    ) -> Result<Option<(EntryMeta, Option<BundleMeta>)>, StoreError> {
        let mut statement = self.conn.prepare_cached(ENTRY)?;
        debug_assert_eq!(statement.column_count(), BUNDLE_COLUMN_COUNT + 7);
        let mut rows = statement.query([asset.0.as_slice()])?;
        let Some(row) = rows.next()? else {
            return Ok(None);
        };
        let at = |column: usize| BUNDLE_COLUMN_COUNT + column;
        // `bundle_uuid` is the asset row's (USING); `root_id` is the
        // bundle row's, NULL when it has none.
        let bundle = BundleUuid(blob16(row.get(0)?));
        let bundle_meta = match row.get::<_, Option<i64>>(1)? {
            Some(_) => Some(bundle_meta_row(row)?),
            None => None,
        };
        if let Some(error) = row.get::<_, Option<String>>(at(4))? {
            return Err(StoreError::BundlePoisoned { bundle, error });
        }
        let local_id: String = row.get(at(0))?;
        let type_uuid = TypeUuid(blob16(row.get(at(1))?));
        // NULL only on a skeleton row (§7), whose owning bundle is
        // poisoned: the poison gate above fires first. Not poisoned ⇒
        // never a skeleton row, by the healing invariant (upsert_bundle
        // drops skeleton rows whenever a poison clears). A NULL here is
        // store corruption and surfaces as a typed column error, never a
        // panic.
        let logical_hash = row.get::<_, Option<Vec<u8>>>(at(2))?.ok_or_else(|| {
            StoreError::Sqlite(rusqlite::Error::InvalidColumnType(
                at(2),
                "logical_hash".to_owned(),
                rusqlite::types::Type::Null,
            ))
        })?;
        let authoring_only = row.get::<_, i64>(at(3))? != 0;
        // One row per tag, by tag; a single row of NULLs when untagged.
        let mut tags = BTreeMap::new();
        let mut row = Some(row);
        while let Some(current) = row {
            if let Some(tag) = current.get::<_, Option<String>>(at(5))? {
                tags.insert(tag, current.get::<_, Option<String>>(at(6))?);
            }
            row = rows.next()?;
        }
        Ok(Some((
            EntryMeta {
                asset,
                bundle,
                local_id,
                type_uuid,
                logical_hash: LogicalHash(blob32(logical_hash)),
                authoring_only,
                tags,
            },
            bundle_meta,
        )))
    }

}

macro_rules! bundle_columns {
    () => {
        "bundle_uuid, root_id, path, format_version, content_hash,
     origin_rules_bundle, origin_rule, origin_group_root, origin_group_path, import_watched"
    };
}
const BUNDLE_COLUMNS: &str = bundle_columns!();
/// The least rules bundle a generated bundle names after `?1`, with its
/// row's source if it has one.
const NEXT_RULES_BUNDLE: &str = "SELECT g.origin_rules_bundle, r.root_id, r.path
     FROM bundles g INDEXED BY bundles_by_origin
     LEFT JOIN bundles r ON r.bundle_uuid = g.origin_rules_bundle
     WHERE g.origin_rules_bundle IS NOT NULL AND g.origin_rules_bundle > ?1
     ORDER BY g.origin_rules_bundle LIMIT 1";
/// Every bundle's primary asset by (path, root): a walk of `bundles_by_path`.
const PRIMARY_ASSETS: &str = "SELECT path, root_id, primary_asset FROM bundles INDEXED BY bundles_by_path
     WHERE primary_asset IS NOT NULL ORDER BY path, root_id";
/// The primaries of the bundles at one path: a search of `bundles_by_path`.
pub(crate) const PATH_PRIMARIES: &str =
    "SELECT primary_asset FROM bundles WHERE path = ?1 AND primary_asset IS NOT NULL";
/// The number of columns in [`BUNDLE_COLUMNS`]; a column selected after them
/// has this index.
const BUNDLE_COLUMN_COUNT: usize = 10;
/// An asset's entry: its owning bundle's row (NULL columns when it has
/// none, `bundle_uuid` the asset row's by USING), its own columns, the
/// bundle's poison and one row per tag (NULLs when untagged), by tag.
pub(crate) const ENTRY: &str = concat!(
    "SELECT ",
    bundle_columns!(),
    ", local_id, type_uuid, logical_hash, authoring_only, poison, tag, value
     FROM assets LEFT JOIN bundles USING (bundle_uuid) LEFT JOIN asset_tags USING (asset_uuid)
     WHERE asset_uuid = ?1 ORDER BY tag"
);

fn bundle_meta_row(row: &rusqlite::Row<'_>) -> rusqlite::Result<BundleMeta> {
    let origin = match (
        row.get::<_, Option<Vec<u8>>>(5)?,
        row.get::<_, Option<Vec<u8>>>(6)?,
        row.get::<_, Option<String>>(7)?,
        row.get::<_, Option<String>>(8)?,
    ) {
        (Some(rules), Some(rule), Some(group_root), Some(group_path)) => Some(DirectoryOrigin {
            rules_bundle: BundleUuid(blob16(rules)),
            rule: DirectoryRuleId(blob16(rule)),
            group_root,
            group_path,
        }),
        _ => None,
    };
    Ok(BundleMeta {
        bundle: BundleUuid(blob16(row.get(0)?)),
        root: RootId(row.get(1)?),
        path: row.get(2)?,
        format_version: row.get(3)?,
        content_hash: ContentHash(blob32(row.get(4)?)),
        origin,
        import_watched: row.get(9)?,
    })
}

/// A conjunction of asset selectors, answered by SQL over the `assets`,
/// `bundles` and `asset_tags` indexes. An absent selector selects every row.
/// This is the one asset query: build traces, codegen and the RPC each turn
/// their query into a filter and ask [`StoreReader::namespace_assets_matching`]
/// or [`StoreReader::served_assets_matching`] (DESIGN.md §13, asset queries).
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct AssetFilter {
    pub asset: Option<AssetUuid>,
    pub bundle: Option<BundleUuid>,
    /// The owning bundle's logical path, exactly.
    pub bundle_path: Option<String>,
    /// The final segment of the owning bundle's logical path, exactly.
    pub bundle_name: Option<String>,
    pub local_id: Option<String>,
    pub authored_type: Option<TypeUuid>,
    /// The authored type is one of these: a build's terminal type, which
    /// depends on its target, asks for the authored types whose chains end
    /// there. An empty set selects nothing.
    pub authored_type_in: Option<Vec<TypeUuid>>,
    /// The served terminal type (`assets.terminal_type`).
    pub terminal_type: Option<TypeUuid>,
    /// A search tag, with its value when `Some`: an asset carrying the tag
    /// with any value (`None`) or exactly that value.
    pub tag: Option<(String, Option<String>)>,
    /// Strings the owning bundle's logical path starts with; every one must
    /// hold.
    pub path_prefixes: Vec<String>,
    /// Only authoring-only rows (`Some(true)`) or only runtime rows. Alone,
    /// `Some(false)` selects every runtime row: it narrows nothing.
    pub authoring_only: Option<bool>,
}

/// What an asset query answers: the rows it selects, by asset UUID, or the
/// poisoned bundles (by UUID) whose rows it could select.
pub type AssetAnswer = Result<Vec<MatchedAsset>, Vec<BundleUuid>>;

/// The selector a filter's query is driven from, and so the index it
/// names. SQLite keeps no statistics here and cannot tell a basename from
/// a type by selectivity, so the filter decides: an identity or exact name
/// first (asset, bundle, bundle path, bundle name, local id), then the
/// poisoned tag-index rows (normally none; only when looking for them), a
/// tag value, an authored type, a path prefix, a set of authored types, a
/// terminal type and a bare tag, then the authoring-only rows. Every other
/// selector is checked on the rows the driver finds.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Driver {
    Asset,
    Bundle,
    BundlePath,
    BundleName,
    LocalId,
    TagPoisoned,
    TagPoisonedTypes,
    Tag,
    AuthoredType,
    PathPrefix,
    AuthoredTypes,
    TerminalType,
    AuthoringOnly,
    Everything,
}

impl AssetFilter {
    /// With the keys of a path glob (see [`crate::files::GlobKeys`]): its
    /// literal prefix and the final segment its literal tail names.
    pub fn with_glob_keys(mut self, keys: crate::files::GlobKeys<'_>) -> Self {
        if !keys.prefix.is_empty() {
            self.path_prefixes.push(keys.prefix.to_owned());
        }
        if self.bundle_name.is_none() {
            self.bundle_name = keys.name.map(str::to_owned);
        }
        self
    }

    /// The one path prefix the others imply (every path starting with the
    /// longest starts with each shorter one, or none matches): `Err(())`
    /// when two prefixes contradict each other.
    fn path_prefix(&self) -> Result<Option<&str>, ()> {
        let longest = self
            .path_prefixes
            .iter()
            .map(String::as_str)
            .filter(|prefix| !prefix.is_empty())
            .max_by_key(|prefix| prefix.len());
        match longest {
            Some(longest) if self.path_prefixes.iter().any(|p| !longest.starts_with(p.as_str())) => {
                Err(())
            }
            longest => Ok(longest),
        }
    }

    /// Whether no row can satisfy the filter, without asking SQLite.
    fn selects_nothing(&self) -> bool {
        self.path_prefix().is_err()
            || self.authored_type_in.as_ref().is_some_and(Vec::is_empty)
    }

    fn driver(&self, tag_poisoned: bool) -> Driver {
        let tag_value = self.tag.as_ref().is_some_and(|(_, value)| value.is_some());
        if self.asset.is_some() {
            Driver::Asset
        } else if self.bundle.is_some() {
            Driver::Bundle
        } else if self.bundle_path.is_some() {
            Driver::BundlePath
        } else if self.bundle_name.is_some() {
            Driver::BundleName
        } else if self.local_id.is_some() {
            Driver::LocalId
        } else if tag_poisoned && (self.authored_type.is_some() || self.authored_type_in.is_some()) {
            // A typed query walks the poisoned rows of its types only.
            Driver::TagPoisonedTypes
        } else if tag_poisoned {
            Driver::TagPoisoned
        } else if tag_value {
            Driver::Tag
        } else if self.authored_type.is_some() {
            Driver::AuthoredType
        } else if matches!(self.path_prefix(), Ok(Some(_))) {
            Driver::PathPrefix
        } else if self.authored_type_in.is_some() {
            Driver::AuthoredTypes
        } else if self.terminal_type.is_some() {
            Driver::TerminalType
        } else if self.tag.is_some() {
            Driver::Tag
        } else if self.authoring_only == Some(true) {
            Driver::AuthoringOnly
        } else {
            Driver::Everything
        }
    }

    /// The `assets a`, `bundles b` join the driver walks, outer table
    /// first, each table on the index it must use.
    fn sql_from(driver: Driver) -> &'static str {
        const BY_ASSET: &str = "assets a INDEXED BY sqlite_autoindex_assets_1
             CROSS JOIN bundles b ON b.bundle_uuid = a.bundle_uuid";
        match driver {
            Driver::Asset | Driver::Tag | Driver::Everything => BY_ASSET,
            Driver::TagPoisoned => {
                "assets a INDEXED BY assets_tag_poisoned
                 CROSS JOIN bundles b ON b.bundle_uuid = a.bundle_uuid"
            }
            Driver::TagPoisonedTypes => {
                "assets a INDEXED BY assets_tag_poisoned_by_type
                 CROSS JOIN bundles b ON b.bundle_uuid = a.bundle_uuid"
            }
            Driver::Bundle => {
                "assets a INDEXED BY assets_by_bundle
                 CROSS JOIN bundles b ON b.bundle_uuid = a.bundle_uuid"
            }
            Driver::LocalId => {
                "assets a INDEXED BY assets_by_local_id
                 CROSS JOIN bundles b ON b.bundle_uuid = a.bundle_uuid"
            }
            Driver::AuthoredType | Driver::AuthoredTypes => {
                "assets a INDEXED BY assets_by_type
                 CROSS JOIN bundles b ON b.bundle_uuid = a.bundle_uuid"
            }
            Driver::TerminalType => {
                "assets a INDEXED BY assets_by_terminal_type
                 CROSS JOIN bundles b ON b.bundle_uuid = a.bundle_uuid"
            }
            Driver::AuthoringOnly => {
                "assets a INDEXED BY assets_authoring
                 CROSS JOIN bundles b ON b.bundle_uuid = a.bundle_uuid"
            }
            Driver::BundlePath | Driver::PathPrefix => {
                "bundles b INDEXED BY bundles_by_path
                 CROSS JOIN assets a INDEXED BY assets_by_bundle ON a.bundle_uuid = b.bundle_uuid"
            }
            Driver::BundleName => {
                "bundles b INDEXED BY bundles_by_name
                 CROSS JOIN assets a INDEXED BY assets_by_bundle ON a.bundle_uuid = b.bundle_uuid"
            }
        }
    }

    /// `AND`-prefixed conditions over [`Self::sql_from`]'s join, pushing
    /// their parameters (numbered from `params.len() + 1`). With
    /// `tag_poisoned`, only rows whose tag index is poisoned.
    fn sql_conditions(
        &self,
        driver: Driver,
        tag_poisoned: bool,
        params: &mut Vec<rusqlite::types::Value>,
    ) -> String {
        use rusqlite::types::Value;
        /// Bind `value` and return its parameter number.
        fn bind(params: &mut Vec<Value>, value: Value) -> usize {
            params.push(value);
            params.len()
        }
        let mut conditions = Vec::new();
        if let Some(asset) = self.asset {
            let n = bind(params, Value::Blob(asset.0.to_vec()));
            conditions.push(format!("a.asset_uuid = ?{n}"));
        }
        if let Some(bundle) = self.bundle {
            let n = bind(params, Value::Blob(bundle.0.to_vec()));
            conditions.push(format!("a.bundle_uuid = ?{n}"));
        }
        if let Some(path) = &self.bundle_path {
            let n = bind(params, Value::Text(path.clone()));
            conditions.push(format!("b.path = ?{n}"));
        }
        if let Some(name) = &self.bundle_name {
            let n = bind(params, Value::Text(name.clone()));
            conditions.push(format!("b.name = ?{n}"));
        }
        if let Some(local_id) = &self.local_id {
            let n = bind(params, Value::Text(local_id.clone()));
            conditions.push(format!("a.local_id = ?{n}"));
        }
        // The authored types the rows must have, as a condition on a
        // `type_uuid` column.
        let mut types_condition = Vec::new();
        if let Some(type_uuid) = self.authored_type {
            let n = bind(params, Value::Blob(type_uuid.0.to_vec()));
            types_condition.push(format!("= ?{n}"));
        }
        if let Some(types) = &self.authored_type_in {
            let list = types
                .iter()
                .map(|type_uuid| format!("?{}", bind(params, Value::Blob(type_uuid.0.to_vec()))))
                .collect::<Vec<_>>()
                .join(", ");
            types_condition.push(format!("IN ({list})"));
        }
        for condition in &types_condition {
            conditions.push(format!("a.type_uuid {condition}"));
        }
        if let Some(type_uuid) = self.terminal_type {
            let n = bind(params, Value::Blob(type_uuid.0.to_vec()));
            conditions.push(format!("a.terminal_type = ?{n}"));
        }
        // The longest prefix implies the others.
        if let Ok(Some(prefix)) = self.path_prefix() {
            let n = bind(params, Value::Text(prefix.to_owned()));
            conditions.push(crate::files::starts_with_sql("b.path", n));
        }
        if let Some((tag, value)) = &self.tag {
            let n = bind(params, Value::Text(tag.clone()));
            let value = match value {
                Some(value) => format!(" AND t.value = ?{}", bind(params, Value::Text(value.clone()))),
                None => String::new(),
            };
            // Driving, the tag's rows are the candidates; otherwise each
            // candidate's tag is checked on its primary key.
            conditions.push(if driver == Driver::Tag {
                format!(
                    "a.asset_uuid IN (SELECT t.asset_uuid FROM asset_tags t
                                      WHERE t.tag = ?{n}{value})"
                )
            } else {
                format!(
                    "EXISTS (SELECT 1 FROM asset_tags t
                             WHERE t.asset_uuid = a.asset_uuid AND t.tag = ?{n}{value})"
                )
            });
        }
        // A literal, so the partial `assets_authoring` index applies.
        if let Some(authoring_only) = self.authoring_only {
            conditions.push(format!("a.authoring_only = {}", i64::from(authoring_only)));
        }
        if tag_poisoned {
            conditions.push("a.tag_poison IS NOT NULL".to_owned());
        }
        conditions
            .iter()
            .map(|condition| format!(" AND {condition}"))
            .collect()
    }

    /// The statement selecting this filter's rows among `rows` (a condition
    /// on the join), and its parameters. Each row is (asset, bundle, path,
    /// authored type, whether its bundle is poisoned). Every row a poisoned
    /// bundle's skeleton holds is selected beside `rows`, so the one walk
    /// that answers the query also finds the poisons that fail it.
    pub(crate) fn rows_sql(&self, rows: &str) -> (String, Vec<rusqlite::types::Value>) {
        let driver = self.driver(false);
        let mut params = Vec::new();
        let conditions = self.sql_conditions(driver, false, &mut params);
        let sql = format!(
            "SELECT a.asset_uuid, a.bundle_uuid, b.path, a.type_uuid, b.poison IS NOT NULL
             FROM {} WHERE (b.poison IS NOT NULL OR ({rows})){conditions}
             ORDER BY a.asset_uuid",
            Self::sql_from(driver)
        );
        (sql, params)
    }

    /// The statement selecting the bundle and path of each row among `rows`
    /// this filter selects without its tag whose tag index is poisoned.
    pub(crate) fn tag_poisons_sql(&self, rows: &str) -> (String, Vec<rusqlite::types::Value>) {
        let untagged = Self {
            tag: None,
            ..self.clone()
        };
        let driver = untagged.driver(true);
        let mut params = Vec::new();
        let conditions = untagged.sql_conditions(driver, true, &mut params);
        let sql = format!(
            "SELECT a.bundle_uuid, b.path FROM {} WHERE b.poison IS NULL AND ({rows}){conditions}",
            Self::sql_from(driver)
        );
        (sql, params)
    }
}

/// The rows of a published namespace an asset query reads: every asset of
/// a bundle that is not poisoned (a poisoned bundle's skeleton rows are
/// read beside them, see [`AssetFilter::rows_sql`]).
pub(crate) const NAMESPACE_ROWS: &str = "b.poison IS NULL";

impl StoreReader {
    /// The asset rows of non-poisoned bundles that `filter` selects and
    /// whose owning bundle's path `glob` matches, with their bundle and its
    /// logical path, by asset UUID. Fails naming the poisoned bundles whose
    /// rows the query could select (DESIGN.md §13, asset queries).
    pub fn namespace_assets_matching(
        &self,
        filter: &AssetFilter,
        glob: impl Fn(&str) -> bool,
    ) -> Result<AssetAnswer, StoreError> {
        self.assets_matching(filter, NAMESPACE_ROWS, glob)
    }

    /// One asset query over the rows `rows` admits: at most two statements,
    /// each driven by the most selective index the filter names. Rows are
    /// streamed and matched against `glob` as they arrive.
    pub(crate) fn assets_matching(
        &self,
        filter: &AssetFilter,
        rows: &str,
        glob: impl Fn(&str) -> bool,
    ) -> Result<AssetAnswer, StoreError> {
        if filter.selects_nothing() {
            return Ok(Ok(Vec::new()));
        }
        let mut poisoned = BTreeSet::new();
        if filter.tag.is_some() {
            let (sql, params) = filter.tag_poisons_sql(rows);
            let mut statement = self.conn.prepare_cached(&sql)?;
            let mut found = statement.query(rusqlite::params_from_iter(params))?;
            while let Some(row) = found.next()? {
                if glob(&row.get::<_, String>(1)?) {
                    poisoned.insert(BundleUuid(blob16(row.get(0)?)));
                }
            }
        }
        let (sql, params) = filter.rows_sql(rows);
        let mut statement = self.conn.prepare_cached(&sql)?;
        let mut found = statement.query(rusqlite::params_from_iter(params))?;
        let mut matched = Vec::new();
        while let Some(row) = found.next()? {
            let path = row.get::<_, String>(2)?;
            if !glob(&path) {
                continue;
            }
            let bundle = BundleUuid(blob16(row.get(1)?));
            if row.get::<_, bool>(4)? {
                poisoned.insert(bundle);
            } else if poisoned.is_empty() {
                matched.push(MatchedAsset {
                    asset: AssetUuid(blob16(row.get(0)?)),
                    bundle,
                    path,
                    type_uuid: TypeUuid(blob16(row.get(3)?)),
                });
            }
        }
        Ok(if poisoned.is_empty() {
            Ok(matched)
        } else {
            Err(poisoned.into_iter().collect())
        })
    }
}

/// One asset a filter selected: its UUID, owning bundle, the bundle's
/// logical path and the asset's authored type.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MatchedAsset {
    pub asset: AssetUuid,
    pub bundle: BundleUuid,
    pub path: String,
    pub type_uuid: TypeUuid,
}

pub(crate) fn blob16(bytes: Vec<u8>) -> [u8; 16] {
    let mut out = [0u8; 16];
    out.copy_from_slice(&bytes);
    out
}

pub(crate) fn blob32(bytes: Vec<u8>) -> [u8; 32] {
    let mut out = [0u8; 32];
    out.copy_from_slice(&bytes);
    out
}
