//! Asset-namespace metadata (§13): `bundles`, `assets` + search tags,
//! `path_index`, `deps`, `schemas` — and the two poison shapes.
//!
//! Bundle-scoped poison (§7, §13): a file that cannot be indexed
//! publishes a poison row *only when the current malformed bytes
//! themselves yield a fully validated, complete namespace skeleton* —
//! the outer envelope parses and every asset UUID, `local_id`, type
//! UUID, and tag value extracts and validates even though the file as a
//! whole fails. The skeleton's rows then REPLACE every prior
//! `bundles`/`assets` row for the file's UUIDs (never silently
//! retained, never silently dropped): resolves against those UUIDs
//! return a stable `Failed` naming the error, and tag queries whose
//! selectors match its entries fail naming the poisoned bundle. Anything
//! less than the complete skeleton takes §7's conservative
//! **version-global** poison instead — *regardless of what prior
//! metadata exists*: a prior indexed row identifies what the OLD bytes
//! claimed, not what the malformed bytes might claim, so a poison is
//! scoped only by facts validated from the bytes being poisoned.

use distill_core::id::{AssetUuid, BundleUuid, ContentHash, LogicalHash, TypeUuid};
use rusqlite::OptionalExtension;

use crate::db::{meta_get_blob, meta_set_blob, InputTxn, Store};
use crate::error::{RetiredTypeReference, StoreError};
use crate::files::RootId;
use crate::state::VersionPoison;

/// One `bundles` row (§13): the physical key, matching `files`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BundleMeta {
    pub bundle: BundleUuid,
    pub root: RootId,
    pub path: String,
    pub format_version: u32,
    pub content_hash: ContentHash,
    /// Directory-import provenance (§8, §13): present iff this bundle
    /// was generated by a directory import — derived at scan from the
    /// `DirectoryOrigin` record riding in the bundle's `$record` entry,
    /// never from precious rows. `None` means explicit import.
    pub origin: Option<DirectoryOrigin>,
}

/// A generated bundle's directory-import provenance (§2, §8, §13): who
/// owns it and which group produced it — what orphan tracking re-derives
/// ownership from after daemon-state loss.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DirectoryOrigin {
    pub rules_bundle: BundleUuid,
    /// Stable authored UUID-style rule identity (R22/H7), never the
    /// rule's mutable position in `DirectoryImportRules.rules`.
    pub rule: DirectoryRuleId,
    /// The fold's group key as a rooted path (§8) — the root's
    /// persistent NAME (§18's named roots), never a numeric ordinal.
    pub group_root: String,
    pub group_path: String,
}

/// Stable identity of one authored directory-import rule. Kept local to
/// the store surface because it is provenance metadata, not an asset or
/// bundle identity domain.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct DirectoryRuleId(pub [u8; 16]);

impl std::fmt::Display for DirectoryRuleId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        for (i, byte) in self.0.iter().enumerate() {
            if matches!(i, 4 | 6 | 8 | 10) {
                f.write_str("-")?;
            }
            write!(f, "{byte:02x}")?;
        }
        Ok(())
    }
}

/// One `assets` row (§13) plus its search tags.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AssetRecord {
    pub asset: AssetUuid,
    pub bundle: BundleUuid,
    pub local_id: String,
    pub type_uuid: TypeUuid,
    pub logical_hash: LogicalHash,
    pub authoring_only: bool,
    pub tags: Vec<String>,
}

/// The fully validated, complete namespace skeleton a malformed file's
/// CURRENT bytes yielded (§7, §13) — the precondition for bundle-scoped
/// poison. Every field is a fact validated from the bytes being
/// poisoned; the caller that could not extract all of them publishes
/// the version-global poison instead.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NamespaceSkeleton {
    pub bundle: BundleUuid,
    pub root: RootId,
    pub path: String,
    pub format_version: u32,
    /// Hash of the malformed bytes themselves — what "fixing the file
    /// heals on the next version" compares against.
    pub content_hash: ContentHash,
    pub entries: Vec<SkeletonEntry>,
}

/// One asset entry of a [`NamespaceSkeleton`]: UUID, local id, type,
/// and tags — validated despite the whole-file failure. There is
/// deliberately no logical hash: the schema closure may be exactly what
/// failed.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SkeletonEntry {
    pub asset: AssetUuid,
    pub local_id: String,
    pub type_uuid: TypeUuid,
    pub authoring_only: bool,
    pub tags: Vec<String>,
}

/// What `entry()` returns (§13's `EntryMeta`).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EntryMeta {
    pub asset: AssetUuid,
    pub bundle: BundleUuid,
    pub local_id: String,
    pub type_uuid: TypeUuid,
    pub logical_hash: LogicalHash,
    pub authoring_only: bool,
    pub tags: Vec<String>,
}

/// Recorded dependency kinds (§10, §13's `deps`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DepKind {
    Content,
    Resolution,
    Query,
}

impl DepKind {
    fn to_i64(self) -> i64 {
        match self {
            DepKind::Content => 0,
            DepKind::Resolution => 1,
            DepKind::Query => 2,
        }
    }
}

impl InputTxn<'_> {
    /// Publish (or republish) a bundle row. Clears any poison: fixing
    /// the file heals on the next version (§13). Healing republishes
    /// wholesale — a previously poisoned row's asset rows are the
    /// malformed file's skeleton, and their meaning dies with the
    /// poison, so they are dropped here before the caller re-indexes
    /// the fixed file's entries.
    pub fn upsert_bundle(&mut self, meta: &BundleMeta) -> Result<(), StoreError> {
        let was_poisoned: Option<Option<String>> = self
            .txn
            .query_row(
                "SELECT poison FROM bundles WHERE bundle_uuid = ?1",
                [meta.bundle.0.as_slice()],
                |r| r.get(0),
            )
            .optional()?;
        if matches!(was_poisoned, Some(Some(_))) {
            self.remove_owned_asset_rows(meta.bundle)?;
        }
        self.txn.execute(
            "INSERT INTO bundles(bundle_uuid, root_id, path, format_version, content_hash, poison,
                                 origin_rules_bundle, origin_rule, origin_group_root, origin_group_path)
             VALUES (?1, ?2, ?3, ?4, ?5, NULL, ?6, ?7, ?8, ?9)
             ON CONFLICT(bundle_uuid) DO UPDATE SET
               root_id = excluded.root_id, path = excluded.path,
               format_version = excluded.format_version,
               content_hash = excluded.content_hash, poison = NULL,
               origin_rules_bundle = excluded.origin_rules_bundle,
               origin_rule = excluded.origin_rule,
               origin_group_root = excluded.origin_group_root,
               origin_group_path = excluded.origin_group_path",
            rusqlite::params![
                meta.bundle.0.as_slice(),
                meta.root.0,
                meta.path,
                meta.format_version,
                meta.content_hash.0.as_slice(),
                meta.origin.as_ref().map(|o| o.rules_bundle.0.as_slice().to_vec()),
                meta.origin.as_ref().map(|o| o.rule.0.as_slice()),
                meta.origin.as_ref().map(|o| o.group_root.as_str()),
                meta.origin.as_ref().map(|o| o.group_path.as_str()),
            ],
        )?;
        Ok(())
    }

    /// Remove a bundle and everything it owns (assets, tags, its assets'
    /// path-index rows).
    pub fn remove_bundle(&mut self, bundle: BundleUuid) -> Result<bool, StoreError> {
        self.remove_owned_asset_rows(bundle)?;
        let n = self.txn.execute(
            "DELETE FROM bundles WHERE bundle_uuid = ?1",
            [bundle.0.as_slice()],
        )?;
        Ok(n > 0)
    }

    /// Drop every asset row a bundle owns, with tags and path-index rows.
    fn remove_owned_asset_rows(&mut self, bundle: BundleUuid) -> Result<(), StoreError> {
        self.txn.execute(
            "DELETE FROM path_index WHERE asset_uuid IN
               (SELECT asset_uuid FROM assets WHERE bundle_uuid = ?1)",
            [bundle.0.as_slice()],
        )?;
        self.txn.execute(
            "DELETE FROM asset_tags WHERE asset_uuid IN
               (SELECT asset_uuid FROM assets WHERE bundle_uuid = ?1)",
            [bundle.0.as_slice()],
        )?;
        self.txn.execute(
            "DELETE FROM assets WHERE bundle_uuid = ?1",
            [bundle.0.as_slice()],
        )?;
        Ok(())
    }

    /// Publish (or republish) an asset row; tags replace wholesale.
    pub fn upsert_asset(&mut self, rec: &AssetRecord) -> Result<(), StoreError> {
        self.ensure_type_reference_active(rec.type_uuid, RetiredTypeReference::Asset(rec.asset))?;
        self.txn.execute(
            "INSERT INTO assets(
                 asset_uuid, bundle_uuid, local_id, type_uuid, logical_hash, authoring_only
             ) VALUES (?1, ?2, ?3, ?4, ?5, ?6)
             ON CONFLICT(asset_uuid) DO UPDATE SET
               bundle_uuid = excluded.bundle_uuid, local_id = excluded.local_id,
               type_uuid = excluded.type_uuid, logical_hash = excluded.logical_hash,
               authoring_only = excluded.authoring_only",
            rusqlite::params![
                rec.asset.0.as_slice(),
                rec.bundle.0.as_slice(),
                rec.local_id,
                rec.type_uuid.0.as_slice(),
                rec.logical_hash.0.as_slice(),
                i64::from(rec.authoring_only),
            ],
        )?;
        self.txn.execute(
            "DELETE FROM asset_tags WHERE asset_uuid = ?1",
            [rec.asset.0.as_slice()],
        )?;
        for tag in &rec.tags {
            self.txn.execute(
                "INSERT OR IGNORE INTO asset_tags(asset_uuid, tag) VALUES (?1, ?2)",
                rusqlite::params![rec.asset.0.as_slice(), tag],
            )?;
        }
        Ok(())
    }

    /// Record a path/primary resolution entry (§13's `path_index`).
    pub fn set_path_entry(
        &mut self,
        path: &str,
        root: RootId,
        asset: AssetUuid,
    ) -> Result<(), StoreError> {
        let role: Option<i64> = self
            .txn
            .query_row(
                "SELECT authoring_only FROM assets WHERE asset_uuid = ?1",
                [asset.0.as_slice()],
                |row| row.get(0),
            )
            .optional()?;
        if role == Some(1) {
            return Err(StoreError::RoleIneligible { asset });
        }
        self.txn.execute(
            "INSERT INTO path_index(path, root_id, asset_uuid) VALUES (?1, ?2, ?3)
             ON CONFLICT(path, root_id) DO UPDATE SET asset_uuid = excluded.asset_uuid",
            rusqlite::params![path, root.0, asset.0.as_slice()],
        )?;
        Ok(())
    }

    /// Remove a path/primary resolution entry.
    pub fn remove_path_entry(&mut self, path: &str, root: RootId) -> Result<bool, StoreError> {
        let n = self.txn.execute(
            "DELETE FROM path_index WHERE path = ?1 AND root_id = ?2",
            rusqlite::params![path, root.0],
        )?;
        Ok(n > 0)
    }

    /// Record one dependency edge (§13's `deps`).
    pub fn record_dep(
        &mut self,
        src: AssetUuid,
        kind: DepKind,
        target: &str,
    ) -> Result<(), StoreError> {
        self.txn.execute(
            "INSERT OR IGNORE INTO deps(src_uuid, kind, target) VALUES (?1, ?2, ?3)",
            rusqlite::params![src.0.as_slice(), kind.to_i64(), target],
        )?;
        Ok(())
    }

    /// Drop every recorded dependency of `src` (re-recording is
    /// wholesale).
    pub fn clear_deps(&mut self, src: AssetUuid) -> Result<(), StoreError> {
        self.txn
            .execute("DELETE FROM deps WHERE src_uuid = ?1", [src.0.as_slice()])?;
        Ok(())
    }

    /// Cache a schema by logical hash (§13's `schemas` — rebuilt from
    /// bundle snapshots, never precious).
    pub fn put_schema(&mut self, hash: LogicalHash, json: &str) -> Result<(), StoreError> {
        self.txn.execute(
            "INSERT INTO schemas(logical_hash, schema_json) VALUES (?1, ?2)
             ON CONFLICT(logical_hash) DO UPDATE SET schema_json = excluded.schema_json",
            rusqlite::params![hash.0.as_slice(), json],
        )?;
        Ok(())
    }

    /// Publish the bundle-scoped poison row (§7, §13). Scope is decided
    /// by the caller-supplied **validated skeleton** parsed from the
    /// CURRENT malformed bytes — never by prior metadata: the skeleton's
    /// rows replace every prior `bundles`/`assets` row for the file's
    /// UUIDs, so resolves against them (old and newly introduced alike)
    /// return the stable `Failed`, and queries whose selectors match the
    /// skeleton's entries fail naming this bundle. A caller that could
    /// not extract the complete skeleton publishes
    /// [`InputTxn::set_version_poison`] instead — regardless of what
    /// prior rows exist.
    pub fn poison_bundle(
        &mut self,
        skeleton: &NamespaceSkeleton,
        error: &str,
    ) -> Result<(), StoreError> {
        // Replace, never retain: the prior rows describe the old bytes.
        self.remove_owned_asset_rows(skeleton.bundle)?;
        self.txn.execute(
            "INSERT INTO bundles(bundle_uuid, root_id, path, format_version, content_hash, poison)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6)
             ON CONFLICT(bundle_uuid) DO UPDATE SET
               root_id = excluded.root_id, path = excluded.path,
               format_version = excluded.format_version,
               content_hash = excluded.content_hash, poison = excluded.poison",
            rusqlite::params![
                skeleton.bundle.0.as_slice(),
                skeleton.root.0,
                skeleton.path,
                skeleton.format_version,
                skeleton.content_hash.0.as_slice(),
                error,
            ],
        )?;
        for entry in &skeleton.entries {
            // Plain INSERT: a skeleton UUID colliding with another
            // bundle's row is a cross-file identity collision — §7 keeps
            // the version-global poison for those, and the constraint
            // failure surfaces rather than silently reassigning the row.
            self.txn.execute(
                "INSERT INTO assets(
                     asset_uuid, bundle_uuid, local_id, type_uuid, logical_hash, authoring_only
                 ) VALUES (?1, ?2, ?3, ?4, NULL, ?5)",
                rusqlite::params![
                    entry.asset.0.as_slice(),
                    skeleton.bundle.0.as_slice(),
                    entry.local_id,
                    entry.type_uuid.0.as_slice(),
                    i64::from(entry.authoring_only),
                ],
            )?;
            for tag in &entry.tags {
                self.txn.execute(
                    "INSERT OR IGNORE INTO asset_tags(asset_uuid, tag) VALUES (?1, ?2)",
                    rusqlite::params![entry.asset.0.as_slice(), tag],
                )?;
            }
        }
        Ok(())
    }

    /// Set or clear §7/§13's version-global poison.
    pub fn set_version_poison(&mut self, poison: Option<&VersionPoison>) -> Result<(), StoreError> {
        match poison {
            Some(poison) => meta_set_blob(
                &self.txn,
                "version_poison",
                &poison
                    .persisted_bytes()
                    .map_err(StoreError::InvalidVersionPoison)?,
            ),
            None => {
                self.txn
                    .execute("DELETE FROM store_meta WHERE key = 'version_poison'", [])?;
                Ok(())
            }
        }
    }

    /// Scanner publication boundary for simultaneous version-global defects.
    /// The full canonical set is returned for doctor diagnostics; only its
    /// deterministic first row becomes namespace authority.
    pub fn set_version_poisons(
        &mut self,
        poisons: impl IntoIterator<Item = VersionPoison>,
    ) -> Result<Vec<VersionPoison>, StoreError> {
        let canonical =
            VersionPoison::canonical_set(poisons).map_err(StoreError::InvalidVersionPoison)?;
        self.set_version_poison(canonical.first())?;
        Ok(canonical)
    }
}

impl Store {
    fn check_version_poison(&self) -> Result<(), StoreError> {
        if let Some(poison) = self.version_poison()? {
            return Err(StoreError::Poisoned {
                error: poison.message,
            });
        }
        Ok(())
    }

    /// The current version's global poison, if any (§13's
    /// `MetadataSnapshot::poisoned`).
    pub fn version_poison(&self) -> Result<Option<VersionPoison>, StoreError> {
        meta_get_blob(&self.conn, "version_poison")?
            .map(|bytes| {
                VersionPoison::from_persisted_bytes(&bytes)
                    .map_err(StoreError::InvalidVersionPoison)
            })
            .transpose()
    }

    /// One bundle's physical row. Poisoned bundles still *have* a row —
    /// the poison is part of it.
    pub fn bundle(&self, bundle: BundleUuid) -> Result<Option<BundleMeta>, StoreError> {
        Ok(self
            .conn
            .query_row(
                "SELECT root_id, path, format_version, content_hash,
                        origin_rules_bundle, origin_rule, origin_group_root, origin_group_path
                 FROM bundles WHERE bundle_uuid = ?1",
                [bundle.0.as_slice()],
                |r| {
                    let origin = match (
                        r.get::<_, Option<Vec<u8>>>(4)?,
                        r.get::<_, Option<Vec<u8>>>(5)?,
                        r.get::<_, Option<String>>(6)?,
                        r.get::<_, Option<String>>(7)?,
                    ) {
                        (Some(rules), Some(rule), Some(group_root), Some(group_path)) => {
                            Some(DirectoryOrigin {
                                rules_bundle: BundleUuid(blob16(rules)),
                                rule: DirectoryRuleId(blob16(rule)),
                                group_root,
                                group_path,
                            })
                        }
                        _ => None,
                    };
                    Ok(BundleMeta {
                        bundle,
                        root: RootId(r.get(0)?),
                        path: r.get(1)?,
                        format_version: r.get(2)?,
                        content_hash: ContentHash(blob32(r.get::<_, Vec<u8>>(3)?)),
                        origin,
                    })
                },
            )
            .optional()?)
    }

    /// Complete deterministic bundle projection used to synthesize deletes
    /// during startup reconciliation and to hydrate the RPC metadata index.
    pub fn all_bundles(&self) -> Result<Vec<BundleMeta>, StoreError> {
        let mut statement = self.conn.prepare(
            "SELECT bundle_uuid, root_id, path, format_version, content_hash,
                    origin_rules_bundle, origin_rule, origin_group_root, origin_group_path
             FROM bundles ORDER BY bundle_uuid",
        )?;
        let rows = statement.query_map([], |row| {
            let origin = match (
                row.get::<_, Option<Vec<u8>>>(5)?,
                row.get::<_, Option<Vec<u8>>>(6)?,
                row.get::<_, Option<String>>(7)?,
                row.get::<_, Option<String>>(8)?,
            ) {
                (Some(rules), Some(rule), Some(group_root), Some(group_path)) => {
                    Some(DirectoryOrigin {
                        rules_bundle: BundleUuid(blob16(rules)),
                        rule: DirectoryRuleId(blob16(rule)),
                        group_root,
                        group_path,
                    })
                }
                _ => None,
            };
            Ok(BundleMeta {
                bundle: BundleUuid(blob16(row.get(0)?)),
                root: RootId(row.get(1)?),
                path: row.get(2)?,
                format_version: row.get(3)?,
                content_hash: ContentHash(blob32(row.get(4)?)),
                origin,
            })
        })?;
        rows.collect::<Result<Vec<_>, _>>()
            .map_err(StoreError::from)
    }

    /// Complete deterministic entry projection for one bundle. Poisoned
    /// skeleton rows intentionally fail through [`Store::entry`] rather than
    /// being mistaken for ordinary authored metadata.
    pub fn entries_in_bundle(&self, bundle: BundleUuid) -> Result<Vec<EntryMeta>, StoreError> {
        let mut statement = self
            .conn
            .prepare("SELECT asset_uuid FROM assets WHERE bundle_uuid = ?1 ORDER BY asset_uuid")?;
        let assets = statement
            .query_map([bundle.0.as_slice()], |row| row.get::<_, Vec<u8>>(0))?
            .collect::<Result<Vec<_>, _>>()?;
        let mut entries = Vec::with_capacity(assets.len());
        for asset in assets {
            if let Some(entry) = self.entry(AssetUuid(blob16(asset)))? {
                entries.push(entry);
            }
        }
        Ok(entries)
    }

    /// Complete path-index projection grouped by normalized logical path.
    /// Multiple roots remain multiple candidates; no root is selected here.
    pub fn all_path_entries(&self) -> Result<Vec<(String, RootId, AssetUuid)>, StoreError> {
        let mut statement = self
            .conn
            .prepare("SELECT path, root_id, asset_uuid FROM path_index ORDER BY path, root_id")?;
        let rows = statement.query_map([], |row| {
            Ok((
                row.get(0)?,
                RootId(row.get(1)?),
                AssetUuid(blob16(row.get(2)?)),
            ))
        })?;
        rows.collect::<Result<Vec<_>, _>>()
            .map_err(StoreError::from)
    }

    /// Raw deterministic asset identity set, including poisoned skeleton rows.
    /// Startup reconciliation uses it only to remove identities absent from a
    /// healed full scan; it does not expose skeleton metadata.
    pub fn all_asset_ids(&self) -> Result<Vec<AssetUuid>, StoreError> {
        let mut statement = self
            .conn
            .prepare("SELECT asset_uuid FROM assets ORDER BY asset_uuid")?;
        let rows = statement.query_map([], |row| row.get::<_, Vec<u8>>(0))?;
        rows.map(|row| row.map(|bytes| AssetUuid(blob16(bytes))))
            .collect::<Result<Vec<_>, _>>()
            .map_err(StoreError::from)
    }

    /// Every generated bundle a rules bundle owns (§2, §8): the
    /// scan-derived ownership index orphan tracking re-derives after
    /// daemon-state loss — never precious.
    pub fn bundles_owned_by(&self, rules: BundleUuid) -> Result<Vec<BundleUuid>, StoreError> {
        let mut stmt = self.conn.prepare(
            "SELECT bundle_uuid FROM bundles WHERE origin_rules_bundle = ?1 ORDER BY bundle_uuid",
        )?;
        let rows = stmt.query_map([rules.0.as_slice()], |r| r.get::<_, Vec<u8>>(0))?;
        let mut out = Vec::new();
        for row in rows {
            out.push(BundleUuid(blob16(row?)));
        }
        Ok(out)
    }

    fn bundle_poison(&self, bundle: &[u8]) -> Result<Option<String>, StoreError> {
        Ok(self
            .conn
            .query_row(
                "SELECT poison FROM bundles WHERE bundle_uuid = ?1",
                [bundle],
                |r| r.get::<_, Option<String>>(0),
            )
            .optional()?
            .flatten())
    }

    /// §13 `MetadataSnapshot::entry` semantics: `Ok(None)` is a
    /// recordable miss; a poisoned version or a poisoned owning bundle is
    /// `Err`, never last-good metadata.
    pub fn entry(&self, asset: AssetUuid) -> Result<Option<EntryMeta>, StoreError> {
        self.check_version_poison()?;
        let row = self
            .conn
            .query_row(
                "SELECT bundle_uuid, local_id, type_uuid, logical_hash, authoring_only FROM assets
                 WHERE asset_uuid = ?1",
                [asset.0.as_slice()],
                |r| {
                    Ok((
                        r.get::<_, Vec<u8>>(0)?,
                        r.get::<_, String>(1)?,
                        r.get::<_, Vec<u8>>(2)?,
                        // NULL only on a skeleton row (§7), whose owning
                        // bundle is poisoned — the poison gate below
                        // fires before this is ever consumed.
                        r.get::<_, Option<Vec<u8>>>(3)?,
                        r.get::<_, i64>(4)? != 0,
                    ))
                },
            )
            .optional()?;
        let Some((bundle_bytes, local_id, type_bytes, hash_bytes, authoring_only)) = row else {
            return Ok(None);
        };
        if let Some(error) = self.bundle_poison(&bundle_bytes)? {
            return Err(StoreError::BundlePoisoned {
                bundle: BundleUuid(blob16(bundle_bytes)),
                error,
            });
        }
        // Not poisoned ⇒ never a skeleton row: the hash is present by
        // the healing invariant (upsert_bundle drops skeleton rows
        // whenever a poison clears). A NULL here is store corruption and
        // surfaces as a typed column error, never a panic.
        let hash_bytes = hash_bytes.ok_or_else(|| {
            StoreError::Sqlite(rusqlite::Error::InvalidColumnType(
                3,
                "logical_hash".to_owned(),
                rusqlite::types::Type::Null,
            ))
        })?;
        let mut tags: Vec<String> = {
            let mut stmt = self
                .conn
                .prepare("SELECT tag FROM asset_tags WHERE asset_uuid = ?1")?;
            let rows = stmt.query_map([asset.0.as_slice()], |r| r.get(0))?;
            rows.collect::<Result<_, _>>()?
        };
        tags.sort();
        Ok(Some(EntryMeta {
            asset,
            bundle: BundleUuid(blob16(bundle_bytes)),
            local_id,
            type_uuid: TypeUuid(blob16(type_bytes)),
            logical_hash: LogicalHash(blob32(hash_bytes)),
            authoring_only,
            tags,
        }))
    }

    /// Runtime direct-UUID lookup. Authoring/control rows remain visible to
    /// `entry()` for tooling metadata, but can never enter a runtime closure.
    pub fn runtime_entry(&self, asset: AssetUuid) -> Result<Option<EntryMeta>, StoreError> {
        let entry = self.entry(asset)?;
        if entry.as_ref().is_some_and(|entry| entry.authoring_only) {
            return Err(StoreError::RoleIneligible { asset });
        }
        Ok(entry)
    }

    /// §13 `MetadataSnapshot::resolve_path` semantics: `Ok(None)` is a
    /// recordable miss; a path resolvable in more than one asset root is
    /// `Err` (§18), never a tiebreak; version poison is `Err`.
    pub fn resolve_path(&self, path: &str) -> Result<Option<AssetUuid>, StoreError> {
        self.check_version_poison()?;
        // A poisoned bundle's own path fails naming it (§13): the poison
        // row replaced the file's asset rows, and a Missing here would
        // silently change query semantics.
        let poisoned_at_path: Option<(Vec<u8>, String)> = self
            .conn
            .query_row(
                "SELECT bundle_uuid, poison FROM bundles
                 WHERE path = ?1 AND poison IS NOT NULL LIMIT 1",
                [path],
                |r| Ok((r.get(0)?, r.get(1)?)),
            )
            .optional()?;
        if let Some((bundle_bytes, error)) = poisoned_at_path {
            return Err(StoreError::BundlePoisoned {
                bundle: BundleUuid(blob16(bundle_bytes)),
                error,
            });
        }
        let mut stmt = self.conn.prepare(
            "SELECT p.root_id, p.asset_uuid, r.name FROM path_index p
             LEFT JOIN roots r ON r.root_id = p.root_id
             WHERE p.path = ?1 ORDER BY p.root_id",
        )?;
        let rows: Vec<(i64, Vec<u8>, Option<String>)> = stmt
            .query_map([path], |r| Ok((r.get(0)?, r.get(1)?, r.get(2)?)))?
            .collect::<Result<_, _>>()?;
        match rows.len() {
            0 => Ok(None),
            1 => {
                let asset = AssetUuid(blob16(rows.into_iter().next().unwrap().1));
                // A resolution reaching a poisoned bundle is the stable
                // Failed, not a silent success (§13).
                let owner: Option<(Vec<u8>, Option<String>, bool)> = self
                    .conn
                    .query_row(
                        "SELECT b.bundle_uuid, b.poison, a.authoring_only FROM assets a
                         JOIN bundles b ON b.bundle_uuid = a.bundle_uuid
                         WHERE a.asset_uuid = ?1",
                        [asset.0.as_slice()],
                        |r| Ok((r.get(0)?, r.get(1)?, r.get::<_, i64>(2)? != 0)),
                    )
                    .optional()?;
                if let Some((bundle_bytes, poison, authoring_only)) = owner {
                    if let Some(error) = poison {
                        return Err(StoreError::BundlePoisoned {
                            bundle: BundleUuid(blob16(bundle_bytes)),
                            error,
                        });
                    }
                    if authoring_only {
                        return Err(StoreError::RoleIneligible { asset });
                    }
                }
                Ok(Some(asset))
            }
            _ => Err(StoreError::AmbiguousPath {
                path: path.to_owned(),
                roots: rows
                    .into_iter()
                    .map(|(id, _, name)| name.unwrap_or_else(|| format!("root#{id}")))
                    .collect(),
            }),
        }
    }

    /// Tag lookup over the search tags (§13's `assets` row). A selector
    /// matching any poisoned bundle's entries fails naming that bundle —
    /// the same shape as §10's tag poisoning.
    pub fn assets_by_tag(&self, tag: &str) -> Result<Vec<AssetUuid>, StoreError> {
        self.check_version_poison()?;
        let mut stmt = self.conn.prepare(
            "SELECT a.asset_uuid, b.bundle_uuid, b.poison FROM asset_tags t
             JOIN assets a ON a.asset_uuid = t.asset_uuid
             JOIN bundles b ON b.bundle_uuid = a.bundle_uuid
             WHERE t.tag = ?1 AND a.authoring_only = 0 ORDER BY a.asset_uuid",
        )?;
        let rows: Vec<(Vec<u8>, Vec<u8>, Option<String>)> = stmt
            .query_map([tag], |r| Ok((r.get(0)?, r.get(1)?, r.get(2)?)))?
            .collect::<Result<_, _>>()?;
        let mut out = Vec::with_capacity(rows.len());
        for (asset_bytes, bundle_bytes, poison) in rows {
            if let Some(error) = poison {
                return Err(StoreError::BundlePoisoned {
                    bundle: BundleUuid(blob16(bundle_bytes)),
                    error,
                });
            }
            out.push(AssetUuid(blob16(asset_bytes)));
        }
        Ok(out)
    }

    /// Explicit tooling-only tag lookup. This surface cannot be used as a
    /// processor-input, runtime-reference, or pack-root selector.
    pub fn authoring_assets_by_tag(&self, tag: &str) -> Result<Vec<AssetUuid>, StoreError> {
        self.check_version_poison()?;
        let mut stmt = self.conn.prepare(
            "SELECT a.asset_uuid, b.bundle_uuid, b.poison FROM asset_tags t
             JOIN assets a ON a.asset_uuid = t.asset_uuid
             JOIN bundles b ON b.bundle_uuid = a.bundle_uuid
             WHERE t.tag = ?1 AND a.authoring_only = 1 ORDER BY a.asset_uuid",
        )?;
        let rows: Vec<(Vec<u8>, Vec<u8>, Option<String>)> = stmt
            .query_map([tag], |row| Ok((row.get(0)?, row.get(1)?, row.get(2)?)))?
            .collect::<Result<_, _>>()?;
        let mut out = Vec::with_capacity(rows.len());
        for (asset_bytes, bundle_bytes, poison) in rows {
            if let Some(error) = poison {
                return Err(StoreError::BundlePoisoned {
                    bundle: BundleUuid(blob16(bundle_bytes)),
                    error,
                });
            }
            out.push(AssetUuid(blob16(asset_bytes)));
        }
        Ok(out)
    }

    /// Reverse dependency lookup by selector (§13's `deps` indexes).
    pub fn deps_on(&self, kind: DepKind, target: &str) -> Result<Vec<AssetUuid>, StoreError> {
        let mut stmt = self
            .conn
            .prepare("SELECT src_uuid FROM deps WHERE kind = ?1 AND target = ?2")?;
        let rows = stmt.query_map(rusqlite::params![kind.to_i64(), target], |r| {
            r.get::<_, Vec<u8>>(0)
        })?;
        let mut out = Vec::new();
        for row in rows {
            out.push(AssetUuid(blob16(row?)));
        }
        Ok(out)
    }

    /// Cached schema JSON by logical hash.
    pub fn schema(&self, hash: LogicalHash) -> Result<Option<String>, StoreError> {
        Ok(self
            .conn
            .query_row(
                "SELECT schema_json FROM schemas WHERE logical_hash = ?1",
                [hash.0.as_slice()],
                |r| r.get(0),
            )
            .optional()?)
    }
}

pub(crate) fn blob16(bytes: Vec<u8>) -> [u8; 16] {
    let mut out = [0u8; 16];
    out.copy_from_slice(&bytes);
    out
}

pub(crate) fn blob32(bytes: Vec<u8>) -> [u8; 32] {
    let mut out = [0u8; 32];
    out.copy_from_slice(&bytes);
    out
}
