//! Asset-namespace metadata (§13): `bundles`, `assets` + search tags,
//! `path_index`, `deps`, `schemas` — and bundle poison versus namespace errors.
//!
//! Bundle-scoped poison (§7, §13): a file that cannot be indexed
//! publishes a poison row *only when the current malformed bytes
//! themselves yield a fully validated, complete namespace skeleton* —
//! the outer envelope parses and every asset UUID, `local_id`, type
//! UUID, and tag value extracts and validates even though the file as a
//! whole fails. The skeleton's rows then REPLACE every prior
//! `bundles`/`assets` row for the file's UUIDs (never silently
//! retained, never silently dropped): resolves against those UUIDs
//! return a stable `Failed` naming the error, and tag queries whose
//! selectors match its entries fail naming the poisoned bundle. Anything
//! less than the complete skeleton takes §7's conservative
//! **namespace error** instead — *regardless of what prior
//! metadata exists*: a prior indexed row identifies what the OLD bytes
//! claimed, not what the malformed bytes might claim, so a poison is
//! scoped only by facts validated from the bytes being poisoned.

use std::collections::{BTreeMap, BTreeSet};

use distill_core::id::{AssetUuid, BundleUuid, ContentHash, LogicalHash, TypeUuid};
use rusqlite::OptionalExtension;

use crate::db::{InputTxn, Store, StoreReader};
use crate::error::StoreError;
use crate::files::RootId;
use crate::state::InputVersion;

/// One `bundles` row (§13): the physical key, matching `files`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BundleMeta {
    pub bundle: BundleUuid,
    pub root: RootId,
    pub path: String,
    pub format_version: u32,
    pub content_hash: ContentHash,
    /// Directory-import provenance (§8, §13): present iff this bundle
    /// was generated by a directory import — derived at scan from the
    /// `DirectoryOrigin` record riding in the bundle's `$record` entry,
    /// never from precious rows. `None` means explicit import.
    pub origin: Option<DirectoryOrigin>,
}

/// A generated bundle's directory-import provenance (§2, §8, §13): who
/// owns it and which group produced it — what orphan tracking re-derives
/// ownership from after daemon-state loss.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct DirectoryOrigin {
    pub rules_bundle: BundleUuid,
    /// Stable authored UUID-style rule identity (R22/H7), never the
    /// rule's mutable position in `DirectoryImportRules.rules`.
    pub rule: DirectoryRuleId,
    /// The fold's group key as a rooted path (§8) — the root's
    /// persistent NAME (§18's named roots), never a numeric ordinal.
    pub group_root: String,
    pub group_path: String,
}

/// Stable identity of one authored directory-import rule. Kept local to
/// the store surface because it is provenance metadata, not an asset or
/// bundle identity domain.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct DirectoryRuleId(pub [u8; 16]);

impl std::fmt::Display for DirectoryRuleId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        for (i, byte) in self.0.iter().enumerate() {
            if matches!(i, 4 | 6 | 8 | 10) {
                f.write_str("-")?;
            }
            write!(f, "{byte:02x}")?;
        }
        Ok(())
    }
}

/// One `assets` row (§13) plus its search tags.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AssetRecord {
    pub asset: AssetUuid,
    pub bundle: BundleUuid,
    pub local_id: String,
    pub type_uuid: TypeUuid,
    pub logical_hash: LogicalHash,
    pub authoring_only: bool,
    pub tags: BTreeMap<String, Option<String>>,
    /// The RPC-served authored value and terminal type, both present for
    /// an entry the RPC namespace serves (see [`crate::served`]).
    pub served: Option<ServedAuthoring>,
}

/// The served half of an asset row: what the RPC namespace answers from
/// without reading the bundle file.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ServedAuthoring {
    /// [`crate::served::encode_authored_value`] bytes.
    pub authored_value: Vec<u8>,
    pub terminal_type: TypeUuid,
}

/// The fully validated, complete namespace skeleton a malformed file's
/// CURRENT bytes yielded (§7, §13) — the precondition for bundle-scoped
/// poison. Every field is a fact validated from the bytes being
/// poisoned; the caller that could not extract all of them publishes
/// a namespace error instead.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NamespaceSkeleton {
    pub bundle: BundleUuid,
    pub root: RootId,
    pub path: String,
    pub format_version: u32,
    /// Hash of the malformed bytes themselves — what "fixing the file
    /// heals on the next version" compares against.
    pub content_hash: ContentHash,
    pub entries: Vec<SkeletonEntry>,
}

/// One asset entry of a [`NamespaceSkeleton`]: UUID, local id, type,
/// and tags — validated despite the whole-file failure. There is
/// deliberately no logical hash: the schema closure may be exactly what
/// failed.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SkeletonEntry {
    pub asset: AssetUuid,
    pub local_id: String,
    pub type_uuid: TypeUuid,
    pub authoring_only: bool,
    pub tags: BTreeMap<String, Option<String>>,
}

/// What `entry()` returns (§13's `EntryMeta`).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EntryMeta {
    pub asset: AssetUuid,
    pub bundle: BundleUuid,
    pub local_id: String,
    pub type_uuid: TypeUuid,
    pub logical_hash: LogicalHash,
    pub authoring_only: bool,
    pub tags: BTreeMap<String, Option<String>>,
}

/// Complete §10 tag-index publication for one asset. The current-schema tags
/// and every input that could change `load_current` are replaced atomically.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TagIndexUpdate {
    pub asset: AssetUuid,
    pub tags: BTreeMap<String, Option<String>>,
    pub tag_epoch: [u8; 32],
    pub planner_version: Option<u32>,
    pub dylib_hash: Option<[u8; 32]>,
    pub trace: Vec<u8>,
    pub poison: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TagIndexState {
    pub tag_epoch: [u8; 32],
    pub planner_version: Option<u32>,
    pub dylib_hash: Option<[u8; 32]>,
    pub trace: Vec<u8>,
    pub poison: Option<String>,
}

/// Recorded dependency kinds (§10, §13's `deps`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DepKind {
    Content,
    Resolution,
    Query,
}

impl DepKind {
    fn to_i64(self) -> i64 {
        match self {
            DepKind::Content => 0,
            DepKind::Resolution => 1,
            DepKind::Query => 2,
        }
    }
}

impl InputTxn<'_> {
    /// Publish (or republish) a bundle row. Clears any poison: fixing
    /// the file heals on the next version (§13). Healing republishes
    /// wholesale — a previously poisoned row's asset rows are the
    /// malformed file's skeleton, and their meaning dies with the
    /// poison, so they are dropped here before the caller re-indexes
    /// the fixed file's entries.
    pub fn upsert_bundle(&mut self, meta: &BundleMeta) -> Result<(), StoreError> {
        let was_poisoned: Option<Option<String>> = self
            .txn
            .query_row(
                "SELECT poison FROM bundles WHERE bundle_uuid = ?1",
                [meta.bundle.0.as_slice()],
                |r| r.get(0),
            )
            .optional()?;
        if matches!(was_poisoned, Some(Some(_))) {
            self.remove_owned_asset_rows(meta.bundle)?;
        }
        // The caller republishes the references of the bytes it indexes.
        self.clear_path_refs(meta.bundle)?;
        self.txn.execute(
            "INSERT INTO bundles(bundle_uuid, root_id, path, format_version, content_hash, poison,
                                 origin_rules_bundle, origin_rule, origin_group_root, origin_group_path)
             VALUES (?1, ?2, ?3, ?4, ?5, NULL, ?6, ?7, ?8, ?9)
             ON CONFLICT(bundle_uuid) DO UPDATE SET
               root_id = excluded.root_id, path = excluded.path,
               format_version = excluded.format_version,
               content_hash = excluded.content_hash, poison = NULL,
               origin_rules_bundle = excluded.origin_rules_bundle,
               origin_rule = excluded.origin_rule,
               origin_group_root = excluded.origin_group_root,
               origin_group_path = excluded.origin_group_path",
            rusqlite::params![
                meta.bundle.0.as_slice(),
                meta.root.0,
                meta.path,
                meta.format_version,
                meta.content_hash.0.as_slice(),
                meta.origin.as_ref().map(|o| o.rules_bundle.0.as_slice().to_vec()),
                meta.origin.as_ref().map(|o| o.rule.0.as_slice()),
                meta.origin.as_ref().map(|o| o.group_root.as_str()),
                meta.origin.as_ref().map(|o| o.group_path.as_str()),
            ],
        )?;
        Ok(())
    }

    /// Remove a bundle and everything it owns (assets, tags, its assets'
    /// path-index rows).
    pub fn remove_bundle(&mut self, bundle: BundleUuid) -> Result<bool, StoreError> {
        self.remove_owned_asset_rows(bundle)?;
        self.clear_path_refs(bundle)?;
        let n = self.txn.execute(
            "DELETE FROM bundles WHERE bundle_uuid = ?1",
            [bundle.0.as_slice()],
        )?;
        Ok(n > 0)
    }

    /// Record the logical path strings `bundle`'s reference fields name
    /// (§13's `bundle_path_refs`), replacing any it had. Call after
    /// [`InputTxn::upsert_bundle`], which clears them.
    pub fn set_bundle_path_refs<'a>(
        &mut self,
        bundle: BundleUuid,
        targets: impl IntoIterator<Item = &'a str>,
    ) -> Result<(), StoreError> {
        self.clear_path_refs(bundle)?;
        for target in targets {
            self.txn.execute(
                "INSERT OR IGNORE INTO bundle_path_refs(bundle_uuid, target) VALUES (?1, ?2)",
                rusqlite::params![bundle.0.as_slice(), target],
            )?;
        }
        Ok(())
    }

    fn clear_path_refs(&mut self, bundle: BundleUuid) -> Result<(), StoreError> {
        self.txn.execute(
            "DELETE FROM bundle_path_refs WHERE bundle_uuid = ?1",
            [bundle.0.as_slice()],
        )?;
        Ok(())
    }

    /// Drop every asset row a bundle owns, with tags and path-index rows.
    fn remove_owned_asset_rows(&mut self, bundle: BundleUuid) -> Result<(), StoreError> {
        self.txn.execute(
            "DELETE FROM path_index WHERE asset_uuid IN
               (SELECT asset_uuid FROM assets WHERE bundle_uuid = ?1)",
            [bundle.0.as_slice()],
        )?;
        self.txn.execute(
            "DELETE FROM asset_tags WHERE asset_uuid IN
               (SELECT asset_uuid FROM assets WHERE bundle_uuid = ?1)",
            [bundle.0.as_slice()],
        )?;
        self.txn.execute(
            "DELETE FROM asset_tag_index WHERE asset_uuid IN
               (SELECT asset_uuid FROM assets WHERE bundle_uuid = ?1)",
            [bundle.0.as_slice()],
        )?;
        self.txn.execute(
            "DELETE FROM assets WHERE bundle_uuid = ?1",
            [bundle.0.as_slice()],
        )?;
        Ok(())
    }

    /// Publish (or republish) an asset row; tags replace wholesale.
    pub fn upsert_asset(&mut self, rec: &AssetRecord) -> Result<(), StoreError> {
        self.txn.execute(
            "INSERT INTO assets(
                 asset_uuid, bundle_uuid, local_id, type_uuid, logical_hash, authoring_only,
                 authored_value, terminal_type
             ) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8)
             ON CONFLICT(asset_uuid) DO UPDATE SET
               bundle_uuid = excluded.bundle_uuid, local_id = excluded.local_id,
               type_uuid = excluded.type_uuid, logical_hash = excluded.logical_hash,
               authoring_only = excluded.authoring_only,
               authored_value = excluded.authored_value,
               terminal_type = excluded.terminal_type",
            rusqlite::params![
                rec.asset.0.as_slice(),
                rec.bundle.0.as_slice(),
                rec.local_id,
                rec.type_uuid.0.as_slice(),
                rec.logical_hash.0.as_slice(),
                i64::from(rec.authoring_only),
                rec.served.as_ref().map(|served| served.authored_value.as_slice()),
                rec.served
                    .as_ref()
                    .map(|served| served.terminal_type.0.to_vec()),
            ],
        )?;
        self.txn.execute(
            "DELETE FROM asset_tags WHERE asset_uuid = ?1",
            [rec.asset.0.as_slice()],
        )?;
        for (tag, value) in &rec.tags {
            self.txn.execute(
                "INSERT OR REPLACE INTO asset_tags(asset_uuid, tag, value) VALUES (?1, ?2, ?3)",
                rusqlite::params![rec.asset.0.as_slice(), tag, value],
            )?;
        }
        self.txn.execute(
            "DELETE FROM asset_tag_index WHERE asset_uuid = ?1",
            [rec.asset.0.as_slice()],
        )?;
        Ok(())
    }

    /// Install the conservative half of a two-phase tag publication in the
    /// same transaction as the asset identity. A crash before refinement is
    /// therefore a query failure, never an empty successful index.
    pub fn set_tag_index_pending(
        &mut self,
        asset: AssetUuid,
        tag_epoch: [u8; 32],
    ) -> Result<(), StoreError> {
        self.txn.execute(
            "INSERT INTO asset_tag_index(
                asset_uuid, tag_epoch, planner_version, dylib_hash, trace, poison
             ) VALUES (?1, ?2, NULL, NULL, X'', 'tag indexing pending')
             ON CONFLICT(asset_uuid) DO UPDATE SET
                tag_epoch = excluded.tag_epoch,
                planner_version = NULL,
                dylib_hash = NULL,
                trace = X'',
                poison = excluded.poison",
            rusqlite::params![asset.0.as_slice(), tag_epoch.as_slice()],
        )?;
        Ok(())
    }

    /// Record a path/primary resolution entry (§13's `path_index`).
    pub fn set_path_entry(
        &mut self,
        path: &str,
        root: RootId,
        asset: AssetUuid,
    ) -> Result<(), StoreError> {
        let role: Option<i64> = self
            .txn
            .query_row(
                "SELECT authoring_only FROM assets WHERE asset_uuid = ?1",
                [asset.0.as_slice()],
                |row| row.get(0),
            )
            .optional()?;
        if role == Some(1) {
            return Err(StoreError::RoleIneligible { asset });
        }
        self.txn.execute(
            "INSERT INTO path_index(path, root_id, asset_uuid) VALUES (?1, ?2, ?3)
             ON CONFLICT(path, root_id) DO UPDATE SET asset_uuid = excluded.asset_uuid",
            rusqlite::params![path, root.0, asset.0.as_slice()],
        )?;
        Ok(())
    }

    /// Remove a path/primary resolution entry.
    pub fn remove_path_entry(&mut self, path: &str, root: RootId) -> Result<bool, StoreError> {
        let n = self.txn.execute(
            "DELETE FROM path_index WHERE path = ?1 AND root_id = ?2",
            rusqlite::params![path, root.0],
        )?;
        Ok(n > 0)
    }

    /// Record one dependency edge (§13's `deps`).
    pub fn record_dep(
        &mut self,
        src: AssetUuid,
        kind: DepKind,
        target: &str,
    ) -> Result<(), StoreError> {
        self.txn.execute(
            "INSERT OR IGNORE INTO deps(src_uuid, kind, target) VALUES (?1, ?2, ?3)",
            rusqlite::params![src.0.as_slice(), kind.to_i64(), target],
        )?;
        Ok(())
    }

    /// Drop every recorded dependency of `src` (re-recording is
    /// wholesale).
    pub fn clear_deps(&mut self, src: AssetUuid) -> Result<(), StoreError> {
        self.txn
            .execute("DELETE FROM deps WHERE src_uuid = ?1", [src.0.as_slice()])?;
        Ok(())
    }

    /// Cache a schema by logical hash (§13's `schemas` — rebuilt from
    /// bundle snapshots, never precious).
    pub fn put_schema(&mut self, hash: LogicalHash, json: &str) -> Result<(), StoreError> {
        self.txn.execute(
            "INSERT INTO schemas(logical_hash, schema_json) VALUES (?1, ?2)
             ON CONFLICT(logical_hash) DO UPDATE SET schema_json = excluded.schema_json",
            rusqlite::params![hash.0.as_slice(), json],
        )?;
        Ok(())
    }

    /// Publish the bundle-scoped poison row (§7, §13). Scope is decided
    /// by the caller-supplied **validated skeleton** parsed from the
    /// CURRENT malformed bytes — never by prior metadata: the skeleton's
    /// rows replace every prior `bundles`/`assets` row for the file's
    /// UUIDs, so resolves against them (old and newly introduced alike)
    /// return the stable `Failed`, and queries whose selectors match the
    /// skeleton's entries fail naming this bundle. A caller that could
    /// not extract the complete skeleton publishes a file-scoped
    /// namespace error instead ([`InputTxn::set_namespace_errors`]).
    pub fn poison_bundle(
        &mut self,
        skeleton: &NamespaceSkeleton,
        error: &str,
    ) -> Result<(), StoreError> {
        // Replace, never retain: the prior rows describe the old bytes.
        self.remove_owned_asset_rows(skeleton.bundle)?;
        self.clear_path_refs(skeleton.bundle)?;
        self.txn.execute(
            "INSERT INTO bundles(bundle_uuid, root_id, path, format_version, content_hash, poison)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6)
             ON CONFLICT(bundle_uuid) DO UPDATE SET
               root_id = excluded.root_id, path = excluded.path,
               format_version = excluded.format_version,
               content_hash = excluded.content_hash, poison = excluded.poison",
            rusqlite::params![
                skeleton.bundle.0.as_slice(),
                skeleton.root.0,
                skeleton.path,
                skeleton.format_version,
                skeleton.content_hash.0.as_slice(),
                error,
            ],
        )?;
        for entry in &skeleton.entries {
            // Plain INSERT: a skeleton UUID colliding with another
            // bundle's row is a cross-file identity collision — §7 keeps
            // a namespace error for those, and the constraint
            // failure surfaces rather than silently reassigning the row.
            self.txn.execute(
                "INSERT INTO assets(
                     asset_uuid, bundle_uuid, local_id, type_uuid, logical_hash, authoring_only
                 ) VALUES (?1, ?2, ?3, ?4, NULL, ?5)",
                rusqlite::params![
                    entry.asset.0.as_slice(),
                    skeleton.bundle.0.as_slice(),
                    entry.local_id,
                    entry.type_uuid.0.as_slice(),
                    i64::from(entry.authoring_only),
                ],
            )?;
            for (tag, value) in &entry.tags {
                self.txn.execute(
                    "INSERT OR REPLACE INTO asset_tags(asset_uuid, tag, value) VALUES (?1, ?2, ?3)",
                    rusqlite::params![entry.asset.0.as_slice(), tag, value],
                )?;
            }
        }
        Ok(())
    }

}

impl Store {

    /// Complete tag extraction after the owning input transaction has made
    /// the candidate namespace readable but before that version is exposed by
    /// the RPC publication step. This deliberately does not
    /// advance the input version: a crash between the namespace transaction
    /// and this refinement leaves the conservative pending poison intact.
    pub fn refine_unpublished_tag_index(
        &mut self,
        expected: InputVersion,
        updates: &[TagIndexUpdate],
    ) -> Result<(), StoreError> {
        self.write_txn(|store| {
            if store.input_version() != expected {
                return Err(StoreError::InvalidConfiguration {
                    error: format!(
                        "tag-index refinement basis {:?}, current {:?}",
                        expected,
                        store.input_version()
                    ),
                });
            }
            let mut assets = BTreeSet::new();
            let txn = store.read.conn.savepoint()?;
            for update in updates {
                if !assets.insert(update.asset) {
                    return Err(StoreError::InvalidConfiguration {
                        error: format!("duplicate tag-index update for {}", update.asset),
                    });
                }
                let exists: bool = txn.query_row(
                    "SELECT EXISTS(SELECT 1 FROM assets WHERE asset_uuid = ?1)",
                    [update.asset.0.as_slice()],
                    |row| row.get(0),
                )?;
                if !exists {
                    return Err(StoreError::InvalidConfiguration {
                        error: format!("tag-index update names missing asset {}", update.asset),
                    });
                }
                if update.poison.is_some() && !update.tags.is_empty() {
                    return Err(StoreError::InvalidConfiguration {
                        error: format!("poisoned tag-index update {} carried tags", update.asset),
                    });
                }
                txn.execute(
                    "DELETE FROM asset_tags WHERE asset_uuid = ?1",
                    [update.asset.0.as_slice()],
                )?;
                for (tag, value) in &update.tags {
                    txn.execute(
                        "INSERT INTO asset_tags(asset_uuid, tag, value) VALUES (?1, ?2, ?3)",
                        rusqlite::params![update.asset.0.as_slice(), tag, value],
                    )?;
                }
                txn.execute(
                    "INSERT INTO asset_tag_index(
                        asset_uuid, tag_epoch, planner_version, dylib_hash, trace, poison
                     ) VALUES (?1, ?2, ?3, ?4, ?5, ?6)
                     ON CONFLICT(asset_uuid) DO UPDATE SET
                        tag_epoch = excluded.tag_epoch,
                        planner_version = excluded.planner_version,
                        dylib_hash = excluded.dylib_hash,
                        trace = excluded.trace,
                        poison = excluded.poison",
                    rusqlite::params![
                        update.asset.0.as_slice(),
                        update.tag_epoch.as_slice(),
                        update.planner_version.map(i64::from),
                        update.dylib_hash.map(|hash| hash.to_vec()),
                        update.trace,
                        update.poison,
                    ],
                )?;
            }
            txn.commit()?;
            Ok(())
        })
    }
}

impl StoreReader {
    pub fn tag_index_state(&self, asset: AssetUuid) -> Result<Option<TagIndexState>, StoreError> {
        Ok(self
            .conn
            .query_row(
                "SELECT tag_epoch, planner_version, dylib_hash, trace, poison
                 FROM asset_tag_index WHERE asset_uuid = ?1",
                [asset.0.as_slice()],
                |row| {
                    let planner = row
                        .get::<_, Option<i64>>(1)?
                        .map(|value| u32::try_from(value).unwrap_or(u32::MAX));
                    Ok(TagIndexState {
                        tag_epoch: blob32(row.get(0)?),
                        planner_version: planner,
                        dylib_hash: row.get::<_, Option<Vec<u8>>>(2)?.map(blob32),
                        trace: row.get(3)?,
                        poison: row.get(4)?,
                    })
                },
            )
            .optional()?)
    }

    // `CROSS JOIN` keeps the poisoned partial index the outer loop: the
    // planner would otherwise walk every asset to avoid the sort.
    fn tag_poisoned_bundles(&self, authoring_only: bool) -> Result<Vec<BundleUuid>, StoreError> {
        let mut statement = self.conn.prepare(
            "SELECT DISTINCT a.bundle_uuid
             FROM asset_tag_index i CROSS JOIN assets a ON a.asset_uuid = i.asset_uuid
             WHERE i.poison IS NOT NULL AND a.authoring_only = ?1
             ORDER BY a.bundle_uuid",
        )?;
        let rows =
            statement.query_map([i64::from(authoring_only)], |row| row.get::<_, Vec<u8>>(0))?;
        rows.map(|row| row.map(|bytes| BundleUuid(blob16(bytes))))
            .collect::<Result<Vec<_>, _>>()
            .map_err(StoreError::from)
    }

    /// The bundle row at (root name, path), if any.
    pub fn bundle_at(&self, root_name: &str, path: &str) -> Result<Option<BundleMeta>, StoreError> {
        let bundle = self
            .conn
            .query_row(
                "SELECT b.bundle_uuid FROM bundles b JOIN roots r USING (root_id)
                 WHERE r.name = ?1 AND b.path = ?2",
                rusqlite::params![root_name, path],
                |r| r.get::<_, Vec<u8>>(0),
            )
            .optional()?;
        match bundle {
            Some(bundle) => self.bundle(BundleUuid(blob16(bundle))),
            None => Ok(None),
        }
    }

    /// One bundle's physical row. Poisoned bundles still *have* a row —
    /// the poison is part of it.
    pub fn bundle(&self, bundle: BundleUuid) -> Result<Option<BundleMeta>, StoreError> {
        Ok(self
            .conn
            .prepare_cached(&format!(
                "SELECT {BUNDLE_COLUMNS} FROM bundles WHERE bundle_uuid = ?1"
            ))?
            .query_row([bundle.0.as_slice()], bundle_meta_row)
            .optional()?)
    }

    /// Complete deterministic bundle projection used to synthesize deletes
    /// during startup reconciliation and to hydrate the RPC metadata index.
    pub fn all_bundles(&self) -> Result<Vec<BundleMeta>, StoreError> {
        self.query_rows(
            &format!("SELECT {BUNDLE_COLUMNS} FROM bundles ORDER BY bundle_uuid"),
            [],
            bundle_meta_row,
        )
    }

    /// Visit every bundle row with its root's name, by bundle UUID: one
    /// streamed join, for a complete scan's publication.
    pub fn for_each_bundle_with_root_name(
        &self,
        mut visit: impl FnMut(String, BundleMeta) -> Result<(), StoreError>,
    ) -> Result<(), StoreError> {
        let mut statement = self.conn.prepare_cached(&format!(
            "SELECT {BUNDLE_COLUMNS}, r.name FROM bundles JOIN roots r USING (root_id)
             ORDER BY bundle_uuid"
        ))?;
        let mut rows = statement.query([])?;
        while let Some(row) = rows.next()? {
            visit(row.get(9)?, bundle_meta_row(row)?)?;
        }
        Ok(())
    }

    /// The bundle rows at logical `path` in any root, by bundle UUID.
    pub fn bundles_at_path(&self, path: &str) -> Result<Vec<BundleMeta>, StoreError> {
        self.query_rows(
            &format!("SELECT {BUNDLE_COLUMNS} FROM bundles WHERE path = ?1 ORDER BY bundle_uuid"),
            [path],
            bundle_meta_row,
        )
    }

    /// Every bundle a directory import generated (its row carries a
    /// [`DirectoryOrigin`]), by bundle UUID.
    pub fn generated_bundles(&self) -> Result<Vec<BundleMeta>, StoreError> {
        self.query_rows(
            &format!(
                "SELECT {BUNDLE_COLUMNS} FROM bundles
                 WHERE origin_rules_bundle IS NOT NULL ORDER BY bundle_uuid"
            ),
            [],
            bundle_meta_row,
        )
    }

    /// Every poisoned bundle, by UUID.
    pub fn poisoned_bundles(&self) -> Result<Vec<BundleUuid>, StoreError> {
        self.bundle_ids(
            "SELECT bundle_uuid FROM bundles WHERE poison IS NOT NULL ORDER BY bundle_uuid",
            [],
        )
    }

    /// Every bundle holding an entry under the reserved (`$`-prefixed) local
    /// id `local_id`, by UUID.
    pub fn bundles_with_reserved_entry(&self, local_id: &str) -> Result<Vec<BundleUuid>, StoreError> {
        if !local_id.starts_with('$') {
            return Err(StoreError::InvalidConfiguration {
                error: format!("{local_id:?} is not a reserved local id"),
            });
        }
        self.bundle_ids(
            "SELECT DISTINCT bundle_uuid FROM assets INDEXED BY assets_by_local_id
             WHERE local_id = ?1 ORDER BY bundle_uuid",
            [local_id],
        )
    }

    /// Every bundle whose reference fields name logical `path` (§13's
    /// `bundle_path_refs`), by UUID.
    pub fn bundles_referencing_path(&self, path: &str) -> Result<Vec<BundleUuid>, StoreError> {
        self.bundle_ids(
            "SELECT bundle_uuid FROM bundle_path_refs WHERE target = ?1 ORDER BY bundle_uuid",
            [path],
        )
    }

    /// The logical path strings `bundle`'s reference fields name.
    pub fn bundle_path_refs(&self, bundle: BundleUuid) -> Result<BTreeSet<String>, StoreError> {
        Ok(self
            .query_rows(
                "SELECT target FROM bundle_path_refs WHERE bundle_uuid = ?1 ORDER BY target",
                [bundle.0.as_slice()],
                |row| row.get::<_, String>(0),
            )?
            .into_iter()
            .collect())
    }

    fn bundle_ids<P: rusqlite::Params>(
        &self,
        sql: &str,
        params: P,
    ) -> Result<Vec<BundleUuid>, StoreError> {
        self.query_rows(sql, params, |row| {
            Ok(BundleUuid(blob16(row.get::<_, Vec<u8>>(0)?)))
        })
    }

    /// Whether an `assets` row (skeleton rows included) exists for `asset`.
    pub fn asset_exists(&self, asset: AssetUuid) -> Result<bool, StoreError> {
        Ok(self
            .conn
            .prepare_cached("SELECT EXISTS(SELECT 1 FROM assets WHERE asset_uuid = ?1)")?
            .query_row([asset.0.as_slice()], |row| row.get(0))?)
    }

    /// The error [`StoreReader::entry`] returns for the first asset, in UUID
    /// order, whose entry cannot be read: one owned by a poisoned bundle, or
    /// a row with no logical hash. `Ok(())` when every entry reads. Both
    /// sets come from partial indexes; healthy rows are never visited.
    pub fn check_entries(&self) -> Result<(), StoreError> {
        let first = self
            .conn
            .prepare_cached(
                "SELECT asset_uuid FROM (
                     SELECT asset_uuid FROM assets WHERE logical_hash IS NULL
                     UNION
                     SELECT a.asset_uuid FROM bundles b
                       JOIN assets a ON a.bundle_uuid = b.bundle_uuid
                      WHERE b.poison IS NOT NULL)
                 ORDER BY asset_uuid LIMIT 1",
            )?
            .query_row([], |row| row.get::<_, Vec<u8>>(0))
            .optional()?;
        match first {
            Some(asset) => self.entry(AssetUuid(blob16(asset))).map(drop),
            None => Ok(()),
        }
    }

    /// The failures [`StoreReader::assets_by_tag_value`] (or, with
    /// `authoring_only`, [`StoreReader::authoring_assets_by_tag_value`])
    /// reports for this selector, without collecting its assets.
    pub fn check_tag_selector(
        &self,
        tag: &str,
        value: Option<&str>,
        authoring_only: bool,
    ) -> Result<(), StoreError> {
        let poisoned = self.tag_poisoned_bundles(authoring_only)?;
        if !poisoned.is_empty() {
            return Err(StoreError::TagIndexPoisoned { bundles: poisoned });
        }
        let poisoned_owner = self
            .conn
            .prepare_cached(
                // Driven from the poisoned bundles' partial index: a
                // common tag must not walk every tagged asset.
                "SELECT b.bundle_uuid, b.poison
                 FROM bundles b CROSS JOIN assets a ON a.bundle_uuid = b.bundle_uuid
                 WHERE b.poison IS NOT NULL AND a.authoring_only = ?3
                   AND EXISTS (SELECT 1 FROM asset_tags t
                               WHERE t.asset_uuid = a.asset_uuid AND t.tag = ?1
                                 AND (?2 IS NULL OR t.value = ?2))
                 ORDER BY a.asset_uuid LIMIT 1",
            )?
            .query_row(
                rusqlite::params![tag, value, i64::from(authoring_only)],
                |row| Ok((row.get::<_, Vec<u8>>(0)?, row.get::<_, String>(1)?)),
            )
            .optional()?;
        match poisoned_owner {
            Some((bundle, error)) => Err(StoreError::BundlePoisoned {
                bundle: BundleUuid(blob16(bundle)),
                error,
            }),
            None => Ok(()),
        }
    }

    /// The asset rows of non-poisoned bundles that `filter` selects, with
    /// their bundle and its logical path, by asset UUID. Every selector is
    /// a SQL condition; the most selective drives the query from its index.
    pub fn namespace_assets_matching(
        &self,
        filter: &AssetFilter,
    ) -> Result<Vec<MatchedAsset>, StoreError> {
        let mut params = Vec::new();
        let conditions = filter.sql_conditions(&mut params);
        self.query_rows(
            &format!(
                "SELECT a.asset_uuid, a.bundle_uuid, b.path FROM {}
                 WHERE b.poison IS NULL{conditions} ORDER BY a.asset_uuid",
                filter.sql_from()
            ),
            rusqlite::params_from_iter(params),
            matched_asset_row,
        )
    }

    /// Complete deterministic entry projection for one bundle. Poisoned
    /// skeleton rows intentionally fail through [`Store::entry`] rather than
    /// being mistaken for ordinary authored metadata.
    pub fn entries_in_bundle(&self, bundle: BundleUuid) -> Result<Vec<EntryMeta>, StoreError> {
        let mut statement = self
            .conn
            .prepare("SELECT asset_uuid FROM assets WHERE bundle_uuid = ?1 ORDER BY asset_uuid")?;
        let assets = statement
            .query_map([bundle.0.as_slice()], |row| row.get::<_, Vec<u8>>(0))?
            .collect::<Result<Vec<_>, _>>()?;
        let mut entries = Vec::with_capacity(assets.len());
        for asset in assets {
            if let Some(entry) = self.entry(AssetUuid(blob16(asset)))? {
                entries.push(entry);
            }
        }
        Ok(entries)
    }

    /// Raw deterministic identity set for one bundle, including poisoned
    /// skeleton rows. Incremental healing needs the prior UUID set without
    /// interpreting poisoned metadata or enumerating unrelated bundles.
    pub fn asset_ids_in_bundle(
        &self,
        bundle: BundleUuid,
    ) -> Result<BTreeSet<AssetUuid>, StoreError> {
        let mut statement = self
            .conn
            .prepare("SELECT asset_uuid FROM assets WHERE bundle_uuid = ?1 ORDER BY asset_uuid")?;
        let rows = statement.query_map([bundle.0.as_slice()], |row| row.get::<_, Vec<u8>>(0))?;
        rows.map(|row| row.map(|bytes| AssetUuid(blob16(bytes))))
            .collect::<Result<BTreeSet<_>, _>>()
            .map_err(StoreError::from)
    }

    /// Complete path-index projection grouped by normalized logical path.
    /// Multiple roots remain multiple candidates; no root is selected here.
    pub fn all_path_entries(&self) -> Result<Vec<(String, RootId, AssetUuid)>, StoreError> {
        let mut statement = self
            .conn
            .prepare("SELECT path, root_id, asset_uuid FROM path_index ORDER BY path, root_id")?;
        let rows = statement.query_map([], |row| {
            Ok((
                row.get(0)?,
                RootId(row.get(1)?),
                AssetUuid(blob16(row.get(2)?)),
            ))
        })?;
        rows.collect::<Result<Vec<_>, _>>()
            .map_err(StoreError::from)
    }

    /// Current logical candidates for one normalized path. Ordinary watcher
    /// publications use this bounded lookup instead of enumerating the whole
    /// path index.
    pub fn path_assets(&self, path: &str) -> Result<BTreeSet<AssetUuid>, StoreError> {
        let mut statement = self
            .conn
            .prepare("SELECT asset_uuid FROM path_index WHERE path = ?1 ORDER BY asset_uuid")?;
        let rows = statement.query_map([path], |row| row.get::<_, Vec<u8>>(0))?;
        rows.map(|row| row.map(|bytes| AssetUuid(blob16(bytes))))
            .collect::<Result<BTreeSet<_>, _>>()
            .map_err(StoreError::from)
    }

    /// Raw deterministic asset identity set, including poisoned skeleton rows.
    /// Startup reconciliation uses it only to remove identities absent from a
    /// healed full scan; it does not expose skeleton metadata.
    pub fn all_asset_ids(&self) -> Result<Vec<AssetUuid>, StoreError> {
        let mut statement = self
            .conn
            .prepare("SELECT asset_uuid FROM assets ORDER BY asset_uuid")?;
        let rows = statement.query_map([], |row| row.get::<_, Vec<u8>>(0))?;
        rows.map(|row| row.map(|bytes| AssetUuid(blob16(bytes))))
            .collect::<Result<Vec<_>, _>>()
            .map_err(StoreError::from)
    }

    /// The tag-index rows a refinement under `tag_epoch` and the pipeline
    /// module `dylib_hash` (none when no module is loaded) must redo, each
    /// with its asset's bundle: poisoned rows (pending ones included), rows
    /// of another schema epoch, and migrated rows of another module. Every
    /// other row already holds what refining it would write. Each kind is
    /// one search of its index, so this costs the rows it returns.
    pub fn stale_tag_index_assets(
        &self,
        tag_epoch: [u8; 32],
        dylib_hash: Option<[u8; 32]>,
    ) -> Result<BTreeMap<AssetUuid, BundleUuid>, StoreError> {
        // No module: every migrated row is stale, and every blob sorts
        // after the empty one.
        let module = dylib_hash.map_or_else(Vec::new, |hash| hash.to_vec());
        let mut statement = self.conn.prepare_cached(
            "SELECT i.asset_uuid, a.bundle_uuid
             FROM asset_tag_index i JOIN assets a USING (asset_uuid)
             WHERE i.poison IS NOT NULL
             UNION SELECT i.asset_uuid, a.bundle_uuid
             FROM asset_tag_index i JOIN assets a USING (asset_uuid)
             WHERE i.tag_epoch < ?1
             UNION SELECT i.asset_uuid, a.bundle_uuid
             FROM asset_tag_index i JOIN assets a USING (asset_uuid)
             WHERE i.tag_epoch > ?1
             UNION SELECT i.asset_uuid, a.bundle_uuid
             FROM asset_tag_index i JOIN assets a USING (asset_uuid)
             WHERE i.dylib_hash < ?2
             UNION SELECT i.asset_uuid, a.bundle_uuid
             FROM asset_tag_index i JOIN assets a USING (asset_uuid)
             WHERE i.dylib_hash > ?2",
        )?;
        let rows = statement.query_map(
            rusqlite::params![tag_epoch.as_slice(), module],
            |row| {
                Ok((
                    AssetUuid(blob16(row.get::<_, Vec<u8>>(0)?)),
                    BundleUuid(blob16(row.get::<_, Vec<u8>>(1)?)),
                ))
            },
        )?;
        rows.collect::<Result<BTreeMap<_, _>, _>>()
            .map_err(StoreError::from)
    }

    /// Raw deterministic asset-to-bundle projection, including poisoned
    /// skeleton rows. A whole-namespace bulk read no publication makes: the
    /// tests compare the bounded reads against it.
    pub fn all_asset_bundles(&self) -> Result<BTreeMap<AssetUuid, BundleUuid>, StoreError> {
        let mut statement = self
            .conn
            .prepare("SELECT asset_uuid, bundle_uuid FROM assets ORDER BY asset_uuid")?;
        let rows = statement.query_map([], |row| {
            Ok((
                AssetUuid(blob16(row.get::<_, Vec<u8>>(0)?)),
                BundleUuid(blob16(row.get::<_, Vec<u8>>(1)?)),
            ))
        })?;
        rows.collect::<Result<BTreeMap<_, _>, _>>()
            .map_err(StoreError::from)
    }

    /// Visit every asset row's (asset, bundle), skeleton rows included, in
    /// asset UUID order, without collecting them.
    pub fn for_each_asset_bundle(
        &self,
        mut visit: impl FnMut(AssetUuid, BundleUuid) -> Result<(), StoreError>,
    ) -> Result<(), StoreError> {
        let mut statement = self
            .conn
            .prepare_cached("SELECT asset_uuid, bundle_uuid FROM assets ORDER BY asset_uuid")?;
        let mut rows = statement.query([])?;
        while let Some(row) = rows.next()? {
            visit(
                AssetUuid(blob16(row.get::<_, Vec<u8>>(0)?)),
                BundleUuid(blob16(row.get::<_, Vec<u8>>(1)?)),
            )?;
        }
        Ok(())
    }

    /// Visit every asset row's (bundle, asset), skeleton rows included, in
    /// (bundle, asset) order: each bundle's assets arrive together, read
    /// from the `assets_by_bundle` index alone.
    pub fn for_each_bundle_asset(
        &self,
        mut visit: impl FnMut(BundleUuid, AssetUuid) -> Result<(), StoreError>,
    ) -> Result<(), StoreError> {
        let mut statement = self.conn.prepare_cached(
            "SELECT bundle_uuid, asset_uuid FROM assets ORDER BY bundle_uuid, asset_uuid",
        )?;
        let mut rows = statement.query([])?;
        while let Some(row) = rows.next()? {
            visit(
                BundleUuid(blob16(row.get::<_, Vec<u8>>(0)?)),
                AssetUuid(blob16(row.get::<_, Vec<u8>>(1)?)),
            )?;
        }
        Ok(())
    }

    /// Visit [`Self::all_path_entries`]'s rows in its (path, root) order
    /// without collecting them.
    pub fn for_each_path_entry(
        &self,
        mut visit: impl FnMut(String, RootId, AssetUuid) -> Result<(), StoreError>,
    ) -> Result<(), StoreError> {
        let mut statement = self
            .conn
            .prepare_cached("SELECT path, root_id, asset_uuid FROM path_index ORDER BY path, root_id")?;
        let mut rows = statement.query([])?;
        while let Some(row) = rows.next()? {
            visit(row.get(0)?, RootId(row.get(1)?), AssetUuid(blob16(row.get(2)?)))?;
        }
        Ok(())
    }

    /// Every generated bundle a rules bundle owns (§2, §8): the
    /// scan-derived ownership index orphan tracking re-derives after
    /// daemon-state loss — never precious.
    pub fn bundles_owned_by(&self, rules: BundleUuid) -> Result<Vec<BundleUuid>, StoreError> {
        let mut stmt = self.conn.prepare(
            "SELECT bundle_uuid FROM bundles WHERE origin_rules_bundle = ?1 ORDER BY bundle_uuid",
        )?;
        let rows = stmt.query_map([rules.0.as_slice()], |r| r.get::<_, Vec<u8>>(0))?;
        let mut out = Vec::new();
        for row in rows {
            out.push(BundleUuid(blob16(row?)));
        }
        Ok(out)
    }

    fn bundle_poison(&self, bundle: &[u8]) -> Result<Option<String>, StoreError> {
        Ok(self
            .conn
            .query_row(
                "SELECT poison FROM bundles WHERE bundle_uuid = ?1",
                [bundle],
                |r| r.get::<_, Option<String>>(0),
            )
            .optional()?
            .flatten())
    }

    /// §13 `MetadataSnapshot::entry` semantics: `Ok(None)` is a
    /// recordable miss; a namespace error or a poisoned owning bundle is
    /// `Err`, never last-good metadata.
    pub fn entry(&self, asset: AssetUuid) -> Result<Option<EntryMeta>, StoreError> {
        let row = self
            .conn
            .query_row(
                "SELECT bundle_uuid, local_id, type_uuid, logical_hash, authoring_only FROM assets
                 WHERE asset_uuid = ?1",
                [asset.0.as_slice()],
                |r| {
                    Ok((
                        r.get::<_, Vec<u8>>(0)?,
                        r.get::<_, String>(1)?,
                        r.get::<_, Vec<u8>>(2)?,
                        // NULL only on a skeleton row (§7), whose owning
                        // bundle is poisoned — the poison gate below
                        // fires before this is ever consumed.
                        r.get::<_, Option<Vec<u8>>>(3)?,
                        r.get::<_, i64>(4)? != 0,
                    ))
                },
            )
            .optional()?;
        let Some((bundle_bytes, local_id, type_bytes, hash_bytes, authoring_only)) = row else {
            return Ok(None);
        };
        if let Some(error) = self.bundle_poison(&bundle_bytes)? {
            return Err(StoreError::BundlePoisoned {
                bundle: BundleUuid(blob16(bundle_bytes)),
                error,
            });
        }
        // Not poisoned ⇒ never a skeleton row: the hash is present by
        // the healing invariant (upsert_bundle drops skeleton rows
        // whenever a poison clears). A NULL here is store corruption and
        // surfaces as a typed column error, never a panic.
        let hash_bytes = hash_bytes.ok_or_else(|| {
            StoreError::Sqlite(rusqlite::Error::InvalidColumnType(
                3,
                "logical_hash".to_owned(),
                rusqlite::types::Type::Null,
            ))
        })?;
        let tags: BTreeMap<String, Option<String>> = {
            let mut stmt = self
                .conn
                .prepare("SELECT tag, value FROM asset_tags WHERE asset_uuid = ?1 ORDER BY tag")?;
            let rows = stmt.query_map([asset.0.as_slice()], |r| {
                Ok((r.get::<_, String>(0)?, r.get::<_, Option<String>>(1)?))
            })?;
            rows.collect::<Result<_, _>>()?
        };
        Ok(Some(EntryMeta {
            asset,
            bundle: BundleUuid(blob16(bundle_bytes)),
            local_id,
            type_uuid: TypeUuid(blob16(type_bytes)),
            logical_hash: LogicalHash(blob32(hash_bytes)),
            authoring_only,
            tags,
        }))
    }

    /// Runtime direct-UUID lookup. Authoring/control rows remain visible to
    /// `entry()` for tooling metadata, but can never enter a runtime closure.
    pub fn runtime_entry(&self, asset: AssetUuid) -> Result<Option<EntryMeta>, StoreError> {
        let entry = self.entry(asset)?;
        if entry.as_ref().is_some_and(|entry| entry.authoring_only) {
            return Err(StoreError::RoleIneligible { asset });
        }
        Ok(entry)
    }

    /// §13 `MetadataSnapshot::resolve_path` semantics: `Ok(None)` is a
    /// recordable miss; a path resolvable in more than one asset root is
    /// `Err` (§18), never a tiebreak; a namespace error is `Err`.
    pub fn resolve_path(&self, path: &str) -> Result<Option<AssetUuid>, StoreError> {
        // A poisoned bundle's own path fails naming it (§13): the poison
        // row replaced the file's asset rows, and a Missing here would
        // silently change query semantics.
        let poisoned_at_path: Option<(Vec<u8>, String)> = self
            .conn
            .query_row(
                "SELECT bundle_uuid, poison FROM bundles
                 WHERE path = ?1 AND poison IS NOT NULL LIMIT 1",
                [path],
                |r| Ok((r.get(0)?, r.get(1)?)),
            )
            .optional()?;
        if let Some((bundle_bytes, error)) = poisoned_at_path {
            return Err(StoreError::BundlePoisoned {
                bundle: BundleUuid(blob16(bundle_bytes)),
                error,
            });
        }
        let mut stmt = self.conn.prepare(
            "SELECT p.root_id, p.asset_uuid, r.name FROM path_index p
             LEFT JOIN roots r ON r.root_id = p.root_id
             WHERE p.path = ?1 ORDER BY p.root_id",
        )?;
        let rows: Vec<(i64, Vec<u8>, Option<String>)> = stmt
            .query_map([path], |r| Ok((r.get(0)?, r.get(1)?, r.get(2)?)))?
            .collect::<Result<_, _>>()?;
        match rows.len() {
            0 => Ok(None),
            1 => {
                let asset = AssetUuid(blob16(rows.into_iter().next().unwrap().1));
                // A resolution reaching a poisoned bundle is the stable
                // Failed, not a silent success (§13).
                let owner: Option<(Vec<u8>, Option<String>, bool)> = self
                    .conn
                    .query_row(
                        "SELECT b.bundle_uuid, b.poison, a.authoring_only FROM assets a
                         JOIN bundles b ON b.bundle_uuid = a.bundle_uuid
                         WHERE a.asset_uuid = ?1",
                        [asset.0.as_slice()],
                        |r| Ok((r.get(0)?, r.get(1)?, r.get::<_, i64>(2)? != 0)),
                    )
                    .optional()?;
                if let Some((bundle_bytes, poison, authoring_only)) = owner {
                    if let Some(error) = poison {
                        return Err(StoreError::BundlePoisoned {
                            bundle: BundleUuid(blob16(bundle_bytes)),
                            error,
                        });
                    }
                    if authoring_only {
                        return Err(StoreError::RoleIneligible { asset });
                    }
                }
                Ok(Some(asset))
            }
            _ => Err(StoreError::AmbiguousPath {
                path: path.to_owned(),
                roots: rows
                    .into_iter()
                    .map(|(id, _, name)| name.unwrap_or_else(|| format!("root#{id}")))
                    .collect(),
            }),
        }
    }

    /// Tag lookup over the search tags (§13's `assets` row). A selector
    /// matching any poisoned bundle's entries fails naming that bundle —
    /// the same shape as §10's tag poisoning.
    pub fn assets_by_tag(&self, tag: &str) -> Result<Vec<AssetUuid>, StoreError> {
        self.assets_by_tag_value(tag, None)
    }

    pub fn assets_by_tag_value(
        &self,
        tag: &str,
        value: Option<&str>,
    ) -> Result<Vec<AssetUuid>, StoreError> {
        let poisoned = self.tag_poisoned_bundles(false)?;
        if !poisoned.is_empty() {
            return Err(StoreError::TagIndexPoisoned { bundles: poisoned });
        }
        let mut stmt = self.conn.prepare(
            "SELECT a.asset_uuid, b.bundle_uuid, b.poison FROM asset_tags t
             JOIN assets a ON a.asset_uuid = t.asset_uuid
             JOIN bundles b ON b.bundle_uuid = a.bundle_uuid
             WHERE t.tag = ?1 AND (?2 IS NULL OR t.value = ?2)
               AND a.authoring_only = 0 ORDER BY a.asset_uuid",
        )?;
        let rows: Vec<(Vec<u8>, Vec<u8>, Option<String>)> = stmt
            .query_map(rusqlite::params![tag, value], |r| {
                Ok((r.get(0)?, r.get(1)?, r.get(2)?))
            })?
            .collect::<Result<_, _>>()?;
        let mut out = Vec::with_capacity(rows.len());
        for (asset_bytes, bundle_bytes, poison) in rows {
            if let Some(error) = poison {
                return Err(StoreError::BundlePoisoned {
                    bundle: BundleUuid(blob16(bundle_bytes)),
                    error,
                });
            }
            out.push(AssetUuid(blob16(asset_bytes)));
        }
        Ok(out)
    }

    /// Explicit tooling-only tag lookup. This surface cannot be used as a
    /// processor-input, runtime-reference, or pack-root selector.
    pub fn authoring_assets_by_tag(&self, tag: &str) -> Result<Vec<AssetUuid>, StoreError> {
        self.authoring_assets_by_tag_value(tag, None)
    }

    pub fn authoring_assets_by_tag_value(
        &self,
        tag: &str,
        value: Option<&str>,
    ) -> Result<Vec<AssetUuid>, StoreError> {
        let poisoned = self.tag_poisoned_bundles(true)?;
        if !poisoned.is_empty() {
            return Err(StoreError::TagIndexPoisoned { bundles: poisoned });
        }
        let mut stmt = self.conn.prepare(
            "SELECT a.asset_uuid, b.bundle_uuid, b.poison FROM asset_tags t
             JOIN assets a ON a.asset_uuid = t.asset_uuid
             JOIN bundles b ON b.bundle_uuid = a.bundle_uuid
             WHERE t.tag = ?1 AND (?2 IS NULL OR t.value = ?2)
               AND a.authoring_only = 1 ORDER BY a.asset_uuid",
        )?;
        let rows: Vec<(Vec<u8>, Vec<u8>, Option<String>)> = stmt
            .query_map(rusqlite::params![tag, value], |row| {
                Ok((row.get(0)?, row.get(1)?, row.get(2)?))
            })?
            .collect::<Result<_, _>>()?;
        let mut out = Vec::with_capacity(rows.len());
        for (asset_bytes, bundle_bytes, poison) in rows {
            if let Some(error) = poison {
                return Err(StoreError::BundlePoisoned {
                    bundle: BundleUuid(blob16(bundle_bytes)),
                    error,
                });
            }
            out.push(AssetUuid(blob16(asset_bytes)));
        }
        Ok(out)
    }

    /// Reverse dependency lookup by selector (§13's `deps` indexes).
    pub fn deps_on(&self, kind: DepKind, target: &str) -> Result<Vec<AssetUuid>, StoreError> {
        let mut stmt = self
            .conn
            .prepare("SELECT src_uuid FROM deps WHERE kind = ?1 AND target = ?2")?;
        let rows = stmt.query_map(rusqlite::params![kind.to_i64(), target], |r| {
            r.get::<_, Vec<u8>>(0)
        })?;
        let mut out = Vec::new();
        for row in rows {
            out.push(AssetUuid(blob16(row?)));
        }
        Ok(out)
    }

    /// Cached schema JSON by logical hash.
    pub fn schema(&self, hash: LogicalHash) -> Result<Option<String>, StoreError> {
        Ok(self
            .conn
            .query_row(
                "SELECT schema_json FROM schemas WHERE logical_hash = ?1",
                [hash.0.as_slice()],
                |r| r.get(0),
            )
            .optional()?)
    }

    /// Every retained exact-hash schema snapshot, including snapshots no
    /// longer referenced by the current bundle projection. Doctor uses this
    /// disposable cache as one additional exact repair source.
    pub fn all_schemas(&self) -> Result<Vec<(LogicalHash, String)>, StoreError> {
        let mut statement = self
            .conn
            .prepare("SELECT logical_hash, schema_json FROM schemas ORDER BY logical_hash")?;
        let rows = statement
            .query_map([], |row| {
                Ok((row.get::<_, Vec<u8>>(0)?, row.get::<_, String>(1)?))
            })?
            .collect::<Result<Vec<_>, _>>()?;
        rows.into_iter()
            .map(|(hash, json)| {
                if hash.len() != 32 {
                    return Err(StoreError::InvalidSchemaCache {
                        detail: "schema cache contains a non-32-byte logical hash".to_owned(),
                    });
                }
                Ok((LogicalHash(blob32(hash)), json))
            })
            .collect()
    }
}

const BUNDLE_COLUMNS: &str = "bundle_uuid, root_id, path, format_version, content_hash,
     origin_rules_bundle, origin_rule, origin_group_root, origin_group_path";

fn bundle_meta_row(row: &rusqlite::Row<'_>) -> rusqlite::Result<BundleMeta> {
    let origin = match (
        row.get::<_, Option<Vec<u8>>>(5)?,
        row.get::<_, Option<Vec<u8>>>(6)?,
        row.get::<_, Option<String>>(7)?,
        row.get::<_, Option<String>>(8)?,
    ) {
        (Some(rules), Some(rule), Some(group_root), Some(group_path)) => Some(DirectoryOrigin {
            rules_bundle: BundleUuid(blob16(rules)),
            rule: DirectoryRuleId(blob16(rule)),
            group_root,
            group_path,
        }),
        _ => None,
    };
    Ok(BundleMeta {
        bundle: BundleUuid(blob16(row.get(0)?)),
        root: RootId(row.get(1)?),
        path: row.get(2)?,
        format_version: row.get(3)?,
        content_hash: ContentHash(blob32(row.get(4)?)),
        origin,
    })
}

/// A conjunction of asset selectors, answered by SQL over the `assets`,
/// `bundles` and `asset_tags` indexes. An absent selector selects every row.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct AssetFilter {
    pub asset: Option<AssetUuid>,
    pub bundle: Option<BundleUuid>,
    /// The owning bundle's logical path, exactly.
    pub bundle_path: Option<String>,
    /// The final segment of the owning bundle's logical path, exactly.
    pub bundle_name: Option<String>,
    pub local_id: Option<String>,
    pub authored_type: Option<TypeUuid>,
    pub terminal_type: Option<TypeUuid>,
    /// A search tag, with its value when `Some`: an asset carrying the tag
    /// with any value (`None`) or exactly that value.
    pub tag: Option<(String, Option<String>)>,
    /// Strings the owning bundle's logical path starts with; every one must
    /// hold.
    pub path_prefixes: Vec<String>,
    /// Only authoring-only rows (`Some(true)`) or only runtime rows. Alone,
    /// `Some(false)` selects every runtime row: it narrows nothing.
    pub authoring_only: Option<bool>,
    /// Only assets whose tag index is poisoned (pending or failed).
    pub tag_index_poisoned: bool,
}

/// The selector a filter's query is driven from, and so the index it
/// names. SQLite keeps no statistics here and cannot tell a basename from
/// a type by selectivity, so the filter decides, in the order build traces
/// pick their candidates in: an identity or exact name first (asset, bundle,
/// bundle path, bundle name, local id), then the poisoned tag-index rows
/// (normally none), a tag value, an authored type, a path prefix, a terminal
/// type and a bare tag, then the authoring-only rows. Every other selector is checked on the rows the
/// driver finds.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Driver {
    Asset,
    Bundle,
    BundlePath,
    BundleName,
    LocalId,
    TagPoisoned,
    Tag,
    AuthoredType,
    TerminalType,
    PathPrefix,
    AuthoringOnly,
    Everything,
}

impl AssetFilter {
    /// With the keys of a path glob (see [`crate::files::GlobKeys`]): its
    /// literal prefix and the final segment its literal tail names.
    pub fn with_glob_keys(mut self, keys: crate::files::GlobKeys<'_>) -> Self {
        if !keys.prefix.is_empty() {
            self.path_prefixes.push(keys.prefix.to_owned());
        }
        if self.bundle_name.is_none() {
            self.bundle_name = keys.name.map(str::to_owned);
        }
        self
    }

    fn driver(&self) -> Driver {
        let tag_value = self.tag.as_ref().is_some_and(|(_, value)| value.is_some());
        if self.asset.is_some() {
            Driver::Asset
        } else if self.bundle.is_some() {
            Driver::Bundle
        } else if self.bundle_path.is_some() {
            Driver::BundlePath
        } else if self.bundle_name.is_some() {
            Driver::BundleName
        } else if self.local_id.is_some() {
            Driver::LocalId
        } else if self.tag_index_poisoned {
            Driver::TagPoisoned
        } else if tag_value {
            Driver::Tag
        } else if self.authored_type.is_some() {
            Driver::AuthoredType
        } else if self.path_prefixes.iter().any(|prefix| !prefix.is_empty()) {
            Driver::PathPrefix
        } else if self.terminal_type.is_some() {
            Driver::TerminalType
        } else if self.tag.is_some() {
            Driver::Tag
        } else if self.authoring_only == Some(true) {
            Driver::AuthoringOnly
        } else {
            Driver::Everything
        }
    }

    /// The `assets a`, `bundles b` join this filter's driver walks, outer
    /// table first, each table on the index it must use.
    pub(crate) fn sql_from(&self) -> &'static str {
        const BY_ASSET: &str = "assets a INDEXED BY sqlite_autoindex_assets_1
             CROSS JOIN bundles b ON b.bundle_uuid = a.bundle_uuid";
        match self.driver() {
            Driver::Asset | Driver::TagPoisoned | Driver::Tag | Driver::Everything => BY_ASSET,
            Driver::Bundle => {
                "assets a INDEXED BY assets_by_bundle
                 CROSS JOIN bundles b ON b.bundle_uuid = a.bundle_uuid"
            }
            Driver::LocalId => {
                "assets a INDEXED BY assets_by_local_id
                 CROSS JOIN bundles b ON b.bundle_uuid = a.bundle_uuid"
            }
            Driver::AuthoredType => {
                "assets a INDEXED BY assets_by_type
                 CROSS JOIN bundles b ON b.bundle_uuid = a.bundle_uuid"
            }
            Driver::TerminalType => {
                "assets a INDEXED BY assets_by_terminal_type
                 CROSS JOIN bundles b ON b.bundle_uuid = a.bundle_uuid"
            }
            Driver::AuthoringOnly => {
                "assets a INDEXED BY assets_authoring
                 CROSS JOIN bundles b ON b.bundle_uuid = a.bundle_uuid"
            }
            Driver::BundlePath | Driver::PathPrefix => {
                "bundles b INDEXED BY bundles_by_path
                 CROSS JOIN assets a INDEXED BY assets_by_bundle ON a.bundle_uuid = b.bundle_uuid"
            }
            Driver::BundleName => {
                "bundles b INDEXED BY bundles_by_name
                 CROSS JOIN assets a INDEXED BY assets_by_bundle ON a.bundle_uuid = b.bundle_uuid"
            }
        }
    }

    /// `AND`-prefixed conditions over [`Self::sql_from`]'s join, pushing
    /// their parameters (numbered from `params.len() + 1`).
    pub(crate) fn sql_conditions(&self, params: &mut Vec<rusqlite::types::Value>) -> String {
        use rusqlite::types::Value;
        /// Bind `value` and return its parameter number.
        fn bind(params: &mut Vec<Value>, value: Value) -> usize {
            params.push(value);
            params.len()
        }
        let driver = self.driver();
        let mut conditions = Vec::new();
        if let Some(asset) = self.asset {
            let n = bind(params, Value::Blob(asset.0.to_vec()));
            conditions.push(format!("a.asset_uuid = ?{n}"));
        }
        if let Some(bundle) = self.bundle {
            let n = bind(params, Value::Blob(bundle.0.to_vec()));
            conditions.push(format!("a.bundle_uuid = ?{n}"));
        }
        if let Some(path) = &self.bundle_path {
            let n = bind(params, Value::Text(path.clone()));
            conditions.push(format!("b.path = ?{n}"));
        }
        if let Some(name) = &self.bundle_name {
            let n = bind(params, Value::Text(name.clone()));
            conditions.push(format!("b.name = ?{n}"));
        }
        if let Some(local_id) = &self.local_id {
            let n = bind(params, Value::Text(local_id.clone()));
            conditions.push(format!("a.local_id = ?{n}"));
        }
        if let Some(type_uuid) = self.authored_type {
            let n = bind(params, Value::Blob(type_uuid.0.to_vec()));
            conditions.push(format!("a.type_uuid = ?{n}"));
        }
        if let Some(type_uuid) = self.terminal_type {
            let n = bind(params, Value::Blob(type_uuid.0.to_vec()));
            conditions.push(format!("a.terminal_type = ?{n}"));
        }
        // Every path starts with the empty prefix.
        for prefix in self.path_prefixes.iter().filter(|prefix| !prefix.is_empty()) {
            let n = bind(params, Value::Text(prefix.clone()));
            conditions.push(crate::files::starts_with_sql("b.path", n));
        }
        if let Some((tag, value)) = &self.tag {
            let n = bind(params, Value::Text(tag.clone()));
            let value = match value {
                Some(value) => format!(" AND t.value = ?{}", bind(params, Value::Text(value.clone()))),
                None => String::new(),
            };
            // Driving, the tag's rows are the candidates; otherwise each
            // candidate's tag is checked on its primary key.
            conditions.push(if driver == Driver::Tag {
                format!(
                    "a.asset_uuid IN (SELECT t.asset_uuid FROM asset_tags t
                                      WHERE t.tag = ?{n}{value})"
                )
            } else {
                format!(
                    "EXISTS (SELECT 1 FROM asset_tags t
                             WHERE t.asset_uuid = a.asset_uuid AND t.tag = ?{n}{value})"
                )
            });
        }
        // A literal, so the partial `assets_authoring` index applies.
        if let Some(authoring_only) = self.authoring_only {
            conditions.push(format!("a.authoring_only = {}", i64::from(authoring_only)));
        }
        if self.tag_index_poisoned {
            conditions.push(if driver == Driver::TagPoisoned {
                "a.asset_uuid IN (SELECT i.asset_uuid FROM asset_tag_index i
                                  WHERE i.poison IS NOT NULL)"
                    .to_owned()
            } else {
                "EXISTS (SELECT 1 FROM asset_tag_index i
                         WHERE i.asset_uuid = a.asset_uuid AND i.poison IS NOT NULL)"
                    .to_owned()
            });
        }
        conditions
            .iter()
            .map(|condition| format!(" AND {condition}"))
            .collect()
    }
}

/// One asset a filter selected: its UUID, owning bundle, and the bundle's
/// logical path.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MatchedAsset {
    pub asset: AssetUuid,
    pub bundle: BundleUuid,
    pub path: String,
}

pub(crate) fn matched_asset_row(row: &rusqlite::Row<'_>) -> rusqlite::Result<MatchedAsset> {
    Ok(MatchedAsset {
        asset: AssetUuid(blob16(row.get(0)?)),
        bundle: BundleUuid(blob16(row.get(1)?)),
        path: row.get(2)?,
    })
}

pub(crate) fn blob16(bytes: Vec<u8>) -> [u8; 16] {
    let mut out = [0u8; 16];
    out.copy_from_slice(&bytes);
    out
}

pub(crate) fn blob32(bytes: Vec<u8>) -> [u8; 32] {
    let mut out = [0u8; 32];
    out.copy_from_slice(&bytes);
    out
}
