//! Authoring-side Rust binding generation (§20).
//!
//! Pipeline code owns reflection and emitted unit bytes. The daemon owns the
//! pinned authored reads, DSTR observations, complete generated namespace,
//! and §14 publication/recovery mechanics.

use std::collections::{BTreeMap, BTreeSet};
use std::fs::{self, File, Metadata};
use std::io::Read;
use std::path::{Component, Path, PathBuf};
use std::sync::{Arc, Mutex, MutexGuard};

use distill_build::codegen::{
    CodegenAttempt, CodegenCoordinator, CodegenFailure, CodegenPublication, CodegenPublisher,
    CodegenSnapshot, GeneratedFile, PublicationError,
};
use distill_build::query::{asset_query_result_hash, AssetQuery};
use distill_build::trace::{Observed, TraceOp};
use distill_core::id::{AssetUuid, BundleFileHash, ContentHash};
use distill_store::codegen::CodegenPublicationBasis;
use distill_store::journal::{
    CreationRecoveryOutcome, DeletionRecoveryOutcome, JournalIntentPlan, PublicationGroupKind,
    RenameAsideOutcome,
};
use distill_store::state::InputVersion;
use distill_store::Store;

use crate::callbacks::{
    CallbackInvokeError, CodegenAsset, CodegenContextError, PipelineCodegenContext,
};
use crate::coordinator::DaemonCoordinator;
use crate::lineage_repair::{unique_sibling, write_same_dir_temp};
use crate::quarantine::{QuarantineDriver, QuarantineRoot};
use crate::scanner::RootedScanner;

const GENERATED_HEADER: &str = "// @generated by distill; do not edit.\n";

pub struct CodegenService {
    enabled: bool,
    output: Option<OutputDirectory>,
    coordinator: CodegenCoordinator,
    last_attempted: Option<InputVersion>,
}

impl CodegenService {
    pub fn new(
        daemon: &DaemonCoordinator,
        output_path: impl AsRef<Path>,
        enabled: bool,
    ) -> Result<Self, String> {
        let pending_codegen = {
            let store_handle = daemon.store();
            let store = lock_store(&store_handle)?;
            store
                .unfinished_publication_groups()
                .map_err(|error| error.to_string())?
                .iter()
                .any(|group| group.kind == PublicationGroupKind::Codegen)
        };
        let output = if enabled || pending_codegen {
            Some(OutputDirectory::open(output_path.as_ref())?)
        } else {
            None
        };
        let service = Self {
            enabled,
            output,
            coordinator: CodegenCoordinator::default(),
            last_attempted: None,
        };
        if pending_codegen {
            service.recover(daemon)?;
        }
        Ok(service)
    }

    /// Run at most once for the current input version. A stale attempt is not
    /// remembered, so the coordinator loop can retry after publishing the
    /// filesystem event that made it stale.
    pub fn run(&mut self, daemon: &DaemonCoordinator) -> Result<(), String> {
        if !self.enabled {
            return Ok(());
        }
        let output = self
            .output
            .as_ref()
            .ok_or_else(|| "enabled codegen service has no output directory".to_owned())?;
        output.verify()?;

        let snapshot = daemon.pipeline_snapshot();
        let epoch = snapshot.epoch().map_err(|poison| poison.to_string())?;
        let store_handle = daemon.store();
        let basis = lock_store(&store_handle)?.input_version();
        if self.last_attempted == Some(basis) {
            return Ok(());
        }
        if epoch.codegen_descriptors().is_empty() {
            self.last_attempted = Some(basis);
            return Ok(());
        }

        let store = daemon.store();
        let scanner = daemon.scanner();
        let mut context = AuthoredCodegenContext::new(Arc::clone(&store), scanner.clone(), basis);
        let result = epoch.invoke_codegens(&mut context);
        let trace = context.trace;
        let attempt = match result {
            Ok(files) if !context.stopped => CodegenAttempt::success(basis, trace, files),
            Ok(_) => CodegenAttempt::failure(
                basis,
                trace,
                CodegenFailure::Generation("codegen context stopped after input drift".into()),
            ),
            Err(CallbackInvokeError::Rejected(failure)) => {
                CodegenAttempt::failure(basis, trace, failure)
            }
            Err(error) => {
                let _ = daemon.sync_runtime_pipeline_poison();
                self.last_attempted = Some(basis);
                return Err(error.to_string());
            }
        };
        let quarantine = daemon
            .authoring_service()
            .quarantine_snapshot()
            .with_root(output.quarantine_root())
            .map_err(|error| error.to_string())?;
        let mut world = CodegenWorld {
            store,
            scanner,
            output,
            quarantine,
        };
        let publication = self.coordinator.finish(attempt, &mut world);
        match publication {
            CodegenPublication::Requeued => Ok(()),
            CodegenPublication::Published { .. } => {
                self.last_attempted = Some(basis);
                Ok(())
            }
            CodegenPublication::Failed(failure) => {
                self.last_attempted = Some(basis);
                Err(failure.to_string())
            }
            CodegenPublication::PublicationFailed(error) => {
                self.last_attempted = Some(basis);
                Err(error.to_string())
            }
        }
    }

    fn recover(&self, daemon: &DaemonCoordinator) -> Result<(), String> {
        let output = self
            .output
            .as_ref()
            .ok_or_else(|| "codegen recovery has no output directory".to_owned())?;
        let quarantine = daemon
            .authoring_service()
            .quarantine_snapshot()
            .with_root(output.quarantine_root())
            .map_err(|error| error.to_string())?;
        let store = daemon.store();
        let mut store = lock_store(&store)?;
        let publication = quarantine
            .admit_publication(&mut store)
            .map_err(|error| error.to_string())?;
        drop(publication);
        Ok(())
    }
}

struct AuthoredCodegenContext {
    store: Arc<Mutex<Store>>,
    scanner: RootedScanner,
    basis: InputVersion,
    trace: Vec<TraceOp>,
    stopped: bool,
}

impl AuthoredCodegenContext {
    fn new(store: Arc<Mutex<Store>>, scanner: RootedScanner, basis: InputVersion) -> Self {
        Self {
            store,
            scanner,
            basis,
            trace: Vec::new(),
            stopped: false,
        }
    }

    fn stop<T>(&mut self, error: impl Into<String>) -> Result<T, CodegenContextError> {
        self.stopped = true;
        Err(CodegenContextError::Failed(error.into()))
    }

    fn check_basis(&mut self, store: &Store) -> Result<(), CodegenContextError> {
        if self.stopped {
            return Err(CodegenContextError::AttemptStopped);
        }
        if store.input_version() != self.basis {
            self.stopped = true;
            return Err(CodegenContextError::AttemptStopped);
        }
        Ok(())
    }
}

impl PipelineCodegenContext for AuthoredCodegenContext {
    fn query(&mut self, query: &AssetQuery) -> Result<Vec<AssetUuid>, CodegenContextError> {
        if self.stopped {
            return Err(CodegenContextError::AttemptStopped);
        }
        let query = match query.clone().close(None) {
            Ok(query) => query,
            Err(error) => {
                self.stopped = true;
                return Err(CodegenContextError::InvalidQuery(error));
            }
        };
        if query.terminal_type.is_some() {
            return self.stop("target-dependent terminal_type is unavailable to Rust codegen");
        }
        let store_handle = Arc::clone(&self.store);
        let result = {
            let store = store_handle.lock().map_err(|_| {
                CodegenContextError::Failed("durable store mutex is poisoned".into())
            })?;
            self.check_basis(&store)?;
            query_results(&store, &query).map_err(CodegenContextError::Failed)?
        };
        self.trace.push(TraceOp::Query {
            query: Box::new(query),
            observed: Observed::Ok(asset_query_result_hash(&result)),
        });
        Ok(result)
    }

    fn read(&mut self, asset: AssetUuid) -> Result<Option<CodegenAsset>, CodegenContextError> {
        if self.stopped {
            return Err(CodegenContextError::AttemptStopped);
        }
        let store_handle = Arc::clone(&self.store);
        let loaded = {
            let store = store_handle.lock().map_err(|_| {
                CodegenContextError::Failed("durable store mutex is poisoned".into())
            })?;
            self.check_basis(&store)?;
            load_authored_asset(&store, &self.scanner, asset)
        };
        let (observed, value) = match loaded {
            Ok(Some((hash, value))) => (Observed::Ok(Some(hash)), Some(value)),
            Ok(None) => (Observed::Ok(None), None),
            Err(error) => return self.stop(error),
        };
        self.trace.push(TraceOp::AuthoringRead { asset, observed });
        Ok(value)
    }
}

struct CodegenWorld<'a> {
    store: Arc<Mutex<Store>>,
    scanner: RootedScanner,
    output: &'a OutputDirectory,
    quarantine: QuarantineDriver,
}

impl CodegenSnapshot<InputVersion> for CodegenWorld<'_> {
    fn current_basis(&self) -> InputVersion {
        self.store
            .lock()
            .map(|store| store.input_version())
            .unwrap_or(InputVersion(u64::MAX))
    }

    fn observe(&self, op: &TraceOp) -> bool {
        let Ok(store) = self.store.lock() else {
            return false;
        };
        match op {
            TraceOp::Query { query, observed } => query_results(&store, query)
                .map(|results| Observed::Ok(asset_query_result_hash(&results)) == *observed)
                .unwrap_or(false),
            TraceOp::AuthoringRead { asset, observed } => {
                observe_authored_asset(&store, &self.scanner, *asset)
                    .map(|actual| Observed::Ok(actual) == *observed)
                    .unwrap_or(false)
            }
            _ => false,
        }
    }
}

impl CodegenPublisher<InputVersion> for CodegenWorld<'_> {
    fn publish(
        &mut self,
        attempted_basis: &InputVersion,
        files: &[GeneratedFile],
    ) -> Result<(), PublicationError> {
        self.publish_files(*attempted_basis, files)
            .map_err(PublicationError::new)
    }
}

impl CodegenWorld<'_> {
    fn publish_files(
        &mut self,
        basis: InputVersion,
        files: &[GeneratedFile],
    ) -> Result<(), String> {
        self.output.verify()?;
        let mut store = lock_store(&self.store)?;
        if store.input_version() != basis {
            return Err("codegen input version changed before publication".into());
        }

        // Admission first completes any crash-recovered Codegen basis. The
        // store lock remains held while the next complete map is prepared.
        drop(
            self.quarantine
                .admit_publication(&mut store)
                .map_err(|error| error.to_string())?,
        );
        let previous = store.codegen_outputs().map_err(|error| error.to_string())?;
        let desired = desired_namespace(files)?;
        let proposed = desired
            .iter()
            .map(|(path, bytes)| (path.clone(), ContentHash(*blake3::hash(bytes).as_bytes())))
            .collect::<BTreeMap<_, _>>();
        self.verify_preimages(&previous, &proposed)?;

        let changes = publication_changes(&previous, &desired, &proposed, &self.output.path);
        if changes.is_empty() {
            if previous != proposed {
                return Err("codegen namespace changed without a filesystem mutation".into());
            }
            return Ok(());
        }
        let mut staged = Vec::with_capacity(changes.len());
        for change in &changes {
            staged.push(
                change
                    .bytes
                    .as_deref()
                    .map(|bytes| write_same_dir_temp(&change.target, bytes))
                    .transpose()?,
            );
        }
        let plans = changes
            .iter()
            .zip(&staged)
            .map(|(change, temp)| {
                Ok(JournalIntentPlan {
                    target_path: path_text(&change.target)?,
                    temp_path: temp
                        .as_deref()
                        .map(path_text)
                        .transpose()?
                        .unwrap_or_default(),
                    conflict_path: path_text(&unique_sibling(&change.target, "conflict"))?,
                    pre_image_hash: change.preimage,
                    proposed_hash: change.proposed_hash,
                })
            })
            .collect::<Result<Vec<_>, String>>()?;
        let completion = CodegenPublicationBasis::new(basis, previous, proposed);
        let mut publication = self
            .quarantine
            .admit_publication(&mut store)
            .map_err(|error| error.to_string())?;
        let group = publication
            .record_group(PublicationGroupKind::Codegen, &completion.encode(), &plans)
            .map_err(|error| error.to_string())?;
        for (change, intent) in changes.iter().zip(&group.child_intents) {
            let installed = match (change.preimage, change.bytes.as_ref()) {
                (Some(_), Some(_)) => publication
                    .resume_group_replace(*intent, &change.target)
                    .map(|outcome| outcome == RenameAsideOutcome::Installed),
                (Some(_), None) => publication
                    .resume_group_delete(*intent, &change.target)
                    .map(|outcome| outcome == DeletionRecoveryOutcome::Deleted),
                (None, Some(_)) => publication
                    .resume_group_create(*intent)
                    .map(|outcome| outcome == CreationRecoveryOutcome::Installed),
                (None, None) => unreachable!("a generated-file change mutates one inode"),
            }
            .map_err(|error| error.to_string())?;
            if !installed {
                return Err(format!(
                    "generated file {} changed concurrently; the observed inode was preserved",
                    change.target.display()
                ));
            }
        }
        publication
            .complete_codegen_group(&group, &completion)
            .map_err(|error| error.to_string())?;
        Ok(())
    }

    fn verify_preimages(
        &self,
        previous: &BTreeMap<String, ContentHash>,
        proposed: &BTreeMap<String, ContentHash>,
    ) -> Result<(), String> {
        for (relative, expected) in previous {
            let target = self.output.path.join(relative);
            let actual = read_owned_file(&target)?;
            let actual = ContentHash(*blake3::hash(&actual).as_bytes());
            if actual != *expected {
                return Err(format!(
                    "generated file {} was edited outside distill",
                    target.display()
                ));
            }
        }
        for relative in proposed.keys() {
            if previous.contains_key(relative) {
                continue;
            }
            let target = self.output.path.join(relative);
            match fs::symlink_metadata(&target) {
                Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
                Ok(_) => {
                    return Err(format!(
                        "unowned path {} occupies the generated namespace",
                        target.display()
                    ))
                }
                Err(error) => {
                    return Err(format!(
                        "inspect generated path {}: {error}",
                        target.display()
                    ))
                }
            }
        }
        for entry in fs::read_dir(&self.output.path).map_err(|error| {
            format!(
                "enumerate generated namespace {}: {error}",
                self.output.path.display()
            )
        })? {
            let entry = entry.map_err(|error| {
                format!(
                    "enumerate generated namespace {}: {error}",
                    self.output.path.display()
                )
            })?;
            let Some(name) = entry.file_name().to_str().map(str::to_owned) else {
                continue;
            };
            let is_generated_name = name == "mod.rs" || validate_unit_path(&name).is_ok();
            if is_generated_name && !previous.contains_key(&name) && !proposed.contains_key(&name) {
                return Err(format!(
                    "unowned path {} occupies the generated namespace",
                    entry.path().display()
                ));
            }
        }
        Ok(())
    }
}

struct GeneratedChange {
    target: PathBuf,
    preimage: Option<ContentHash>,
    bytes: Option<Vec<u8>>,
    proposed_hash: ContentHash,
}

fn publication_changes(
    previous: &BTreeMap<String, ContentHash>,
    desired: &BTreeMap<String, Vec<u8>>,
    proposed: &BTreeMap<String, ContentHash>,
    output: &Path,
) -> Vec<GeneratedChange> {
    let mut paths = previous
        .keys()
        .chain(proposed.keys())
        .cloned()
        .collect::<Vec<_>>();
    paths.sort();
    paths.dedup();
    paths
        .into_iter()
        .filter_map(|path| {
            let before = previous.get(&path).copied();
            let after = proposed.get(&path).copied();
            (before != after).then(|| GeneratedChange {
                target: output.join(&path),
                preimage: before,
                bytes: desired.get(&path).cloned(),
                proposed_hash: after.unwrap_or_else(empty_hash),
            })
        })
        .collect()
}

fn desired_namespace(files: &[GeneratedFile]) -> Result<BTreeMap<String, Vec<u8>>, String> {
    let mut desired = BTreeMap::new();
    let mut modules = Vec::with_capacity(files.len());
    for file in files {
        validate_unit_path(file.relative_path())?;
        if desired
            .insert(file.relative_path().to_owned(), file.bytes().to_vec())
            .is_some()
        {
            return Err(format!(
                "duplicate generated path {} reached the publisher",
                file.relative_path()
            ));
        }
        modules.push(file.relative_path().trim_end_matches(".rs").to_owned());
    }
    modules.sort();
    let mut module = String::from(GENERATED_HEADER);
    for name in modules {
        module.push_str("pub mod ");
        module.push_str(&name);
        module.push_str(";\n");
    }
    desired.insert("mod.rs".into(), module.into_bytes());
    Ok(desired)
}

fn validate_unit_path(path: &str) -> Result<(), String> {
    let Some(hex) = path
        .strip_prefix("sp_")
        .and_then(|path| path.strip_suffix(".rs"))
    else {
        return Err(format!("invalid generated unit path {path:?}"));
    };
    if hex.len() != 32
        || !hex
            .as_bytes()
            .iter()
            .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(byte))
    {
        return Err(format!("invalid generated unit path {path:?}"));
    }
    Ok(())
}

fn query_results(store: &Store, query: &AssetQuery) -> Result<Vec<AssetUuid>, String> {
    if query.terminal_type.is_some() {
        return Err("target-dependent terminal_type is unavailable to Rust codegen".into());
    }
    let tagged = query
        .tag
        .as_ref()
        .map(|tag| {
            store
                .assets_by_tag_value(&tag.tag, tag.value.as_deref())
                .map(|assets| assets.into_iter().collect::<BTreeSet<_>>())
        })
        .transpose()
        .map_err(|error| error.to_string())?;
    let bundles = store
        .all_bundles()
        .map_err(|error| error.to_string())?
        .into_iter()
        .map(|bundle| (bundle.bundle, bundle.path))
        .collect::<BTreeMap<_, _>>();
    let glob = query
        .path_glob
        .as_ref()
        .map(|pattern| {
            globset::Glob::new(pattern)
                .map(|glob| glob.compile_matcher())
                .map_err(|error| error.to_string())
        })
        .transpose()?;
    let mut results = Vec::new();
    for asset in store.all_asset_ids().map_err(|error| error.to_string())? {
        let Some(entry) = store.entry(asset).map_err(|error| error.to_string())? else {
            continue;
        };
        if entry.authoring_only
            || query.uuid.is_some_and(|wanted| wanted != asset)
            || query
                .bundle_uuid
                .is_some_and(|wanted| wanted != entry.bundle)
            || query
                .local_id
                .as_ref()
                .is_some_and(|wanted| wanted != &entry.local_id)
            || query
                .authored_type
                .is_some_and(|wanted| wanted != entry.type_uuid)
            || tagged
                .as_ref()
                .is_some_and(|tagged| !tagged.contains(&asset))
        {
            continue;
        }
        let path = bundles
            .get(&entry.bundle)
            .ok_or_else(|| format!("asset {asset} has no owning bundle row"))?;
        if query
            .bundle_path
            .as_ref()
            .is_some_and(|wanted| wanted != path)
            || query
                .path_prefix
                .as_ref()
                .is_some_and(|prefix| !path.starts_with(prefix))
            || glob.as_ref().is_some_and(|glob| !glob.is_match(path))
        {
            continue;
        }
        results.push(asset);
    }
    results.sort_unstable();
    results.dedup();
    Ok(results)
}

fn load_authored_asset(
    store: &Store,
    scanner: &RootedScanner,
    asset: AssetUuid,
) -> Result<Option<(BundleFileHash, CodegenAsset)>, String> {
    let Some(entry) = store.entry(asset).map_err(|error| error.to_string())? else {
        return Ok(None);
    };
    let bundle_meta = store
        .bundle(entry.bundle)
        .map_err(|error| error.to_string())?
        .ok_or_else(|| format!("asset {asset} has no owning bundle row"))?;
    let root = store
        .root_name(bundle_meta.root)
        .map_err(|error| error.to_string())?
        .ok_or_else(|| format!("bundle {} has no root identity", entry.bundle))?;
    let path = scanner
        .physical_path(&root, &bundle_meta.path)
        .map_err(|error| error.to_string())?;
    let bytes = scanner
        .read_identity_checked(&path)
        .map_err(|error| error.to_string())?;
    let hash = BundleFileHash::of_observed_bytes(&bytes);
    if hash.0 != bundle_meta.content_hash.0 {
        return Err(format!(
            "bundle {} changed before its watcher event was published",
            path.display()
        ));
    }
    let bundle = distill_bundle::parse_bundle(&bytes).map_err(|error| error.to_string())?;
    let decoded = bundle
        .assets
        .get(&entry.local_id)
        .ok_or_else(|| format!("asset {asset} is absent from its owning bundle bytes"))?;
    if decoded.uuid != asset || decoded.type_uuid != entry.type_uuid {
        return Err(format!(
            "asset {asset} disagrees with its durable namespace row"
        ));
    }
    Ok(Some((
        hash,
        CodegenAsset {
            asset,
            type_uuid: decoded.type_uuid,
            value: decoded.data.clone(),
        },
    )))
}

fn observe_authored_asset(
    store: &Store,
    scanner: &RootedScanner,
    asset: AssetUuid,
) -> Result<Option<BundleFileHash>, String> {
    load_authored_asset(store, scanner, asset).map(|loaded| loaded.map(|(hash, _)| hash))
}

#[derive(Debug)]
struct OutputDirectory {
    path: PathBuf,
    handle: File,
    identity: FileIdentity,
}

impl OutputDirectory {
    fn open(path: &Path) -> Result<Self, String> {
        ensure_real_directory_tree(path)?;
        let metadata = fs::symlink_metadata(path)
            .map_err(|error| format!("inspect codegen output {}: {error}", path.display()))?;
        if metadata.file_type().is_symlink() || !metadata.is_dir() {
            return Err(format!(
                "codegen output {} is not a real directory",
                path.display()
            ));
        }
        let handle = File::open(path)
            .map_err(|error| format!("open codegen output {}: {error}", path.display()))?;
        let identity = file_identity(
            &handle
                .metadata()
                .map_err(|error| format!("inspect codegen output handle: {error}"))?,
        );
        Ok(Self {
            path: path.to_path_buf(),
            handle,
            identity,
        })
    }

    fn verify(&self) -> Result<(), String> {
        let metadata = fs::symlink_metadata(&self.path).map_err(|error| {
            format!("reinspect codegen output {}: {error}", self.path.display())
        })?;
        if metadata.file_type().is_symlink()
            || !metadata.is_dir()
            || file_identity(&metadata) != self.identity
            || file_identity(
                &self
                    .handle
                    .metadata()
                    .map_err(|error| format!("reinspect codegen output handle: {error}"))?,
            ) != self.identity
        {
            return Err(format!(
                "codegen output directory {} changed identity",
                self.path.display()
            ));
        }
        Ok(())
    }

    fn quarantine_root(&self) -> QuarantineRoot {
        QuarantineRoot::new(&self.path, self.path.join(".distill-quarantine"))
    }
}

fn ensure_real_directory_tree(path: &Path) -> Result<(), String> {
    if !path.is_absolute() {
        return Err(format!(
            "codegen output path must be absolute: {}",
            path.display()
        ));
    }
    if path
        .components()
        .any(|component| matches!(component, Component::ParentDir))
    {
        return Err("codegen output path contains a parent component".into());
    }
    // The configured absolute path is opened once and its final directory
    // itself must not be a symlink. Platform aliases in ancestors (for
    // example macOS /var -> /private/var) are outside the generated namespace;
    // subsequent publication is fenced against that retained identity.
    match fs::symlink_metadata(path) {
        Ok(_) => {}
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => fs::create_dir_all(path)
            .map_err(|error| format!("create codegen output {}: {error}", path.display()))?,
        Err(error) => {
            return Err(format!(
                "inspect codegen output {}: {error}",
                path.display()
            ))
        }
    }
    Ok(())
}

fn read_owned_file(path: &Path) -> Result<Vec<u8>, String> {
    let before = fs::symlink_metadata(path)
        .map_err(|error| format!("inspect generated file {}: {error}", path.display()))?;
    if before.file_type().is_symlink() || !before.is_file() {
        return Err(format!(
            "generated path {} is not a real regular file",
            path.display()
        ));
    }
    let mut file = File::open(path)
        .map_err(|error| format!("open generated file {}: {error}", path.display()))?;
    let opened = file
        .metadata()
        .map_err(|error| format!("inspect generated file handle {}: {error}", path.display()))?;
    let mut bytes = Vec::new();
    file.read_to_end(&mut bytes)
        .map_err(|error| format!("read generated file {}: {error}", path.display()))?;
    let after = fs::symlink_metadata(path)
        .map_err(|error| format!("reinspect generated file {}: {error}", path.display()))?;
    if after.file_type().is_symlink()
        || file_identity(&before) != file_identity(&opened)
        || file_identity(&after) != file_identity(&opened)
        || opened.len() != bytes.len() as u64
    {
        return Err(format!(
            "generated file {} changed identity while it was read",
            path.display()
        ));
    }
    Ok(bytes)
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum FileIdentity {
    #[cfg(unix)]
    Unix { device: u64, inode: u64 },
    #[cfg(windows)]
    Windows { volume: u64, index: u64 },
    #[cfg(not(any(unix, windows)))]
    Portable { len: u64, modified_nanos: u128 },
}

#[cfg(unix)]
fn file_identity(metadata: &Metadata) -> FileIdentity {
    use std::os::unix::fs::MetadataExt;
    FileIdentity::Unix {
        device: metadata.dev(),
        inode: metadata.ino(),
    }
}

#[cfg(windows)]
fn file_identity(metadata: &Metadata) -> FileIdentity {
    use std::os::windows::fs::MetadataExt;
    FileIdentity::Windows {
        volume: u64::from(metadata.volume_serial_number().unwrap_or(0)),
        index: metadata.file_index().unwrap_or(0),
    }
}

#[cfg(not(any(unix, windows)))]
fn file_identity(metadata: &Metadata) -> FileIdentity {
    let modified_nanos = metadata
        .modified()
        .ok()
        .and_then(|time| time.duration_since(std::time::UNIX_EPOCH).ok())
        .map_or(0, |duration| duration.as_nanos());
    FileIdentity::Portable {
        len: metadata.len(),
        modified_nanos,
    }
}

fn empty_hash() -> ContentHash {
    ContentHash(*blake3::hash(b"").as_bytes())
}

fn path_text(path: &Path) -> Result<String, String> {
    path.to_str()
        .map(str::to_owned)
        .ok_or_else(|| format!("journal path is not lossless UTF-8: {}", path.display()))
}

fn lock_store(store: &Arc<Mutex<Store>>) -> Result<MutexGuard<'_, Store>, String> {
    store
        .lock()
        .map_err(|_| "durable store mutex is poisoned".to_owned())
}

#[cfg(test)]
mod tests {
    use super::*;
    use distill_bundle::{AssetEntry, Bundle, EntryLineageV1};
    use distill_core::id::{BundleUuid, LogicalHash, TypeUuid};
    use distill_core::lineage::{lineage_chain_digest, AcceptedSchemaEpoch, LineageStamp};
    use distill_json::AuthoredValue;
    use distill_schema::ngp_schema::{node_hash, LogicalSchema, PrimitiveKind, SchemaNode};
    use distill_store::bundles::{AssetRecord, BundleMeta};
    use distill_store::StoreConfig;

    fn publication_world(
        temp: &tempfile::TempDir,
    ) -> (
        Arc<Mutex<Store>>,
        RootedScanner,
        OutputDirectory,
        QuarantineDriver,
    ) {
        let assets = temp.path().join("assets");
        let output = temp.path().join("generated");
        fs::create_dir(&assets).unwrap();
        let scanner = RootedScanner::new([crate::scanner::AssetRoot::new(
            "main",
            &assets,
            assets.join(".distill-displaced"),
        )])
        .unwrap();
        let output = OutputDirectory::open(&output).unwrap();
        let quarantine = QuarantineDriver::new([output.quarantine_root()]).unwrap();
        let store = Arc::new(Mutex::new(
            Store::open(StoreConfig::new(temp.path().join("state"))).unwrap(),
        ));
        (store, scanner, output, quarantine)
    }

    fn generated(asset: u8, bytes: &[u8]) -> GeneratedFile {
        GeneratedFile::new(AssetUuid([asset; 16]), bytes.to_vec())
    }

    #[test]
    fn complete_namespace_publishes_diffs_and_skips_unchanged_bytes() {
        let temp = tempfile::tempdir().unwrap();
        let (store, scanner, output, quarantine) = publication_world(&temp);
        let basis = store.lock().unwrap().input_version();
        let first = generated(1, b"pub const VALUE: u8 = 1;\n");
        let second = generated(2, b"pub const VALUE: u8 = 2;\n");
        let first_path = output.path.join(first.relative_path());
        let second_path = output.path.join(second.relative_path());
        let mut world = CodegenWorld {
            store: Arc::clone(&store),
            scanner,
            output: &output,
            quarantine,
        };

        world
            .publish_files(basis, &[first.clone(), second.clone()])
            .unwrap();
        let first_memo = store.lock().unwrap().memo_seq();
        assert_eq!(fs::read(&first_path).unwrap(), first.bytes());
        assert_eq!(fs::read(&second_path).unwrap(), second.bytes());
        assert_eq!(
            fs::read_to_string(output.path.join("mod.rs")).unwrap(),
            concat!(
                "// @generated by distill; do not edit.\n",
                "pub mod sp_01010101010101010101010101010101;\n",
                "pub mod sp_02020202020202020202020202020202;\n"
            )
        );

        world
            .publish_files(basis, &[first.clone(), second])
            .unwrap();
        assert_eq!(store.lock().unwrap().memo_seq(), first_memo);

        world.publish_files(basis, &[first]).unwrap();
        assert!(first_path.exists());
        assert!(!second_path.exists());
        assert_eq!(store.lock().unwrap().codegen_outputs().unwrap().len(), 2);
    }

    #[test]
    fn hand_edits_and_unknown_generated_names_are_never_overwritten() {
        let temp = tempfile::tempdir().unwrap();
        let (store, scanner, output, quarantine) = publication_world(&temp);
        let basis = store.lock().unwrap().input_version();
        let file = generated(3, b"original\n");
        let target = output.path.join(file.relative_path());
        let mut world = CodegenWorld {
            store: Arc::clone(&store),
            scanner,
            output: &output,
            quarantine,
        };
        world.publish_files(basis, &[file]).unwrap();
        let expected = store.lock().unwrap().codegen_outputs().unwrap();

        fs::write(&target, b"human edit\n").unwrap();
        assert!(world
            .publish_files(basis, &[generated(3, b"replacement\n")])
            .unwrap_err()
            .contains("edited outside distill"));
        assert_eq!(fs::read(&target).unwrap(), b"human edit\n");
        assert_eq!(store.lock().unwrap().codegen_outputs().unwrap(), expected);

        fs::write(&target, b"original\n").unwrap();
        fs::write(
            output.path.join("sp_09090909090909090909090909090909.rs"),
            b"unowned\n",
        )
        .unwrap();
        assert!(world
            .publish_files(basis, &[generated(3, b"original\n")])
            .unwrap_err()
            .contains("unowned path"));
    }

    #[test]
    fn authored_context_records_query_and_exact_bundle_read() {
        let temp = tempfile::tempdir().unwrap();
        let assets = temp.path().join("assets");
        fs::create_dir(&assets).unwrap();
        let scanner = RootedScanner::new([crate::scanner::AssetRoot::new(
            "main",
            &assets,
            assets.join(".distill-displaced"),
        )])
        .unwrap();
        let type_uuid = TypeUuid([7; 16]);
        let schema = LogicalSchema {
            root: SchemaNode::Primitive(PrimitiveKind::U8),
        };
        let logical_hash = node_hash(&schema.root).unwrap();
        let epochs = vec![AcceptedSchemaEpoch {
            digest: logical_hash,
            forward_parent: None,
        }];
        let asset = AssetUuid([8; 16]);
        let bundle_uuid = BundleUuid([9; 16]);
        let bytes = distill_bundle::write_bundle(&Bundle {
            format_version: 1,
            uuid: bundle_uuid,
            primary: Some("shader".into()),
            schemas: BTreeMap::from([(logical_hash, schema)]),
            assets: BTreeMap::from([(
                "shader".into(),
                AssetEntry {
                    uuid: asset,
                    type_uuid,
                    schema_hash: logical_hash,
                    lineage: EntryLineageV1::Manifest(LineageStamp {
                        chain: lineage_chain_digest(type_uuid, &epochs, 0),
                        epochs,
                        cursor: 0,
                    }),
                    authoring_only: false,
                    data: AuthoredValue::UInt(7),
                },
            )]),
        })
        .unwrap();
        fs::write(assets.join("shader.bundle"), &bytes).unwrap();
        let store = Arc::new(Mutex::new(
            Store::open(StoreConfig::new(temp.path().join("state"))).unwrap(),
        ));
        let basis = {
            let mut store = store.lock().unwrap();
            let (root, _) = store
                .input_transaction(|transaction| {
                    let root = transaction.intern_root("main")?;
                    transaction.upsert_bundle(&BundleMeta {
                        bundle: bundle_uuid,
                        root,
                        path: "shader.bundle".into(),
                        format_version: 1,
                        content_hash: ContentHash(*blake3::hash(&bytes).as_bytes()),
                        origin: None,
                    })?;
                    transaction.upsert_asset(&AssetRecord {
                        asset,
                        bundle: bundle_uuid,
                        local_id: "shader".into(),
                        type_uuid,
                        logical_hash: LogicalHash(logical_hash.0),
                        authoring_only: false,
                        tags: BTreeMap::new(),
                    })?;
                    Ok(root)
                })
                .unwrap();
            assert_eq!(root.0, 1);
            store.input_version()
        };
        let mut context = AuthoredCodegenContext::new(Arc::clone(&store), scanner.clone(), basis);
        let results = context
            .query(&AssetQuery {
                authored_type: Some(type_uuid),
                ..AssetQuery::default()
            })
            .unwrap();
        assert_eq!(results, [asset]);
        assert_eq!(
            context.read(asset).unwrap().unwrap().value,
            AuthoredValue::UInt(7)
        );
        assert!(matches!(context.trace[0], TraceOp::Query { .. }));
        assert!(matches!(
            context.trace[1],
            TraceOp::AuthoringRead {
                observed: Observed::Ok(Some(_)),
                ..
            }
        ));

        fs::write(assets.join("shader.bundle"), b"concurrent edit").unwrap();
        let output = OutputDirectory::open(&temp.path().join("generated")).unwrap();
        let world = CodegenWorld {
            store,
            scanner,
            output: &output,
            quarantine: QuarantineDriver::new([output.quarantine_root()]).unwrap(),
        };
        assert!(!world.observe(&context.trace[1]));
    }

    #[cfg(unix)]
    #[test]
    fn output_root_symlinks_are_rejected() {
        use std::os::unix::fs::symlink;

        let temp = tempfile::tempdir().unwrap();
        let real = temp.path().join("real");
        let alias = temp.path().join("alias");
        fs::create_dir(&real).unwrap();
        symlink(&real, &alias).unwrap();
        assert!(OutputDirectory::open(&alias)
            .unwrap_err()
            .contains("not a real directory"));
    }
}
