//! Authoring-side Rust binding generation (§20).
//!
//! Pipeline code owns reflection and emitted unit bytes. The daemon owns the
//! pinned authored reads, DSTR observations, complete generated namespace,
//! and §14 publication/recovery mechanics.

use std::collections::{BTreeMap, BTreeSet};
#[cfg(unix)]
use std::ffi::{CStr, CString};
use std::ffi::{OsStr, OsString};
use std::fs::{self, File, Metadata};
use std::io::{Read, Write};
use std::path::{Component, Path, PathBuf};
use std::sync::{Arc, Mutex, MutexGuard};

use distill_build::codegen::{
    CodegenAttempt, CodegenCoordinator, CodegenFailure, CodegenPublication, CodegenPublisher,
    CodegenSnapshot, GeneratedFile, PublicationError,
};
use distill_build::query::{asset_query_result_hash, AssetQuery};
use distill_build::trace::{Observed, TraceOp};
use distill_core::id::{AssetUuid, BundleFileHash, ContentHash};
use distill_store::codegen::CodegenPublicationBasis;
use distill_store::journal::{
    CreationRecoveryOutcome, DeletionRecoveryOutcome, JournalFilesystem, JournalIntentPlan,
    NoReplaceMoveError, PublicationGroupKind, RenameAsideOutcome,
};
use distill_store::state::InputVersion;
use distill_store::{Store, StoreError};

use crate::callbacks::{
    CallbackInvokeError, CodegenAsset, CodegenContextError, PipelineCodegenContext,
};
use crate::coordinator::DaemonCoordinator;
use crate::lineage_repair::unique_sibling;
use crate::quarantine::{QuarantineDriver, QuarantineRoot};
use crate::scanner::RootedScanner;

const GENERATED_HEADER: &str = "// @generated by distill; do not edit.\n";

pub struct CodegenService {
    enabled: bool,
    output: Option<OutputDirectory>,
    coordinator: CodegenCoordinator,
    last_attempted: Option<InputVersion>,
}

impl CodegenService {
    pub fn new(
        daemon: &DaemonCoordinator,
        output_path: impl AsRef<Path>,
        enabled: bool,
    ) -> Result<Self, String> {
        let pending_codegen = {
            let store_handle = daemon.store();
            let store = lock_store(&store_handle)?;
            store
                .unfinished_publication_groups()
                .map_err(|error| error.to_string())?
                .iter()
                .any(|group| group.kind == PublicationGroupKind::Codegen)
        };
        let output = if enabled || pending_codegen {
            Some(OutputDirectory::open(output_path.as_ref())?)
        } else {
            None
        };
        let service = Self {
            enabled,
            output,
            coordinator: CodegenCoordinator::default(),
            last_attempted: None,
        };
        if pending_codegen {
            service.recover(daemon)?;
        }
        Ok(service)
    }

    /// Run at most once for the current input version. A stale attempt is not
    /// remembered, so the coordinator loop can retry after publishing the
    /// filesystem event that made it stale.
    pub fn run(&mut self, daemon: &DaemonCoordinator) -> Result<(), String> {
        if !self.enabled {
            return Ok(());
        }
        let output = self
            .output
            .as_ref()
            .ok_or_else(|| "enabled codegen service has no output directory".to_owned())?;
        output.verify()?;

        let snapshot = daemon.pipeline_snapshot();
        let epoch = snapshot.epoch().map_err(|poison| poison.to_string())?;
        let store_handle = daemon.store();
        let basis = lock_store(&store_handle)?.input_version();
        if self.last_attempted == Some(basis) {
            return Ok(());
        }
        if epoch.codegen_descriptors().is_empty() {
            self.last_attempted = Some(basis);
            return Ok(());
        }

        let store = daemon.store();
        let scanner = daemon.scanner();
        let mut context = AuthoredCodegenContext::new(Arc::clone(&store), scanner.clone(), basis);
        let result = epoch.invoke_codegens(&mut context);
        let trace = context.trace;
        let attempt = match result {
            Ok(files) if !context.stopped => CodegenAttempt::success(basis, trace, files),
            Ok(_) => CodegenAttempt::failure(
                basis,
                trace,
                CodegenFailure::Generation("codegen context stopped after input drift".into()),
            ),
            Err(CallbackInvokeError::Rejected(failure)) => {
                CodegenAttempt::failure(basis, trace, failure)
            }
            Err(error) => {
                let _ = daemon.sync_runtime_pipeline_poison();
                self.last_attempted = Some(basis);
                return Err(error.to_string());
            }
        };
        let quarantine = daemon
            .authoring_service()
            .quarantine_snapshot()
            .with_root(output.quarantine_root())
            .map_err(|error| error.to_string())?;
        let mut world = CodegenWorld {
            store,
            scanner,
            output,
            quarantine,
        };
        let publication = self.coordinator.finish(attempt, &mut world);
        match publication {
            CodegenPublication::Requeued => Ok(()),
            CodegenPublication::Published { .. } => {
                self.last_attempted = Some(basis);
                Ok(())
            }
            CodegenPublication::Failed(failure) => {
                self.last_attempted = Some(basis);
                Err(failure.to_string())
            }
            CodegenPublication::PublicationFailed(error) => Err(error.to_string()),
        }
    }

    fn recover(&self, daemon: &DaemonCoordinator) -> Result<(), String> {
        let output = self
            .output
            .as_ref()
            .ok_or_else(|| "codegen recovery has no output directory".to_owned())?;
        let quarantine = daemon
            .authoring_service()
            .quarantine_snapshot()
            .with_root(output.quarantine_root())
            .map_err(|error| error.to_string())?;
        let store = daemon.store();
        let mut store = lock_store(&store)?;
        let mut filesystem = OutputJournalFilesystem::new(output);
        let publication = quarantine
            .admit_codegen_publication(&mut store, &mut filesystem)
            .map_err(|error| error.to_string())?;
        drop(publication);
        Ok(())
    }
}

struct AuthoredCodegenContext {
    store: Arc<Mutex<Store>>,
    scanner: RootedScanner,
    basis: InputVersion,
    trace: Vec<TraceOp>,
    stopped: bool,
}

impl AuthoredCodegenContext {
    fn new(store: Arc<Mutex<Store>>, scanner: RootedScanner, basis: InputVersion) -> Self {
        Self {
            store,
            scanner,
            basis,
            trace: Vec::new(),
            stopped: false,
        }
    }

    fn stop<T>(&mut self, error: impl Into<String>) -> Result<T, CodegenContextError> {
        self.stopped = true;
        Err(CodegenContextError::Failed(error.into()))
    }

    fn check_basis(&mut self, store: &Store) -> Result<(), CodegenContextError> {
        if self.stopped {
            return Err(CodegenContextError::AttemptStopped);
        }
        if store.input_version() != self.basis {
            self.stopped = true;
            return Err(CodegenContextError::AttemptStopped);
        }
        Ok(())
    }
}

impl PipelineCodegenContext for AuthoredCodegenContext {
    fn query(&mut self, query: &AssetQuery) -> Result<Vec<AssetUuid>, CodegenContextError> {
        if self.stopped {
            return Err(CodegenContextError::AttemptStopped);
        }
        let query = match query.clone().close(None) {
            Ok(query) => query,
            Err(error) => {
                self.stopped = true;
                return Err(CodegenContextError::InvalidQuery(error));
            }
        };
        if query.terminal_type.is_some() {
            return self.stop("target-dependent terminal_type is unavailable to Rust codegen");
        }
        let store_handle = Arc::clone(&self.store);
        let result = {
            let store = store_handle.lock().map_err(|_| {
                CodegenContextError::Failed("durable store mutex is poisoned".into())
            })?;
            self.check_basis(&store)?;
            query_results(&store, &query).map_err(CodegenContextError::Failed)?
        };
        self.trace.push(TraceOp::Query {
            query: Box::new(query),
            observed: Observed::Ok(asset_query_result_hash(&result)),
        });
        Ok(result)
    }

    fn read(&mut self, asset: AssetUuid) -> Result<Option<CodegenAsset>, CodegenContextError> {
        if self.stopped {
            return Err(CodegenContextError::AttemptStopped);
        }
        let store_handle = Arc::clone(&self.store);
        let loaded = {
            let store = store_handle.lock().map_err(|_| {
                CodegenContextError::Failed("durable store mutex is poisoned".into())
            })?;
            self.check_basis(&store)?;
            load_authored_asset(&store, &self.scanner, asset)
        };
        let (observed, value) = match loaded {
            Ok(Some((hash, value))) => (Observed::Ok(Some(hash)), Some(value)),
            Ok(None) => (Observed::Ok(None), None),
            Err(error) => return self.stop(error),
        };
        self.trace.push(TraceOp::AuthoringRead { asset, observed });
        Ok(value)
    }
}

struct CodegenWorld<'a> {
    store: Arc<Mutex<Store>>,
    scanner: RootedScanner,
    output: &'a OutputDirectory,
    quarantine: QuarantineDriver,
}

impl CodegenSnapshot<InputVersion> for CodegenWorld<'_> {
    fn current_basis(&self) -> InputVersion {
        self.store
            .lock()
            .map(|store| store.input_version())
            .unwrap_or(InputVersion(u64::MAX))
    }

    fn observe(&self, op: &TraceOp) -> bool {
        let Ok(store) = self.store.lock() else {
            return false;
        };
        match op {
            TraceOp::Query { query, observed } => query_results(&store, query)
                .map(|results| Observed::Ok(asset_query_result_hash(&results)) == *observed)
                .unwrap_or(false),
            TraceOp::AuthoringRead { asset, observed } => {
                observe_authored_asset(&store, &self.scanner, *asset)
                    .map(|actual| Observed::Ok(actual) == *observed)
                    .unwrap_or(false)
            }
            _ => false,
        }
    }
}

impl CodegenPublisher<InputVersion> for CodegenWorld<'_> {
    fn publish(
        &mut self,
        attempted_basis: &InputVersion,
        files: &[GeneratedFile],
    ) -> Result<(), PublicationError> {
        self.publish_files(*attempted_basis, files)
            .map_err(PublicationError::new)
    }
}

impl CodegenWorld<'_> {
    fn publish_files(
        &mut self,
        basis: InputVersion,
        files: &[GeneratedFile],
    ) -> Result<(), String> {
        self.output.verify()?;
        let mut filesystem = OutputJournalFilesystem::new(self.output);
        let mut store = lock_store(&self.store)?;
        if store.input_version() != basis {
            return Err("codegen input version changed before publication".into());
        }

        // Admission first completes any crash-recovered Codegen basis. The
        // store lock remains held while the next complete map is prepared.
        drop(
            self.quarantine
                .admit_codegen_publication(&mut store, &mut filesystem)
                .map_err(|error| error.to_string())?,
        );
        let previous = store.codegen_outputs().map_err(|error| error.to_string())?;
        let desired = desired_namespace(files)?;
        let proposed = desired
            .iter()
            .map(|(path, bytes)| (path.clone(), ContentHash(*blake3::hash(bytes).as_bytes())))
            .collect::<BTreeMap<_, _>>();
        self.verify_preimages(&previous, &proposed)?;

        let changes = publication_changes(&previous, &desired, &proposed, &self.output.path);
        if changes.is_empty() {
            if previous != proposed {
                return Err("codegen namespace changed without a filesystem mutation".into());
            }
            return Ok(());
        }
        let mut staged = Vec::with_capacity(changes.len());
        for change in &changes {
            staged.push(
                change
                    .bytes
                    .as_deref()
                    .map(|bytes| self.output.write_same_dir_temp(&change.target, bytes))
                    .transpose()?,
            );
        }
        let plans = changes
            .iter()
            .zip(&staged)
            .map(|(change, temp)| {
                Ok(JournalIntentPlan {
                    target_path: path_text(&change.target)?,
                    temp_path: temp
                        .as_deref()
                        .map(path_text)
                        .transpose()?
                        .unwrap_or_default(),
                    conflict_path: path_text(&unique_sibling(&change.target, "conflict"))?,
                    pre_image_hash: change.preimage,
                    proposed_hash: change.proposed_hash,
                })
            })
            .collect::<Result<Vec<_>, String>>()?;
        let completion = CodegenPublicationBasis::new(basis, previous, proposed);
        let mut publication = self
            .quarantine
            .admit_codegen_publication(&mut store, &mut filesystem)
            .map_err(|error| error.to_string())?;
        let group = publication
            .record_group(PublicationGroupKind::Codegen, &completion.encode(), &plans)
            .map_err(|error| error.to_string())?;
        for (change, intent) in changes.iter().zip(&group.child_intents) {
            let installed = match (change.preimage, change.bytes.as_ref()) {
                (Some(_), Some(_)) => publication
                    .resume_group_replace(*intent, &change.target)
                    .map(|outcome| outcome == RenameAsideOutcome::Installed),
                (Some(_), None) => publication
                    .resume_group_delete(*intent, &change.target)
                    .map(|outcome| outcome == DeletionRecoveryOutcome::Deleted),
                (None, Some(_)) => publication
                    .resume_group_create(*intent)
                    .map(|outcome| outcome == CreationRecoveryOutcome::Installed),
                (None, None) => unreachable!("a generated-file change mutates one inode"),
            }
            .map_err(|error| error.to_string())?;
            if !installed {
                return Err(format!(
                    "generated file {} changed concurrently; the observed inode was preserved",
                    change.target.display()
                ));
            }
        }
        publication
            .complete_codegen_group(&group, &completion)
            .map_err(|error| error.to_string())?;
        Ok(())
    }

    fn verify_preimages(
        &self,
        previous: &BTreeMap<String, ContentHash>,
        proposed: &BTreeMap<String, ContentHash>,
    ) -> Result<(), String> {
        for (relative, expected) in previous {
            let target = self.output.path.join(relative);
            let actual = self.output.read_owned_file(&target)?;
            let actual = ContentHash(*blake3::hash(&actual).as_bytes());
            if actual != *expected {
                return Err(format!(
                    "generated file {} was edited outside distill",
                    target.display()
                ));
            }
        }
        for relative in proposed.keys() {
            if previous.contains_key(relative) {
                continue;
            }
            let target = self.output.path.join(relative);
            if self.output.entry_exists(&target)? {
                return Err(format!(
                    "unowned path {} occupies the generated namespace",
                    target.display()
                ));
            }
        }
        for entry in self.output.entry_names()? {
            let Some(name) = entry.to_str().map(str::to_owned) else {
                continue;
            };
            let is_generated_name = name == "mod.rs" || validate_unit_path(&name).is_ok();
            if is_generated_name && !previous.contains_key(&name) && !proposed.contains_key(&name) {
                return Err(format!(
                    "unowned path {} occupies the generated namespace",
                    self.output.path.join(entry).display()
                ));
            }
        }
        Ok(())
    }
}

struct GeneratedChange {
    target: PathBuf,
    preimage: Option<ContentHash>,
    bytes: Option<Vec<u8>>,
    proposed_hash: ContentHash,
}

fn publication_changes(
    previous: &BTreeMap<String, ContentHash>,
    desired: &BTreeMap<String, Vec<u8>>,
    proposed: &BTreeMap<String, ContentHash>,
    output: &Path,
) -> Vec<GeneratedChange> {
    let mut paths = previous
        .keys()
        .chain(proposed.keys())
        .cloned()
        .collect::<Vec<_>>();
    paths.sort();
    paths.dedup();
    paths
        .into_iter()
        .filter_map(|path| {
            let before = previous.get(&path).copied();
            let after = proposed.get(&path).copied();
            (before != after).then(|| GeneratedChange {
                target: output.join(&path),
                preimage: before,
                bytes: desired.get(&path).cloned(),
                proposed_hash: after.unwrap_or_else(empty_hash),
            })
        })
        .collect()
}

fn desired_namespace(files: &[GeneratedFile]) -> Result<BTreeMap<String, Vec<u8>>, String> {
    let mut desired = BTreeMap::new();
    let mut modules = Vec::with_capacity(files.len());
    for file in files {
        validate_unit_path(file.relative_path())?;
        if desired
            .insert(file.relative_path().to_owned(), file.bytes().to_vec())
            .is_some()
        {
            return Err(format!(
                "duplicate generated path {} reached the publisher",
                file.relative_path()
            ));
        }
        modules.push(file.relative_path().trim_end_matches(".rs").to_owned());
    }
    modules.sort();
    let mut module = String::from(GENERATED_HEADER);
    for name in modules {
        module.push_str("pub mod ");
        module.push_str(&name);
        module.push_str(";\n");
    }
    desired.insert("mod.rs".into(), module.into_bytes());
    Ok(desired)
}

fn validate_unit_path(path: &str) -> Result<(), String> {
    let Some(hex) = path
        .strip_prefix("sp_")
        .and_then(|path| path.strip_suffix(".rs"))
    else {
        return Err(format!("invalid generated unit path {path:?}"));
    };
    if hex.len() != 32
        || !hex
            .as_bytes()
            .iter()
            .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(byte))
    {
        return Err(format!("invalid generated unit path {path:?}"));
    }
    Ok(())
}

fn query_results(store: &Store, query: &AssetQuery) -> Result<Vec<AssetUuid>, String> {
    if query.terminal_type.is_some() {
        return Err("target-dependent terminal_type is unavailable to Rust codegen".into());
    }
    let tagged = query
        .tag
        .as_ref()
        .map(|tag| {
            store
                .assets_by_tag_value(&tag.tag, tag.value.as_deref())
                .map(|assets| assets.into_iter().collect::<BTreeSet<_>>())
        })
        .transpose()
        .map_err(|error| error.to_string())?;
    let bundles = store
        .all_bundles()
        .map_err(|error| error.to_string())?
        .into_iter()
        .map(|bundle| (bundle.bundle, bundle.path))
        .collect::<BTreeMap<_, _>>();
    let glob = query
        .path_glob
        .as_ref()
        .map(|pattern| {
            globset::Glob::new(pattern)
                .map(|glob| glob.compile_matcher())
                .map_err(|error| error.to_string())
        })
        .transpose()?;
    let mut results = Vec::new();
    for asset in store.all_asset_ids().map_err(|error| error.to_string())? {
        let Some(entry) = store.entry(asset).map_err(|error| error.to_string())? else {
            continue;
        };
        if entry.authoring_only
            || query.uuid.is_some_and(|wanted| wanted != asset)
            || query
                .bundle_uuid
                .is_some_and(|wanted| wanted != entry.bundle)
            || query
                .local_id
                .as_ref()
                .is_some_and(|wanted| wanted != &entry.local_id)
            || query
                .authored_type
                .is_some_and(|wanted| wanted != entry.type_uuid)
            || tagged
                .as_ref()
                .is_some_and(|tagged| !tagged.contains(&asset))
        {
            continue;
        }
        let path = bundles
            .get(&entry.bundle)
            .ok_or_else(|| format!("asset {asset} has no owning bundle row"))?;
        if query
            .bundle_path
            .as_ref()
            .is_some_and(|wanted| wanted != path)
            || query
                .path_prefix
                .as_ref()
                .is_some_and(|prefix| !path.starts_with(prefix))
            || glob.as_ref().is_some_and(|glob| !glob.is_match(path))
        {
            continue;
        }
        results.push(asset);
    }
    results.sort_unstable();
    results.dedup();
    Ok(results)
}

fn load_authored_asset(
    store: &Store,
    scanner: &RootedScanner,
    asset: AssetUuid,
) -> Result<Option<(BundleFileHash, CodegenAsset)>, String> {
    let Some(entry) = store.entry(asset).map_err(|error| error.to_string())? else {
        return Ok(None);
    };
    let bundle_meta = store
        .bundle(entry.bundle)
        .map_err(|error| error.to_string())?
        .ok_or_else(|| format!("asset {asset} has no owning bundle row"))?;
    let root = store
        .root_name(bundle_meta.root)
        .map_err(|error| error.to_string())?
        .ok_or_else(|| format!("bundle {} has no root identity", entry.bundle))?;
    let path = scanner
        .physical_path(&root, &bundle_meta.path)
        .map_err(|error| error.to_string())?;
    let bytes = scanner
        .read_identity_checked(&path)
        .map_err(|error| error.to_string())?;
    let hash = BundleFileHash::of_observed_bytes(&bytes);
    if hash.0 != bundle_meta.content_hash.0 {
        return Err(format!(
            "bundle {} changed before its watcher event was published",
            path.display()
        ));
    }
    let bundle = distill_bundle::parse_bundle(&bytes).map_err(|error| error.to_string())?;
    let decoded = bundle
        .assets
        .get(&entry.local_id)
        .ok_or_else(|| format!("asset {asset} is absent from its owning bundle bytes"))?;
    if decoded.uuid != asset || decoded.type_uuid != entry.type_uuid {
        return Err(format!(
            "asset {asset} disagrees with its durable namespace row"
        ));
    }
    Ok(Some((
        hash,
        CodegenAsset {
            asset,
            type_uuid: decoded.type_uuid,
            value: decoded.data.clone(),
        },
    )))
}

fn observe_authored_asset(
    store: &Store,
    scanner: &RootedScanner,
    asset: AssetUuid,
) -> Result<Option<BundleFileHash>, String> {
    load_authored_asset(store, scanner, asset).map(|loaded| loaded.map(|(hash, _)| hash))
}

#[derive(Debug)]
struct OutputDirectory {
    path: PathBuf,
    handle: File,
    identity: FileIdentity,
    #[cfg(unix)]
    quarantine_handle: File,
}

impl OutputDirectory {
    fn open(path: &Path) -> Result<Self, String> {
        ensure_real_directory_tree(path)?;
        if fs::symlink_metadata(path)
            .map(|metadata| metadata.file_type().is_symlink())
            .unwrap_or(false)
        {
            return Err(format!(
                "codegen output {} is not a real directory",
                path.display()
            ));
        }
        let handle = open_output_directory(path)
            .map_err(|error| format!("open codegen output {}: {error}", path.display()))?;
        let metadata = handle
            .metadata()
            .map_err(|error| format!("inspect codegen output handle: {error}"))?;
        if !metadata.is_dir() {
            return Err(format!(
                "codegen output {} is not a real directory",
                path.display()
            ));
        }
        let identity = file_identity(&metadata);
        #[cfg(unix)]
        let quarantine_handle = open_or_create_output_directory(
            &handle,
            OsStr::new(".distill-quarantine"),
            &path.join(".distill-quarantine"),
        )?;
        Ok(Self {
            path: path.to_path_buf(),
            handle,
            identity,
            #[cfg(unix)]
            quarantine_handle,
        })
    }

    fn verify(&self) -> Result<(), String> {
        let metadata = self
            .handle
            .metadata()
            .map_err(|error| format!("reinspect codegen output handle: {error}"))?;
        if !metadata.is_dir() || file_identity(&metadata) != self.identity {
            return Err(format!(
                "codegen output directory {} changed identity",
                self.path.display()
            ));
        }
        #[cfg(not(unix))]
        {
            let current = fs::symlink_metadata(&self.path).map_err(|error| {
                format!("reinspect codegen output {}: {error}", self.path.display())
            })?;
            if current.file_type().is_symlink()
                || !current.is_dir()
                || file_identity(&current) != self.identity
            {
                return Err(format!(
                    "codegen output directory {} changed identity",
                    self.path.display()
                ));
            }
        }
        Ok(())
    }

    fn write_same_dir_temp(&self, target: &Path, bytes: &[u8]) -> Result<PathBuf, String> {
        #[cfg(unix)]
        {
            for _ in 0..64 {
                let temp = unique_sibling(target, "proposal");
                let name = self.root_file_name(&temp)?;
                match create_new_at(&self.handle, name) {
                    Ok(mut file) => {
                        file.write_all(bytes).map_err(|error| {
                            format!("write proposed temp {}: {error}", temp.display())
                        })?;
                        file.sync_all().map_err(|error| {
                            format!("sync proposed temp {}: {error}", temp.display())
                        })?;
                        self.handle.sync_all().map_err(|error| {
                            format!("sync codegen output {}: {error}", self.path.display())
                        })?;
                        return Ok(temp);
                    }
                    Err(error) if error.kind() == std::io::ErrorKind::AlreadyExists => continue,
                    Err(error) => {
                        return Err(format!("create proposed temp {}: {error}", temp.display()))
                    }
                }
            }
            Err("could not allocate a unique codegen proposal temp".into())
        }
        #[cfg(not(unix))]
        {
            crate::lineage_repair::write_same_dir_temp(target, bytes)
        }
    }

    fn read_owned_file(&self, target: &Path) -> Result<Vec<u8>, String> {
        let mut filesystem = OutputJournalFilesystem::new(self);
        filesystem
            .read(target)
            .map_err(|error| error.to_string())?
            .ok_or_else(|| format!("generated file {} is missing", target.display()))
    }

    fn entry_exists(&self, target: &Path) -> Result<bool, String> {
        #[cfg(unix)]
        {
            let name = self.root_file_name(target)?;
            entry_exists_at(&self.handle, name)
                .map_err(|error| format!("inspect generated path {}: {error}", target.display()))
        }
        #[cfg(not(unix))]
        {
            match fs::symlink_metadata(target) {
                Ok(_) => Ok(true),
                Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(false),
                Err(error) => Err(format!(
                    "inspect generated path {}: {error}",
                    target.display()
                )),
            }
        }
    }

    fn entry_names(&self) -> Result<Vec<OsString>, String> {
        #[cfg(unix)]
        {
            read_directory_names_at(&self.handle)
                .map_err(|error| format!("enumerate generated namespace: {error}"))
        }
        #[cfg(not(unix))]
        {
            fs::read_dir(&self.path)
                .map_err(|error| {
                    format!(
                        "enumerate generated namespace {}: {error}",
                        self.path.display()
                    )
                })?
                .map(|entry| {
                    entry
                        .map(|entry| entry.file_name())
                        .map_err(|e| e.to_string())
                })
                .collect()
        }
    }

    #[cfg(unix)]
    fn root_file_name<'a>(&self, path: &'a Path) -> Result<&'a OsStr, String> {
        let relative = path.strip_prefix(&self.path).map_err(|_| {
            format!(
                "codegen journal path {} is outside retained output {}",
                path.display(),
                self.path.display()
            )
        })?;
        let mut components = relative.components();
        let name = match components.next() {
            Some(Component::Normal(name)) => name,
            _ => {
                return Err(format!(
                    "codegen journal path {} is not a direct output child",
                    path.display()
                ))
            }
        };
        if components.next().is_some() {
            return Err(format!(
                "codegen journal path {} is not a direct output child",
                path.display()
            ));
        }
        Ok(name)
    }

    fn quarantine_root(&self) -> QuarantineRoot {
        QuarantineRoot::new(&self.path, self.path.join(".distill-quarantine"))
    }
}

fn ensure_real_directory_tree(path: &Path) -> Result<(), String> {
    if !path.is_absolute() {
        return Err(format!(
            "codegen output path must be absolute: {}",
            path.display()
        ));
    }
    if path
        .components()
        .any(|component| matches!(component, Component::ParentDir))
    {
        return Err("codegen output path contains a parent component".into());
    }
    // The configured absolute path is opened once and its final directory
    // itself must not be a symlink. Platform aliases in ancestors (for
    // example macOS /var -> /private/var) are outside the generated namespace;
    // subsequent publication is fenced against that retained identity.
    match fs::symlink_metadata(path) {
        Ok(_) => {}
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => fs::create_dir_all(path)
            .map_err(|error| format!("create codegen output {}: {error}", path.display()))?,
        Err(error) => {
            return Err(format!(
                "inspect codegen output {}: {error}",
                path.display()
            ))
        }
    }
    Ok(())
}

struct OutputJournalFilesystem<'a> {
    output: &'a OutputDirectory,
}

impl<'a> OutputJournalFilesystem<'a> {
    fn new(output: &'a OutputDirectory) -> Self {
        Self { output }
    }

    fn invalid_path(&self, path: &Path, detail: &str) -> StoreError {
        StoreError::Io {
            path: path.to_path_buf(),
            source: std::io::Error::new(std::io::ErrorKind::InvalidInput, detail),
        }
    }

    #[cfg(unix)]
    fn parent_and_name<'b>(&self, path: &'b Path) -> Result<(&File, &'b OsStr), StoreError> {
        let relative = path.strip_prefix(&self.output.path).map_err(|_| {
            self.invalid_path(path, "journal path escapes the retained codegen output")
        })?;
        let components = relative.components().collect::<Vec<_>>();
        match components.as_slice() {
            [Component::Normal(name)] => Ok((&self.output.handle, name)),
            [Component::Normal(directory), Component::Normal(name)]
                if *directory == OsStr::new(".distill-quarantine") =>
            {
                Ok((&self.output.quarantine_handle, name))
            }
            _ => {
                Err(self.invalid_path(path, "journal path is outside the flat generated namespace"))
            }
        }
    }

    #[cfg(unix)]
    fn directory(&self, path: &Path) -> Result<&File, StoreError> {
        if path == self.output.path {
            Ok(&self.output.handle)
        } else if path == self.output.path.join(".distill-quarantine") {
            Ok(&self.output.quarantine_handle)
        } else {
            Err(self.invalid_path(path, "journal directory is outside codegen output"))
        }
    }

    #[cfg(not(unix))]
    fn validate_path(&self, path: &Path) -> Result<(), StoreError> {
        let relative = path.strip_prefix(&self.output.path).map_err(|_| {
            self.invalid_path(path, "journal path escapes the retained codegen output")
        })?;
        if relative.components().any(|component| {
            !matches!(component, Component::Normal(_)) || matches!(component, Component::ParentDir)
        }) {
            return Err(self.invalid_path(path, "journal path is not canonical"));
        }
        Ok(())
    }
}

impl JournalFilesystem for OutputJournalFilesystem<'_> {
    fn read(&mut self, path: &Path) -> Result<Option<Vec<u8>>, StoreError> {
        #[cfg(unix)]
        {
            let (directory, name) = self.parent_and_name(path)?;
            let mut file = match open_file_at(
                directory,
                name,
                libc::O_RDONLY | libc::O_CLOEXEC | libc::O_NOFOLLOW,
                0,
            ) {
                Ok(file) => file,
                Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(None),
                Err(source) => {
                    return Err(StoreError::Io {
                        path: path.to_path_buf(),
                        source,
                    })
                }
            };
            let opened = file.metadata().map_err(|source| StoreError::Io {
                path: path.to_path_buf(),
                source,
            })?;
            if !opened.is_file() {
                return Err(self.invalid_path(path, "journal path is not a regular file"));
            }
            let opened_modified = opened.modified().ok();
            let mut bytes = Vec::new();
            file.read_to_end(&mut bytes)
                .map_err(|source| StoreError::Io {
                    path: path.to_path_buf(),
                    source,
                })?;
            let after = file.metadata().map_err(|source| StoreError::Io {
                path: path.to_path_buf(),
                source,
            })?;
            let current = open_file_at(
                directory,
                name,
                libc::O_RDONLY | libc::O_CLOEXEC | libc::O_NOFOLLOW,
                0,
            )
            .and_then(|file| file.metadata())
            .map_err(|source| StoreError::Io {
                path: path.to_path_buf(),
                source,
            })?;
            if file_identity(&opened) != file_identity(&after)
                || file_identity(&opened) != file_identity(&current)
                || opened.len() != bytes.len() as u64
                || after.len() != bytes.len() as u64
                || opened_modified != after.modified().ok()
            {
                return Err(self.invalid_path(path, "journal file changed while it was read"));
            }
            Ok(Some(bytes))
        }
        #[cfg(not(unix))]
        {
            self.validate_path(path)?;
            match fs::symlink_metadata(path) {
                Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(None),
                Err(source) => Err(StoreError::Io {
                    path: path.to_path_buf(),
                    source,
                }),
                Ok(metadata) if metadata.file_type().is_symlink() || !metadata.is_file() => {
                    Err(self.invalid_path(path, "journal path is not a real regular file"))
                }
                Ok(metadata) => {
                    let bytes = fs::read(path).map_err(|source| StoreError::Io {
                        path: path.to_path_buf(),
                        source,
                    })?;
                    let current = fs::symlink_metadata(path).map_err(|source| StoreError::Io {
                        path: path.to_path_buf(),
                        source,
                    })?;
                    if current.file_type().is_symlink()
                        || file_identity(&metadata) != file_identity(&current)
                        || metadata.len() != bytes.len() as u64
                    {
                        return Err(
                            self.invalid_path(path, "journal file changed while it was read")
                        );
                    }
                    Ok(Some(bytes))
                }
            }
        }
    }

    fn create_dir_all(&mut self, path: &Path) -> Result<(), StoreError> {
        if path != self.output.path.join(".distill-quarantine") {
            return Err(self.invalid_path(path, "journal may create only codegen quarantine"));
        }
        #[cfg(unix)]
        {
            self.output
                .quarantine_handle
                .metadata()
                .map(|_| ())
                .map_err(|source| StoreError::Io {
                    path: path.to_path_buf(),
                    source,
                })
        }
        #[cfg(not(unix))]
        {
            fs::create_dir_all(path).map_err(|source| StoreError::Io {
                path: path.to_path_buf(),
                source,
            })
        }
    }

    fn sync_file(&mut self, path: &Path) -> Result<(), StoreError> {
        #[cfg(unix)]
        {
            let (directory, name) = self.parent_and_name(path)?;
            open_file_at(
                directory,
                name,
                libc::O_RDONLY | libc::O_CLOEXEC | libc::O_NOFOLLOW,
                0,
            )
            .and_then(|file| file.sync_all())
            .map_err(|source| StoreError::Io {
                path: path.to_path_buf(),
                source,
            })
        }
        #[cfg(not(unix))]
        {
            self.validate_path(path)?;
            File::open(path)
                .and_then(|file| file.sync_all())
                .map_err(|source| StoreError::Io {
                    path: path.to_path_buf(),
                    source,
                })
        }
    }

    fn sync_dir(&mut self, path: &Path) -> Result<(), StoreError> {
        #[cfg(unix)]
        {
            self.directory(path)?
                .sync_all()
                .map_err(|source| StoreError::Io {
                    path: path.to_path_buf(),
                    source,
                })
        }
        #[cfg(not(unix))]
        {
            self.validate_path(path)?;
            File::open(path)
                .and_then(|file| file.sync_all())
                .map_err(|source| StoreError::Io {
                    path: path.to_path_buf(),
                    source,
                })
        }
    }

    fn ensure_same_filesystem(
        &mut self,
        source: &Path,
        destination_dir: &Path,
    ) -> Result<(), StoreError> {
        #[cfg(unix)]
        {
            use std::os::unix::fs::MetadataExt;
            let (source_directory, source_name) = self.parent_and_name(source)?;
            let source_metadata = open_file_at(
                source_directory,
                source_name,
                libc::O_RDONLY | libc::O_CLOEXEC | libc::O_NOFOLLOW,
                0,
            )
            .and_then(|file| file.metadata())
            .map_err(|source_error| StoreError::Io {
                path: source.to_path_buf(),
                source: source_error,
            })?;
            let destination_metadata =
                self.directory(destination_dir)?
                    .metadata()
                    .map_err(|source_error| StoreError::Io {
                        path: destination_dir.to_path_buf(),
                        source: source_error,
                    })?;
            if source_metadata.dev() != destination_metadata.dev() {
                return Err(StoreError::CrossFilesystemQuarantine {
                    source: source.to_path_buf(),
                    quarantine: destination_dir.to_path_buf(),
                });
            }
            Ok(())
        }
        #[cfg(not(unix))]
        {
            self.validate_path(source)?;
            self.validate_path(destination_dir)
        }
    }

    fn move_no_replace(
        &mut self,
        source: &Path,
        destination: &Path,
    ) -> Result<(), NoReplaceMoveError> {
        #[cfg(unix)]
        {
            let (source_directory, source_name) = self
                .parent_and_name(source)
                .map_err(NoReplaceMoveError::Other)?;
            let (destination_directory, destination_name) = self
                .parent_and_name(destination)
                .map_err(NoReplaceMoveError::Other)?;
            link_at(
                source_directory,
                source_name,
                destination_directory,
                destination_name,
            )
            .map_err(|error| {
                if error.kind() == std::io::ErrorKind::AlreadyExists {
                    NoReplaceMoveError::DestinationExists
                } else {
                    NoReplaceMoveError::Other(StoreError::Io {
                        path: destination.to_path_buf(),
                        source: error,
                    })
                }
            })?;
            unlink_at(source_directory, source_name).map_err(|source_error| {
                NoReplaceMoveError::Other(StoreError::Io {
                    path: source.to_path_buf(),
                    source: source_error,
                })
            })
        }
        #[cfg(not(unix))]
        {
            self.validate_path(source)
                .and_then(|()| self.validate_path(destination))
                .map_err(NoReplaceMoveError::Other)?;
            match fs::hard_link(source, destination) {
                Ok(()) => fs::remove_file(source).map_err(|source_error| {
                    NoReplaceMoveError::Other(StoreError::Io {
                        path: source.to_path_buf(),
                        source: source_error,
                    })
                }),
                Err(error) if error.kind() == std::io::ErrorKind::AlreadyExists => {
                    Err(NoReplaceMoveError::DestinationExists)
                }
                Err(source_error) => Err(NoReplaceMoveError::Other(StoreError::Io {
                    path: destination.to_path_buf(),
                    source: source_error,
                })),
            }
        }
    }
}

fn open_output_directory(path: &Path) -> std::io::Result<File> {
    #[cfg(unix)]
    {
        use std::os::unix::fs::OpenOptionsExt;
        fs::OpenOptions::new()
            .read(true)
            .custom_flags(libc::O_CLOEXEC | libc::O_DIRECTORY | libc::O_NOFOLLOW)
            .open(path)
    }
    #[cfg(not(unix))]
    {
        File::open(path)
    }
}

#[cfg(unix)]
fn c_name(name: &OsStr) -> std::io::Result<CString> {
    use std::os::unix::ffi::OsStrExt;
    CString::new(name.as_bytes())
        .map_err(|_| std::io::Error::new(std::io::ErrorKind::InvalidInput, "NUL in filename"))
}

#[cfg(unix)]
fn open_file_at(
    directory: &File,
    name: &OsStr,
    flags: libc::c_int,
    mode: libc::mode_t,
) -> std::io::Result<File> {
    use std::os::fd::{AsRawFd, FromRawFd};
    let name = c_name(name)?;
    // SAFETY: the descriptor and C string remain live for openat; the new
    // descriptor is transferred exactly once into File.
    let descriptor = unsafe {
        libc::openat(
            directory.as_raw_fd(),
            name.as_ptr(),
            flags,
            libc::c_uint::from(mode),
        )
    };
    if descriptor < 0 {
        return Err(std::io::Error::last_os_error());
    }
    Ok(unsafe { File::from_raw_fd(descriptor) })
}

#[cfg(unix)]
fn create_new_at(directory: &File, name: &OsStr) -> std::io::Result<File> {
    open_file_at(
        directory,
        name,
        libc::O_WRONLY | libc::O_CREAT | libc::O_EXCL | libc::O_CLOEXEC | libc::O_NOFOLLOW,
        0o600,
    )
}

#[cfg(unix)]
fn open_or_create_output_directory(
    parent: &File,
    name: &OsStr,
    path: &Path,
) -> Result<File, String> {
    use std::os::fd::AsRawFd;
    let encoded = c_name(name).map_err(|error| error.to_string())?;
    // SAFETY: mkdirat reads the live parent descriptor and C string only.
    let status = unsafe { libc::mkdirat(parent.as_raw_fd(), encoded.as_ptr(), 0o700) };
    if status != 0 {
        let error = std::io::Error::last_os_error();
        if error.kind() != std::io::ErrorKind::AlreadyExists {
            return Err(format!(
                "create codegen quarantine {}: {error}",
                path.display()
            ));
        }
    }
    let directory = open_file_at(
        parent,
        name,
        libc::O_RDONLY | libc::O_CLOEXEC | libc::O_DIRECTORY | libc::O_NOFOLLOW,
        0,
    )
    .map_err(|error| format!("open codegen quarantine {}: {error}", path.display()))?;
    parent
        .sync_all()
        .map_err(|error| format!("sync codegen output after quarantine create: {error}"))?;
    Ok(directory)
}

#[cfg(unix)]
fn entry_exists_at(directory: &File, name: &OsStr) -> std::io::Result<bool> {
    use std::os::fd::AsRawFd;
    let name = c_name(name)?;
    // SAFETY: stat is an out parameter and the descriptor/name remain live.
    let mut stat: libc::stat = unsafe { std::mem::zeroed() };
    let status = unsafe {
        libc::fstatat(
            directory.as_raw_fd(),
            name.as_ptr(),
            &mut stat,
            libc::AT_SYMLINK_NOFOLLOW,
        )
    };
    if status == 0 {
        return Ok(true);
    }
    let error = std::io::Error::last_os_error();
    if error.kind() == std::io::ErrorKind::NotFound {
        Ok(false)
    } else {
        Err(error)
    }
}

#[cfg(unix)]
fn read_directory_names_at(directory: &File) -> std::io::Result<Vec<OsString>> {
    use std::os::fd::IntoRawFd;
    use std::os::unix::ffi::OsStringExt;

    struct Dir(*mut libc::DIR);
    impl Drop for Dir {
        fn drop(&mut self) {
            // SAFETY: fdopendir returned this sole owned DIR pointer.
            unsafe { libc::closedir(self.0) };
        }
    }

    let descriptor = open_file_at(
        directory,
        OsStr::new("."),
        libc::O_RDONLY | libc::O_CLOEXEC | libc::O_DIRECTORY | libc::O_NOFOLLOW,
        0,
    )?
    .into_raw_fd();
    // SAFETY: fdopendir consumes the independently owned descriptor.
    let pointer = unsafe { libc::fdopendir(descriptor) };
    if pointer.is_null() {
        let error = std::io::Error::last_os_error();
        // SAFETY: fdopendir did not consume the descriptor on failure.
        unsafe { libc::close(descriptor) };
        return Err(error);
    }
    let directory = Dir(pointer);
    let mut names = Vec::new();
    loop {
        set_codegen_errno(0);
        // SAFETY: the DIR remains live and the returned name is copied before
        // the next call.
        let entry = unsafe { libc::readdir(directory.0) };
        if entry.is_null() {
            let error = codegen_errno();
            if error != 0 {
                return Err(std::io::Error::from_raw_os_error(error));
            }
            break;
        }
        // SAFETY: POSIX dirent names are NUL terminated within d_name.
        let bytes = unsafe { CStr::from_ptr((*entry).d_name.as_ptr()) }.to_bytes();
        if bytes != b"." && bytes != b".." {
            names.push(OsString::from_vec(bytes.to_vec()));
        }
    }
    Ok(names)
}

#[cfg(unix)]
fn link_at(
    source_directory: &File,
    source: &OsStr,
    destination_directory: &File,
    destination: &OsStr,
) -> std::io::Result<()> {
    use std::os::fd::AsRawFd;
    let source = c_name(source)?;
    let destination = c_name(destination)?;
    // SAFETY: linkat reads the live descriptors and names only.
    let status = unsafe {
        libc::linkat(
            source_directory.as_raw_fd(),
            source.as_ptr(),
            destination_directory.as_raw_fd(),
            destination.as_ptr(),
            0,
        )
    };
    if status == 0 {
        Ok(())
    } else {
        Err(std::io::Error::last_os_error())
    }
}

#[cfg(unix)]
fn unlink_at(directory: &File, name: &OsStr) -> std::io::Result<()> {
    use std::os::fd::AsRawFd;
    let name = c_name(name)?;
    // SAFETY: unlinkat reads the live descriptor and name only.
    let status = unsafe { libc::unlinkat(directory.as_raw_fd(), name.as_ptr(), 0) };
    if status == 0 {
        Ok(())
    } else {
        Err(std::io::Error::last_os_error())
    }
}

#[cfg(unix)]
fn set_codegen_errno(value: libc::c_int) {
    // SAFETY: errno is thread-local and used immediately around readdir.
    unsafe { *codegen_errno_pointer() = value };
}

#[cfg(unix)]
fn codegen_errno() -> libc::c_int {
    // SAFETY: this returns the current thread's live errno cell.
    unsafe { *codegen_errno_pointer() }
}

#[cfg(any(target_os = "linux", target_os = "android"))]
unsafe fn codegen_errno_pointer() -> *mut libc::c_int {
    // SAFETY: delegated to the C runtime's thread-local errno accessor.
    unsafe { libc::__errno_location() }
}

#[cfg(all(unix, not(any(target_os = "linux", target_os = "android"))))]
unsafe fn codegen_errno_pointer() -> *mut libc::c_int {
    // SAFETY: delegated to the C runtime's thread-local errno accessor.
    unsafe { libc::__error() }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum FileIdentity {
    #[cfg(unix)]
    Unix { device: u64, inode: u64 },
    #[cfg(windows)]
    Windows { volume: u64, index: u64 },
    #[cfg(not(any(unix, windows)))]
    Portable { len: u64, modified_nanos: u128 },
}

#[cfg(unix)]
fn file_identity(metadata: &Metadata) -> FileIdentity {
    use std::os::unix::fs::MetadataExt;
    FileIdentity::Unix {
        device: metadata.dev(),
        inode: metadata.ino(),
    }
}

#[cfg(windows)]
fn file_identity(metadata: &Metadata) -> FileIdentity {
    use std::os::windows::fs::MetadataExt;
    FileIdentity::Windows {
        volume: u64::from(metadata.volume_serial_number().unwrap_or(0)),
        index: metadata.file_index().unwrap_or(0),
    }
}

#[cfg(not(any(unix, windows)))]
fn file_identity(metadata: &Metadata) -> FileIdentity {
    let modified_nanos = metadata
        .modified()
        .ok()
        .and_then(|time| time.duration_since(std::time::UNIX_EPOCH).ok())
        .map_or(0, |duration| duration.as_nanos());
    FileIdentity::Portable {
        len: metadata.len(),
        modified_nanos,
    }
}

fn empty_hash() -> ContentHash {
    ContentHash(*blake3::hash(b"").as_bytes())
}

fn path_text(path: &Path) -> Result<String, String> {
    path.to_str()
        .map(str::to_owned)
        .ok_or_else(|| format!("journal path is not lossless UTF-8: {}", path.display()))
}

fn lock_store(store: &Arc<Mutex<Store>>) -> Result<MutexGuard<'_, Store>, String> {
    store
        .lock()
        .map_err(|_| "durable store mutex is poisoned".to_owned())
}

#[cfg(test)]
mod tests {
    use super::*;
    use distill_bundle::{AssetEntry, Bundle, EntryLineageV1};
    use distill_core::id::{BundleUuid, LogicalHash, TypeUuid};
    use distill_core::lineage::{lineage_chain_digest, AcceptedSchemaEpoch, LineageStamp};
    use distill_json::AuthoredValue;
    use distill_schema::ngp_schema::{node_hash, LogicalSchema, PrimitiveKind, SchemaNode};
    use distill_store::bundles::{AssetRecord, BundleMeta};
    use distill_store::StoreConfig;

    fn publication_world(
        temp: &tempfile::TempDir,
    ) -> (
        Arc<Mutex<Store>>,
        RootedScanner,
        OutputDirectory,
        QuarantineDriver,
    ) {
        let assets = temp.path().join("assets");
        let output = temp.path().join("generated");
        fs::create_dir(&assets).unwrap();
        let scanner = RootedScanner::new([crate::scanner::AssetRoot::new(
            "main",
            &assets,
            assets.join(".distill-displaced"),
        )])
        .unwrap();
        let output = OutputDirectory::open(&output).unwrap();
        let quarantine = QuarantineDriver::new([output.quarantine_root()]).unwrap();
        let store = Arc::new(Mutex::new(
            Store::open(StoreConfig::new(temp.path().join("state"))).unwrap(),
        ));
        (store, scanner, output, quarantine)
    }

    fn generated(asset: u8, bytes: &[u8]) -> GeneratedFile {
        GeneratedFile::new(AssetUuid([asset; 16]), bytes.to_vec())
    }

    #[test]
    fn complete_namespace_publishes_diffs_and_skips_unchanged_bytes() {
        let temp = tempfile::tempdir().unwrap();
        let (store, scanner, output, quarantine) = publication_world(&temp);
        let basis = store.lock().unwrap().input_version();
        let first = generated(1, b"pub const VALUE: u8 = 1;\n");
        let second = generated(2, b"pub const VALUE: u8 = 2;\n");
        let first_path = output.path.join(first.relative_path());
        let second_path = output.path.join(second.relative_path());
        let mut world = CodegenWorld {
            store: Arc::clone(&store),
            scanner,
            output: &output,
            quarantine,
        };

        world
            .publish_files(basis, &[first.clone(), second.clone()])
            .unwrap();
        let first_memo = store.lock().unwrap().memo_seq();
        assert_eq!(fs::read(&first_path).unwrap(), first.bytes());
        assert_eq!(fs::read(&second_path).unwrap(), second.bytes());
        assert_eq!(
            fs::read_to_string(output.path.join("mod.rs")).unwrap(),
            concat!(
                "// @generated by distill; do not edit.\n",
                "pub mod sp_01010101010101010101010101010101;\n",
                "pub mod sp_02020202020202020202020202020202;\n"
            )
        );

        world
            .publish_files(basis, &[first.clone(), second])
            .unwrap();
        assert_eq!(store.lock().unwrap().memo_seq(), first_memo);

        world.publish_files(basis, &[first]).unwrap();
        assert!(first_path.exists());
        assert!(!second_path.exists());
        assert_eq!(store.lock().unwrap().codegen_outputs().unwrap().len(), 2);
    }

    #[test]
    fn hand_edits_and_unknown_generated_names_are_never_overwritten() {
        let temp = tempfile::tempdir().unwrap();
        let (store, scanner, output, quarantine) = publication_world(&temp);
        let basis = store.lock().unwrap().input_version();
        let file = generated(3, b"original\n");
        let target = output.path.join(file.relative_path());
        let mut world = CodegenWorld {
            store: Arc::clone(&store),
            scanner,
            output: &output,
            quarantine,
        };
        world.publish_files(basis, &[file]).unwrap();
        let expected = store.lock().unwrap().codegen_outputs().unwrap();

        fs::write(&target, b"human edit\n").unwrap();
        assert!(world
            .publish_files(basis, &[generated(3, b"replacement\n")])
            .unwrap_err()
            .contains("edited outside distill"));
        assert_eq!(fs::read(&target).unwrap(), b"human edit\n");
        assert_eq!(store.lock().unwrap().codegen_outputs().unwrap(), expected);

        fs::write(&target, b"original\n").unwrap();
        fs::write(
            output.path.join("sp_09090909090909090909090909090909.rs"),
            b"unowned\n",
        )
        .unwrap();
        assert!(world
            .publish_files(basis, &[generated(3, b"original\n")])
            .unwrap_err()
            .contains("unowned path"));
    }

    #[test]
    fn authored_context_records_query_and_exact_bundle_read() {
        let temp = tempfile::tempdir().unwrap();
        let assets = temp.path().join("assets");
        fs::create_dir(&assets).unwrap();
        let scanner = RootedScanner::new([crate::scanner::AssetRoot::new(
            "main",
            &assets,
            assets.join(".distill-displaced"),
        )])
        .unwrap();
        let type_uuid = TypeUuid([7; 16]);
        let schema = LogicalSchema {
            root: SchemaNode::Primitive(PrimitiveKind::U8),
        };
        let logical_hash = node_hash(&schema.root).unwrap();
        let epochs = vec![AcceptedSchemaEpoch {
            digest: logical_hash,
            forward_parent: None,
        }];
        let asset = AssetUuid([8; 16]);
        let bundle_uuid = BundleUuid([9; 16]);
        let bytes = distill_bundle::write_bundle(&Bundle {
            format_version: 1,
            uuid: bundle_uuid,
            primary: Some("shader".into()),
            schemas: BTreeMap::from([(logical_hash, schema)]),
            assets: BTreeMap::from([(
                "shader".into(),
                AssetEntry {
                    uuid: asset,
                    type_uuid,
                    schema_hash: logical_hash,
                    lineage: EntryLineageV1::Manifest(LineageStamp {
                        chain: lineage_chain_digest(type_uuid, &epochs, 0),
                        epochs,
                        cursor: 0,
                    }),
                    authoring_only: false,
                    data: AuthoredValue::UInt(7),
                },
            )]),
        })
        .unwrap();
        fs::write(assets.join("shader.bundle"), &bytes).unwrap();
        let store = Arc::new(Mutex::new(
            Store::open(StoreConfig::new(temp.path().join("state"))).unwrap(),
        ));
        let basis = {
            let mut store = store.lock().unwrap();
            let (root, _) = store
                .input_transaction(|transaction| {
                    let root = transaction.intern_root("main")?;
                    transaction.upsert_bundle(&BundleMeta {
                        bundle: bundle_uuid,
                        root,
                        path: "shader.bundle".into(),
                        format_version: 1,
                        content_hash: ContentHash(*blake3::hash(&bytes).as_bytes()),
                        origin: None,
                    })?;
                    transaction.upsert_asset(&AssetRecord {
                        asset,
                        bundle: bundle_uuid,
                        local_id: "shader".into(),
                        type_uuid,
                        logical_hash: LogicalHash(logical_hash.0),
                        authoring_only: false,
                        tags: BTreeMap::new(),
                    })?;
                    Ok(root)
                })
                .unwrap();
            assert_eq!(root.0, 1);
            store.input_version()
        };
        let mut context = AuthoredCodegenContext::new(Arc::clone(&store), scanner.clone(), basis);
        let results = context
            .query(&AssetQuery {
                authored_type: Some(type_uuid),
                ..AssetQuery::default()
            })
            .unwrap();
        assert_eq!(results, [asset]);
        assert_eq!(
            context.read(asset).unwrap().unwrap().value,
            AuthoredValue::UInt(7)
        );
        assert!(matches!(context.trace[0], TraceOp::Query { .. }));
        assert!(matches!(
            context.trace[1],
            TraceOp::AuthoringRead {
                observed: Observed::Ok(Some(_)),
                ..
            }
        ));

        fs::write(assets.join("shader.bundle"), b"concurrent edit").unwrap();
        let output = OutputDirectory::open(&temp.path().join("generated")).unwrap();
        let world = CodegenWorld {
            store,
            scanner,
            output: &output,
            quarantine: QuarantineDriver::new([output.quarantine_root()]).unwrap(),
        };
        assert!(!world.observe(&context.trace[1]));
    }

    #[cfg(unix)]
    #[test]
    fn output_root_symlinks_are_rejected() {
        use std::os::unix::fs::symlink;

        let temp = tempfile::tempdir().unwrap();
        let real = temp.path().join("real");
        let alias = temp.path().join("alias");
        fs::create_dir(&real).unwrap();
        symlink(&real, &alias).unwrap();
        assert!(OutputDirectory::open(&alias)
            .unwrap_err()
            .contains("not a real directory"));
    }

    #[cfg(unix)]
    #[test]
    fn retained_output_capability_cannot_be_redirected_by_path_replacement() {
        use std::os::unix::fs::symlink;

        let temp = tempfile::tempdir().unwrap();
        let (store, scanner, output, quarantine) = publication_world(&temp);
        let basis = store.lock().unwrap().input_version();
        let initial = generated(4, b"initial\n");
        let replacement = generated(4, b"replacement\n");
        let relative = initial.relative_path().to_owned();
        let mut world = CodegenWorld {
            store,
            scanner,
            output: &output,
            quarantine,
        };
        world.publish_files(basis, &[initial]).unwrap();

        let retained = temp.path().join("retained-generated");
        let outside = temp.path().join("outside");
        fs::rename(&output.path, &retained).unwrap();
        fs::create_dir(&outside).unwrap();
        fs::write(outside.join(&relative), b"outside\n").unwrap();
        symlink(&outside, &output.path).unwrap();

        world.publish_files(basis, &[replacement]).unwrap();
        assert_eq!(
            fs::read(retained.join(&relative)).unwrap(),
            b"replacement\n"
        );
        assert_eq!(fs::read(outside.join(&relative)).unwrap(), b"outside\n");
        assert!(!outside.join("mod.rs").exists());
    }

    #[cfg(unix)]
    #[test]
    fn codegen_recovery_uses_the_retained_output_capability() {
        use std::os::unix::fs::symlink;

        let temp = tempfile::tempdir().unwrap();
        let (store, _scanner, output, quarantine) = publication_world(&temp);
        let target = output.path.join("mod.rs");
        let proposed_bytes = b"pub mod shader;\n";
        let proposed_hash = ContentHash(*blake3::hash(proposed_bytes).as_bytes());
        let proposed = output.write_same_dir_temp(&target, proposed_bytes).unwrap();
        let outputs = BTreeMap::from([("mod.rs".to_owned(), proposed_hash)]);
        {
            let mut store = store.lock().unwrap();
            let basis = CodegenPublicationBasis::new(
                store.input_version(),
                BTreeMap::new(),
                outputs.clone(),
            );
            store
                .record_publication_group(
                    PublicationGroupKind::Codegen,
                    &basis.encode(),
                    &[JournalIntentPlan {
                        target_path: path_text(&target).unwrap(),
                        temp_path: path_text(&proposed).unwrap(),
                        conflict_path: path_text(&unique_sibling(&target, "conflict")).unwrap(),
                        pre_image_hash: None,
                        proposed_hash,
                    }],
                )
                .unwrap();
        }

        let retained = temp.path().join("retained-generated");
        let outside = temp.path().join("outside");
        fs::rename(&output.path, &retained).unwrap();
        fs::create_dir(&outside).unwrap();
        symlink(&outside, &output.path).unwrap();

        let mut store = store.lock().unwrap();
        let mut filesystem = OutputJournalFilesystem::new(&output);
        let publication = quarantine
            .admit_codegen_publication(&mut store, &mut filesystem)
            .unwrap();
        assert_eq!(publication.recovered().len(), 1);
        drop(publication);
        assert_eq!(fs::read(retained.join("mod.rs")).unwrap(), proposed_bytes);
        assert!(!outside.join("mod.rs").exists());
        assert_eq!(store.codegen_outputs().unwrap(), outputs);
        assert!(store.unfinished_publication_groups().unwrap().is_empty());
    }
}
