//! Authoring-side Rust binding generation (§20).
//!
//! Pipeline code owns reflection and emitted unit bytes. The daemon owns the
//! pinned authored reads, DSTR observations, complete generated namespace,
//! and its atomic publication.

use std::collections::{BTreeMap, BTreeSet};
use std::ffi::OsString;
use std::fs::{self, File, Metadata};
use std::io::Read;
use std::path::{Component, Path, PathBuf};

use distill_build::codegen::{
    CodegenAttempt, CodegenCoordinator, CodegenFailure, CodegenPublication, CodegenPublisher,
    CodegenSnapshot, GeneratedFile, PublicationError,
};
use distill_build::query::{asset_query_result_hash, AssetQuery};
use distill_build::trace::{Observed, TraceOp};
use distill_core::id::{AssetUuid, BundleFileHash, ContentHash};
#[cfg(test)]
use distill_core::id::{BundleUuid, TypeUuid};
use distill_store::state::InputVersion;
use distill_store::{Store, StoreReader};

use crate::callbacks::{
    CallbackInvokeError, CodegenAsset, CodegenContextError, PipelineCodegenContext,
};
use crate::coordinator::DaemonCoordinator;
use distill_store::atomic_file::{self, content_hash, Expected};
use crate::scanner::{DaemonOwnedDirectoryKind, RootedScanner};

/// The first line of every generated file, followed by the blake3 of the
/// rest of the file. A file whose mark matches its body is distill's own
/// unedited output: whatever publication wrote it, the next one may replace
/// or remove it. Codegen ownership is therefore recoverable from the disk
/// alone, which a publication cut short between its file writes and its
/// `codegen_outputs` rows needs.
const GENERATED_MARK: &str = "// @generated by distill; do not edit. blake3:";

/// `body` under its generated mark.
fn certified(body: &[u8]) -> Vec<u8> {
    let mut bytes = Vec::with_capacity(GENERATED_MARK.len() + 65 + body.len());
    bytes.extend_from_slice(GENERATED_MARK.as_bytes());
    bytes.extend_from_slice(blake3::hash(body).to_hex().as_bytes());
    bytes.push(b'\n');
    bytes.extend_from_slice(body);
    bytes
}

/// Whether `bytes` carry a generated mark that matches their body.
fn is_certified(bytes: &[u8]) -> bool {
    let Some(rest) = bytes.strip_prefix(GENERATED_MARK.as_bytes()) else {
        return false;
    };
    let (Some(hex), Some(b'\n')) = (rest.get(..64), rest.get(64)) else {
        return false;
    };
    hex == blake3::hash(&rest[65..]).to_hex().as_bytes()
}

pub struct CodegenService {
    enabled: bool,
    output: Option<OutputDirectory>,
    /// The installed attempt, of the pipeline epoch `epoch`.
    coordinator: CodegenCoordinator,
    epoch: Option<u64>,
    last_attempted: Option<InputVersion>,
}

impl CodegenService {
    pub fn new(
        daemon: &DaemonCoordinator,
        output_path: impl AsRef<Path>,
        enabled: bool,
    ) -> Result<Self, String> {
        let output = if enabled {
            Some(OutputDirectory::open(output_path.as_ref())?)
        } else {
            None
        };
        let service = Self {
            enabled,
            output,
            coordinator: CodegenCoordinator::default(),
            epoch: None,
            last_attempted: None,
        };
        let retained_output = service
            .output
            .as_ref()
            .map(|output| output.path.as_path())
            .or_else(|| {
                output_path
                    .as_ref()
                    .is_dir()
                    .then_some(output_path.as_ref())
            });
        if let Some(output_path) = retained_output {
            let scanner = daemon.scanner();
            scanner
                .retain_daemon_owned_directory(DaemonOwnedDirectoryKind::CodegenOutput, output_path)
                .map_err(|error| error.to_string())?;
        }
        Ok(service)
    }

    /// Run the pipeline's codegens at `store`'s current version and publish
    /// what they generate, through `store`: at most once per input version,
    /// and not at all while the last standing attempt's trace holds. A stale
    /// attempt is not remembered, so the coordinator loop can retry after
    /// publishing the filesystem event that made it stale.
    pub fn run(&mut self, daemon: &DaemonCoordinator, store: &mut Store) -> Result<(), String> {
        if !self.enabled {
            return Ok(());
        }
        let output = self
            .output
            .as_ref()
            .ok_or_else(|| "enabled codegen service has no output directory".to_owned())?;
        output.verify()?;

        // The pipeline compiled for the version this store sees.
        let compiled = daemon.compiled_at(store).map_err(|error| error.to_string())?;
        let snapshot = compiled.pipeline_snapshot();
        let epoch = snapshot.epoch().map_err(|failure| failure.to_string())?;
        let basis = store.input_version().map_err(|error| error.to_string())?;
        if self.last_attempted == Some(basis) {
            return Ok(());
        }
        if epoch.codegen_descriptors().is_empty() {
            self.last_attempted = Some(basis);
            return Ok(());
        }

        let scanner = compiled.scanner().clone();
        // The installed outcome stands while its epoch runs and its every
        // observation holds: revalidating the trace costs its reads, a run
        // costs the codegens and the publication's whole namespace.
        if self.epoch != Some(epoch.id()) {
            self.coordinator = CodegenCoordinator::default();
            self.epoch = Some(epoch.id());
        }
        let world = CodegenWorld {
            store,
            scanner: scanner.clone(),
            output,
        };
        if self.coordinator.holds(&world) {
            self.last_attempted = Some(basis);
            return Ok(());
        }
        let mut context = AuthoredCodegenContext::new(store, scanner.clone(), basis);
        let result = epoch.invoke_codegens(&mut context);
        let trace = context.trace;
        let attempt = match result {
            Ok(files) if !context.stopped => CodegenAttempt::success(basis, trace, files),
            Ok(_) => CodegenAttempt::failure(
                basis,
                trace,
                CodegenFailure::Generation("codegen context stopped after input drift".into()),
            ),
            Err(CallbackInvokeError::Rejected(failure)) => {
                CodegenAttempt::failure(basis, trace, failure)
            }
            Err(error) => {
                // The epoch remains healthy after a host-owned context panic.
                // Do not latch this basis: the infrastructure fault may be
                // transient and retrying does not repeat a deterministic
                // module rejection.
                if retryable_codegen_callback_failure(&error) {
                    return Err(error.to_string());
                }
                let _ = daemon.sync_runtime_pipeline_failure(store);
                self.last_attempted = Some(basis);
                return Err(error.to_string());
            }
        };
        let mut world = CodegenWorld {
            store,
            scanner,
            output,
        };
        let publication = self.coordinator.finish(attempt, &mut world);
        match publication {
            CodegenPublication::Requeued => Ok(()),
            CodegenPublication::Published { .. } => {
                self.last_attempted = Some(basis);
                Ok(())
            }
            CodegenPublication::Failed(failure) => {
                self.last_attempted = Some(basis);
                Err(failure.to_string())
            }
            CodegenPublication::PublicationFailed(error) => Err(error.to_string()),
        }
    }
}

fn retryable_codegen_callback_failure(error: &CallbackInvokeError<CodegenFailure>) -> bool {
    matches!(error, CallbackInvokeError::HostRejected(_))
}

struct AuthoredCodegenContext<'s> {
    store: &'s StoreReader,
    scanner: RootedScanner,
    basis: InputVersion,
    trace: Vec<TraceOp>,
    stopped: bool,
}

impl<'s> AuthoredCodegenContext<'s> {
    fn new(store: &'s StoreReader, scanner: RootedScanner, basis: InputVersion) -> Self {
        Self {
            store,
            scanner,
            basis,
            trace: Vec::new(),
            stopped: false,
        }
    }

    fn stop<T>(&mut self, error: impl Into<String>) -> Result<T, CodegenContextError> {
        self.stopped = true;
        Err(CodegenContextError::Failed(error.into()))
    }

    fn check_basis(&mut self, store: &StoreReader) -> Result<(), CodegenContextError> {
        if self.stopped {
            return Err(CodegenContextError::AttemptStopped);
        }
        if store.input_version().map_err(|error| CodegenContextError::Failed(error.to_string()))? != self.basis {
            self.stopped = true;
            return Err(CodegenContextError::AttemptStopped);
        }
        Ok(())
    }
}

impl PipelineCodegenContext for AuthoredCodegenContext<'_> {
    fn query(&mut self, query: &AssetQuery) -> Result<Vec<AssetUuid>, CodegenContextError> {
        if self.stopped {
            return Err(CodegenContextError::AttemptStopped);
        }
        let query = match query.clone().close(None) {
            Ok(query) => query,
            Err(error) => {
                self.stopped = true;
                return Err(CodegenContextError::InvalidQuery(error));
            }
        };
        if query.terminal_type.is_some() {
            return self.stop("target-dependent terminal_type is unavailable to Rust codegen");
        }
        let result = {
            let store = self.store;
            self.check_basis(store)?;
            query_results(store, &query).map_err(CodegenContextError::Failed)?
        };
        self.trace.push(TraceOp::Query {
            query: Box::new(query),
            observed: Observed::Ok(asset_query_result_hash(&result)),
        });
        Ok(result)
    }

    fn read(&mut self, asset: AssetUuid) -> Result<Option<CodegenAsset>, CodegenContextError> {
        if self.stopped {
            return Err(CodegenContextError::AttemptStopped);
        }
        let loaded = {
            let store = self.store;
            self.check_basis(store)?;
            load_authored_asset(store, &self.scanner, asset)
        };
        let (observed, value) = match loaded {
            Ok(Some((hash, value))) => (Observed::Ok(Some(hash)), Some(value)),
            Ok(None) => (Observed::Ok(None), None),
            Err(error) => return self.stop(error),
        };
        self.trace.push(TraceOp::AuthoringRead { asset, observed });
        Ok(value)
    }
}

struct CodegenWorld<'a> {
    store: &'a mut Store,
    scanner: RootedScanner,
    output: &'a OutputDirectory,
}

impl CodegenSnapshot<InputVersion> for CodegenWorld<'_> {
    fn current_basis(&self) -> Option<InputVersion> {
        self.store.input_version().ok()
    }

    fn observe(&self, op: &TraceOp) -> bool {
        let store: &StoreReader = self.store;
        match op {
            TraceOp::Query { query, observed } => query_results(store, query)
                .map(|results| Observed::Ok(asset_query_result_hash(&results)) == *observed)
                .unwrap_or(false),
            TraceOp::AuthoringRead { asset, observed } => {
                observe_authored_asset(store, &self.scanner, *asset)
                    .map(|actual| Observed::Ok(actual) == *observed)
                    .unwrap_or(false)
            }
            _ => false,
        }
    }
}

impl CodegenPublisher<InputVersion> for CodegenWorld<'_> {
    fn publish(
        &mut self,
        attempted_basis: &InputVersion,
        files: &[GeneratedFile],
    ) -> Result<(), PublicationError> {
        self.publish_files(*attempted_basis, files)
            .map_err(PublicationError::new)
    }
}

impl CodegenWorld<'_> {
    /// Bring every generated file to the proposed bytes, then commit them
    /// as the new expected pre-images. A crash part-way leaves generated
    /// files that carry their mark (`GENERATED_MARK`); the next publication,
    /// of this namespace or any other, owns them.
    fn publish_files(
        &mut self,
        basis: InputVersion,
        files: &[GeneratedFile],
    ) -> Result<(), String> {
        let output = self.output;
        output.verify()?;
        // The basis check, the file writes and the rows share one write
        // transaction.
        self.store.write_transaction_with(|error| error.to_string(), |store| {
            if store.input_version().map_err(|error| error.to_string())? != basis {
                return Err("codegen input version changed before publication".into());
            }
            let previous = store.codegen_outputs().map_err(|error| error.to_string())?;
            let desired = desired_namespace(files)?;
            let proposed = desired
                .iter()
                .map(|(path, bytes)| (path.clone(), content_hash(bytes)))
                .collect::<BTreeMap<_, _>>();
            let current = Self::verify_preimages(output, &previous, &proposed)?;

            for (relative, &on_disk) in &current {
                if on_disk == proposed.get(relative).copied() {
                    continue;
                }
                let target = output.path.join(relative);
                output.verify()?;
                match desired.get(relative) {
                    Some(bytes) => atomic_file::write(&output.path, &target, bytes, on_disk.into()),
                    None => atomic_file::remove(&target, Expected::from(on_disk)),
                }
                .map_err(|error| error.to_string())?;
            }
            if previous != proposed {
                store
                    .commit_codegen_outputs(&previous, &proposed)
                    .map_err(|error| error.to_string())?;
            }
            Ok(())
        })
    }

    /// What every generated name holds now, once each is checked to be
    /// distill's: its recorded pre-image, the proposed bytes, or any file
    /// carrying its generated mark (a publication cut short before its rows
    /// were committed). Anything else is a hand edit or an unowned file.
    fn verify_preimages(
        output: &OutputDirectory,
        previous: &BTreeMap<String, ContentHash>,
        proposed: &BTreeMap<String, ContentHash>,
    ) -> Result<BTreeMap<String, Option<ContentHash>>, String> {
        let mut names = previous
            .keys()
            .chain(proposed.keys())
            .cloned()
            .collect::<BTreeSet<_>>();
        for entry in output.entry_names()? {
            if let Some(name) = entry.to_str() {
                if name == "mod.rs" || validate_unit_path(name).is_ok() {
                    names.insert(name.to_owned());
                }
            }
        }
        let mut current = BTreeMap::new();
        for relative in names {
            let target = output.path.join(&relative);
            let bytes = output.read_owned(&target)?;
            let actual = bytes.as_deref().map(content_hash);
            let recorded = previous.get(&relative).copied();
            let owned = actual.is_none()
                || actual == recorded
                || actual == proposed.get(&relative).copied()
                || bytes.as_deref().is_some_and(is_certified);
            if !owned {
                return Err(match recorded {
                    Some(_) => format!("generated file {} was edited outside distill", target.display()),
                    None => format!("unowned path {} occupies the generated namespace", target.display()),
                });
            }
            current.insert(relative, actual);
        }
        Ok(current)
    }
}

/// Every generated file's path and exact bytes, each under its generated
/// mark.
fn desired_namespace(files: &[GeneratedFile]) -> Result<BTreeMap<String, Vec<u8>>, String> {
    let mut desired = BTreeMap::new();
    let mut modules = Vec::with_capacity(files.len());
    for file in files {
        validate_unit_path(file.relative_path())?;
        if desired
            .insert(file.relative_path().to_owned(), certified(file.bytes()))
            .is_some()
        {
            return Err(format!(
                "duplicate generated path {} reached the publisher",
                file.relative_path()
            ));
        }
        modules.push(file.relative_path().trim_end_matches(".rs").to_owned());
    }
    modules.sort();
    let mut module = String::new();
    for name in modules {
        module.push_str("pub mod ");
        module.push_str(&name);
        module.push_str(";\n");
    }
    desired.insert("mod.rs".into(), certified(module.as_bytes()));
    Ok(desired)
}

fn validate_unit_path(path: &str) -> Result<(), String> {
    let Some(hex) = path
        .strip_prefix("sp_")
        .and_then(|path| path.strip_suffix(".rs"))
    else {
        return Err(format!("invalid generated unit path {path:?}"));
    };
    if hex.len() != 32
        || !hex
            .as_bytes()
            .iter()
            .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(byte))
    {
        return Err(format!("invalid generated unit path {path:?}"));
    }
    Ok(())
}

/// The runtime assets `query` selects, as one asset query (DESIGN.md §13,
/// asset queries): it fails naming the poisoned bundles it reaches, through
/// a poisoned bundle's skeleton or a poisoned tag index. Only the glob is
/// matched here, after SQL narrowed the rows by its keys.
fn query_results(store: &StoreReader, query: &AssetQuery) -> Result<Vec<AssetUuid>, String> {
    if query.terminal_type.is_some() {
        return Err("target-dependent terminal_type is unavailable to Rust codegen".into());
    }
    let glob = query
        .path_glob
        .as_ref()
        .map(|pattern| {
            globset::Glob::new(pattern)
                .map(|glob| glob.compile_matcher())
                .map_err(|error| error.to_string())
        })
        .transpose()?;
    let answer = store
        .namespace_assets_matching(&crate::build::runtime_asset_filter(query), |path| {
            glob.as_ref().is_none_or(|glob| glob.is_match(path))
        })
        .map_err(|error| error.to_string())?;
    match answer {
        Ok(matched) => Ok(matched.into_iter().map(|matched| matched.asset).collect()),
        Err(bundles) => Err(format!("asset query reaches poisoned bundles {bundles:?}")),
    }
}

/// The whole-table scan [`query_results`] replaced, kept to pin its results.
/// `skeletons` are the poisoned bundles' skeleton entries, with their
/// bundle and path (an entry read cannot see them).
#[cfg(test)]
fn query_results_scan(
    store: &StoreReader,
    query: &AssetQuery,
    skeletons: &[(BundleUuid, String, distill_store::bundles::SkeletonEntry)],
) -> Result<Vec<AssetUuid>, String> {
    if query.terminal_type.is_some() {
        return Err("target-dependent terminal_type is unavailable to Rust codegen".into());
    }
    let bundles = store
        .all_bundles()
        .map_err(|error| error.to_string())?
        .into_iter()
        .map(|bundle| (bundle.bundle, bundle.path))
        .collect::<BTreeMap<_, _>>();
    let glob = query
        .path_glob
        .as_ref()
        .map(|pattern| {
            globset::Glob::new(pattern)
                .map(|glob| glob.compile_matcher())
                .map_err(|error| error.to_string())
        })
        .transpose()?;
    // Whether a runtime row meets every selector, its tag too unless
    // `untagged`.
    let selects = |asset: AssetUuid,
                   bundle: BundleUuid,
                   path: &str,
                   local_id: &str,
                   type_uuid: TypeUuid,
                   tags: &BTreeMap<String, Option<String>>,
                   untagged: bool| {
        query.uuid.is_none_or(|wanted| wanted == asset)
            && query.bundle_uuid.is_none_or(|wanted| wanted == bundle)
            && query.local_id.as_ref().is_none_or(|wanted| wanted == local_id)
            && query.authored_type.is_none_or(|wanted| wanted == type_uuid)
            && (untagged
                || query.tag.as_ref().is_none_or(|tag| {
                    tags.get(&tag.tag).is_some_and(|value| {
                        tag.value.is_none() || value.as_ref() == tag.value.as_ref()
                    })
                }))
            && query.bundle_path.as_ref().is_none_or(|wanted| wanted == path)
            && query
                .path_prefix
                .as_ref()
                .is_none_or(|prefix| path.starts_with(prefix))
            && glob.as_ref().is_none_or(|glob| glob.is_match(path))
    };
    let mut poisoned = std::collections::BTreeSet::new();
    for (bundle, path, entry) in skeletons {
        if !entry.authoring_only
            && selects(
                entry.asset,
                *bundle,
                path,
                &entry.local_id,
                entry.type_uuid,
                &entry.tags,
                false,
            )
        {
            poisoned.insert(*bundle);
        }
    }
    let mut results = Vec::new();
    for asset in store.all_asset_ids().map_err(|error| error.to_string())? {
        let entry = match store.entry(asset) {
            Ok(Some(entry)) => entry,
            Ok(None) | Err(distill_store::StoreError::BundlePoisoned { .. }) => continue,
            Err(error) => return Err(error.to_string()),
        };
        if entry.authoring_only {
            continue;
        }
        let path = bundles
            .get(&entry.bundle)
            .ok_or_else(|| format!("asset {asset} has no owning bundle row"))?;
        let selects = |untagged| {
            selects(
                asset,
                entry.bundle,
                path,
                &entry.local_id,
                entry.type_uuid,
                &entry.tags,
                untagged,
            )
        };
        if query.tag.is_some()
            && selects(true)
            && store
                .tag_index_state(asset)
                .map_err(|error| error.to_string())?
                .is_some_and(|state| state.poison.is_some())
        {
            poisoned.insert(entry.bundle);
        }
        if selects(false) {
            results.push(asset);
        }
    }
    if !poisoned.is_empty() {
        let bundles = poisoned.into_iter().collect::<Vec<_>>();
        return Err(format!("asset query reaches poisoned bundles {bundles:?}"));
    }
    results.sort_unstable();
    Ok(results)
}

fn load_authored_asset(
    store: &StoreReader,
    scanner: &RootedScanner,
    asset: AssetUuid,
) -> Result<Option<(BundleFileHash, CodegenAsset)>, String> {
    let Some((entry, bundle_meta)) =
        store.entry_with_bundle(asset).map_err(|error| error.to_string())?
    else {
        return Ok(None);
    };
    let bundle_meta = bundle_meta
        .ok_or_else(|| format!("asset {asset} has no owning bundle row"))?;
    let root = store
        .root_name(bundle_meta.root)
        .map_err(|error| error.to_string())?
        .ok_or_else(|| format!("bundle {} has no root identity", entry.bundle))?;
    let path = scanner
        .physical_path(&root, &bundle_meta.path)
        .map_err(|error| error.to_string())?;
    let bytes = scanner
        .read_identity_checked(&path)
        .map_err(|error| error.to_string())?;
    let hash = BundleFileHash::of_observed_bytes(&bytes);
    if hash.0 != bundle_meta.content_hash.0 {
        return Err(format!(
            "bundle {} changed before its watcher event was published",
            path.display()
        ));
    }
    let bundle = distill_bundle::parse_bundle(&bytes).map_err(|error| error.to_string())?;
    let decoded = bundle
        .assets
        .get(&entry.local_id)
        .ok_or_else(|| format!("asset {asset} is absent from its owning bundle bytes"))?;
    if decoded.uuid != asset || decoded.type_uuid != entry.type_uuid {
        return Err(format!(
            "asset {asset} disagrees with its durable namespace row"
        ));
    }
    Ok(Some((
        hash,
        CodegenAsset {
            asset,
            type_uuid: decoded.type_uuid,
            value: decoded.data.clone(),
        },
    )))
}

fn observe_authored_asset(
    store: &StoreReader,
    scanner: &RootedScanner,
    asset: AssetUuid,
) -> Result<Option<BundleFileHash>, String> {
    load_authored_asset(store, scanner, asset).map(|loaded| loaded.map(|(hash, _)| hash))
}

#[derive(Debug)]
struct OutputDirectory {
    path: PathBuf,
    identity: FileIdentity,
}

impl OutputDirectory {
    /// Open the output directory for this process, emptying its staging
    /// directory (`atomic_file::open_staging`): a temp there is a write an
    /// earlier process never committed.
    fn open(path: &Path) -> Result<Self, String> {
        ensure_real_directory_tree(path)?;
        let link_metadata = fs::symlink_metadata(path)
            .map_err(|error| format!("inspect codegen output {}: {error}", path.display()))?;
        if link_metadata.file_type().is_symlink() || !link_metadata.is_dir() {
            return Err(format!(
                "codegen output {} is not a real directory",
                path.display()
            ));
        }
        let path = fs::canonicalize(path)
            .map_err(|error| format!("canonicalize codegen output {}: {error}", path.display()))?;
        let metadata = fs::metadata(&path)
            .map_err(|error| format!("inspect codegen output {}: {error}", path.display()))?;
        atomic_file::open_staging(&path)
            .map_err(|error| format!("open codegen staging in {}: {error}", path.display()))?;
        Ok(Self {
            path,
            identity: file_identity(&metadata),
        })
    }

    fn verify(&self) -> Result<(), String> {
        let metadata = fs::symlink_metadata(&self.path).map_err(|error| {
            format!("reinspect codegen output {}: {error}", self.path.display())
        })?;
        let canonical = fs::canonicalize(&self.path).map_err(|error| {
            format!(
                "canonicalize codegen output {}: {error}",
                self.path.display()
            )
        })?;
        if metadata.file_type().is_symlink()
            || !metadata.is_dir()
            || canonical != self.path
            || file_identity(&metadata) != self.identity
        {
            return Err(format!(
                "codegen output directory {} changed",
                self.path.display()
            ));
        }
        Ok(())
    }

    /// Read a generated file, `None` when it does not exist. The path must
    /// be a regular file directly in the output directory, and must not
    /// change while it is read.
    fn read_owned(&self, path: &Path) -> Result<Option<Vec<u8>>, String> {
        self.verify()?;
        let invalid = |detail: &str| format!("generated path {}: {detail}", path.display());
        if path.parent() != Some(self.path.as_path()) {
            return Err(invalid("is outside the flat generated namespace"));
        }
        let opened = match fs::symlink_metadata(path) {
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(None),
            Err(error) => return Err(invalid(&error.to_string())),
            Ok(metadata) if metadata.file_type().is_symlink() || !metadata.is_file() => {
                return Err(invalid("is not a real regular file"));
            }
            Ok(metadata) => metadata,
        };
        let mut file = File::open(path).map_err(|error| invalid(&error.to_string()))?;
        let mut bytes = Vec::new();
        file.read_to_end(&mut bytes)
            .map_err(|error| invalid(&error.to_string()))?;
        let after = file.metadata().map_err(|error| invalid(&error.to_string()))?;
        let current = fs::symlink_metadata(path).map_err(|error| invalid(&error.to_string()))?;
        if current.file_type().is_symlink()
            || file_identity(&after) != file_identity(&opened)
            || file_identity(&current) != file_identity(&opened)
            || opened.len() != bytes.len() as u64
            || after.len() != bytes.len() as u64
            || opened.modified().ok() != after.modified().ok()
        {
            return Err(invalid("changed while it was read"));
        }
        Ok(Some(bytes))
    }


    fn entry_names(&self) -> Result<Vec<OsString>, String> {
        self.verify()?;
        fs::read_dir(&self.path)
            .map_err(|error| {
                format!(
                    "enumerate generated namespace {}: {error}",
                    self.path.display()
                )
            })?
            .map(|entry| {
                let entry = entry.map_err(|error| error.to_string())?;
                let metadata = fs::symlink_metadata(entry.path()).map_err(|error| {
                    format!(
                        "inspect generated entry {}: {error}",
                        entry.path().display()
                    )
                })?;
                if metadata.file_type().is_symlink() {
                    return Err(format!(
                        "generated entry {} is a symlink",
                        entry.path().display()
                    ));
                }
                Ok(entry.file_name())
            })
            .collect()
    }

}

fn ensure_real_directory_tree(path: &Path) -> Result<(), String> {
    if !path.is_absolute() {
        return Err(format!(
            "codegen output path must be absolute: {}",
            path.display()
        ));
    }
    if path
        .components()
        .any(|component| matches!(component, Component::ParentDir))
    {
        return Err("codegen output path contains a parent component".into());
    }
    // Ancestor aliases (for example macOS /var -> /private/var) are resolved
    // when OutputDirectory stores its canonical path. The final configured
    // entry itself must be a real directory.
    match fs::symlink_metadata(path) {
        Ok(_) => {}
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => fs::create_dir_all(path)
            .map_err(|error| format!("create codegen output {}: {error}", path.display()))?,
        Err(error) => {
            return Err(format!(
                "inspect codegen output {}: {error}",
                path.display()
            ))
        }
    }
    Ok(())
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct FileIdentity {
    device: u64,
    inode: u64,
}

#[cfg(unix)]
fn file_identity(metadata: &Metadata) -> FileIdentity {
    use std::os::unix::fs::MetadataExt;
    FileIdentity {
        device: metadata.dev(),
        inode: metadata.ino(),
    }
}

/// As the scanner's: the creation time stands in for the file index stable
/// std lacks on Windows.
#[cfg(windows)]
fn file_identity(metadata: &Metadata) -> FileIdentity {
    use std::os::windows::fs::MetadataExt;
    FileIdentity {
        device: 0,
        inode: metadata.creation_time(),
    }
}


#[cfg(test)]
mod tests {
    use super::*;
    use distill_bundle::{AssetEntry, Bundle};
    use distill_core::id::{BundleUuid, LogicalHash, TypeUuid};
    use distill_json::AuthoredValue;
    use distill_schema::ngp_schema::{node_hash, LogicalSchema, PrimitiveKind, SchemaNode};
    use distill_store::bundles::{AssetRecord, BundleMeta};
    use distill_store::StoreConfig;

    fn publication_world(
        temp: &tempfile::TempDir,
    ) -> (Store, RootedScanner, OutputDirectory) {
        let assets = temp.path().join("assets");
        let output = temp.path().join("generated");
        fs::create_dir(&assets).unwrap();
        let scanner = RootedScanner::new([crate::scanner::AssetRoot::new("main", &assets)])
        .unwrap();
        let output = OutputDirectory::open(&output).unwrap();
        let store = distill_store::Store::open(StoreConfig::new(temp.path().join("state"))).unwrap();
        (store, scanner, output)
    }

    fn generated(asset: u8, bytes: &[u8]) -> GeneratedFile {
        GeneratedFile::new(AssetUuid([asset; 16]), bytes.to_vec())
    }

    #[test]
    fn host_rejected_codegen_context_failures_remain_retryable() {
        assert!(retryable_codegen_callback_failure(
            &CallbackInvokeError::HostRejected("host context panic".to_owned())
        ));
        assert!(!retryable_codegen_callback_failure(
            &CallbackInvokeError::Panicked
        ));
    }

    #[test]
    fn complete_namespace_publishes_diffs_and_skips_unchanged_bytes() {
        let temp = tempfile::tempdir().unwrap();
        let (mut store, scanner, output) = publication_world(&temp);
        let basis = store.input_version().unwrap();
        let first = generated(1, b"pub const VALUE: u8 = 1;\n");
        let second = generated(2, b"pub const VALUE: u8 = 2;\n");
        let first_path = output.path.join(first.relative_path());
        let second_path = output.path.join(second.relative_path());
        let mut world = CodegenWorld {
            store: &mut store,
            scanner,
            output: &output,
        };

        world
            .publish_files(basis, &[first.clone(), second.clone()])
            .unwrap();
        let first_memo = world.store.memo_seq().unwrap();
        assert_eq!(fs::read(&first_path).unwrap(), certified(first.bytes()));
        assert_eq!(fs::read(&second_path).unwrap(), certified(second.bytes()));
        let module = fs::read(output.path.join("mod.rs")).unwrap();
        assert!(is_certified(&module));
        assert_eq!(
            String::from_utf8(module).unwrap().split_once('\n').unwrap().1,
            concat!(
                "pub mod sp_01010101010101010101010101010101;\n",
                "pub mod sp_02020202020202020202020202020202;\n"
            )
        );

        world
            .publish_files(basis, &[first.clone(), second])
            .unwrap();
        assert_eq!(world.store.memo_seq().unwrap(), first_memo);

        world.publish_files(basis, &[first]).unwrap();
        assert!(first_path.exists());
        assert!(!second_path.exists());
        assert_eq!(world.store.codegen_outputs().unwrap().len(), 2);
    }

    #[test]
    fn hand_edits_and_unknown_generated_names_are_never_overwritten() {
        let temp = tempfile::tempdir().unwrap();
        let (mut store, scanner, output) = publication_world(&temp);
        let basis = store.input_version().unwrap();
        let file = generated(3, b"original\n");
        let target = output.path.join(file.relative_path());
        let mut world = CodegenWorld {
            store: &mut store,
            scanner,
            output: &output,
        };
        world.publish_files(basis, &[file]).unwrap();
        let expected = world.store.codegen_outputs().unwrap();

        fs::write(&target, b"human edit\n").unwrap();
        assert!(world
            .publish_files(basis, &[generated(3, b"replacement\n")])
            .unwrap_err()
            .contains("edited outside distill"));
        assert_eq!(fs::read(&target).unwrap(), b"human edit\n");
        assert_eq!(world.store.codegen_outputs().unwrap(), expected);

        // A mark that no longer matches its body is a hand edit too.
        let mut stale_mark = certified(b"original\n");
        stale_mark.extend_from_slice(b"// appended by hand\n");
        fs::write(&target, &stale_mark).unwrap();
        assert!(world
            .publish_files(basis, &[generated(3, b"replacement\n")])
            .unwrap_err()
            .contains("edited outside distill"));
        assert_eq!(fs::read(&target).unwrap(), stale_mark);

        fs::write(&target, certified(b"original\n")).unwrap();
        fs::write(
            output.path.join("sp_09090909090909090909090909090909.rs"),
            b"unowned\n",
        )
        .unwrap();
        assert!(world
            .publish_files(basis, &[generated(3, b"original\n")])
            .unwrap_err()
            .contains("unowned path"));
    }

    #[test]
    fn authored_context_records_query_and_exact_bundle_read() {
        let temp = tempfile::tempdir().unwrap();
        let assets = temp.path().join("assets");
        fs::create_dir(&assets).unwrap();
        let scanner = RootedScanner::new([crate::scanner::AssetRoot::new("main", &assets)])
        .unwrap();
        let type_uuid = TypeUuid([7; 16]);
        let schema = LogicalSchema {
            root: SchemaNode::Primitive(PrimitiveKind::U8),
        };
        let logical_hash = node_hash(&schema.root).unwrap();
        let asset = AssetUuid([8; 16]);
        let bundle_uuid = BundleUuid([9; 16]);
        let bytes = distill_bundle::write_bundle(&Bundle {
            format_version: 1,
            uuid: bundle_uuid,
            primary: Some("shader".into()),
            schemas: BTreeMap::from([(logical_hash, schema)]),
            assets: BTreeMap::from([(
                "shader".into(),
                AssetEntry {
                    uuid: asset,
                    type_uuid,
                    schema_hash: logical_hash,
                    authoring_only: false,
                    data: AuthoredValue::UInt(7),
                },
            )]),
        })
        .unwrap();
        fs::write(assets.join("shader.bundle"), &bytes).unwrap();
        let mut store = distill_store::Store::open(StoreConfig::new(temp.path().join("state"))).unwrap();
        let basis = {
            let (root, _) = store
                .input_transaction(|transaction| {
                    let root = transaction.intern_root("main")?;
                    transaction.upsert_bundle(&BundleMeta {
                        bundle: bundle_uuid,
                        root,
                        path: "shader.bundle".into(),
                        format_version: 1,
                        content_hash: ContentHash(*blake3::hash(&bytes).as_bytes()),
                        origin: None,
                        import_watched: false,
                    })?;
                    transaction.upsert_asset(&AssetRecord {
                        asset,
                        bundle: bundle_uuid,
                        local_id: "shader".into(),
                        type_uuid,
                        logical_hash: LogicalHash(logical_hash.0),
                        authoring_only: false,
                        tags: BTreeMap::new(),
                        terminal_type: None,
                    })?;
                    Ok(root)
                })
                .unwrap();
            assert_eq!(root.0, 1);
            store.input_version().unwrap()
        };
        let mut context = AuthoredCodegenContext::new(&store, scanner.clone(), basis);
        let results = context
            .query(&AssetQuery {
                authored_type: Some(type_uuid),
                ..AssetQuery::default()
            })
            .unwrap();
        assert_eq!(results, [asset]);
        assert_eq!(
            context.read(asset).unwrap().unwrap().value,
            AuthoredValue::UInt(7)
        );
        assert!(matches!(context.trace[0], TraceOp::Query { .. }));
        assert!(matches!(
            context.trace[1],
            TraceOp::AuthoringRead {
                observed: Observed::Ok(Some(_)),
                ..
            }
        ));

        let trace = context.trace;

        fs::write(assets.join("shader.bundle"), b"concurrent edit").unwrap();
        let output = OutputDirectory::open(&temp.path().join("generated")).unwrap();
        let world = CodegenWorld {
            store: &mut store,
            scanner,
            output: &output,
        };
        assert!(!world.observe(&trace[1]));
    }

    #[cfg(unix)]
    #[test]
    fn output_root_symlinks_are_rejected() {
        use std::os::unix::fs::symlink;

        let temp = tempfile::tempdir().unwrap();
        let real = temp.path().join("real");
        let alias = temp.path().join("alias");
        fs::create_dir(&real).unwrap();
        symlink(&real, &alias).unwrap();
        assert!(OutputDirectory::open(&alias)
            .unwrap_err()
            .contains("not a real directory"));
    }

    #[cfg(unix)]
    #[test]
    fn output_path_replacement_is_rejected_without_writing_outside() {
        use std::os::unix::fs::symlink;

        let temp = tempfile::tempdir().unwrap();
        let (mut store, scanner, output) = publication_world(&temp);
        let basis = store.input_version().unwrap();
        let initial = generated(4, b"initial\n");
        let replacement = generated(4, b"replacement\n");
        let relative = initial.relative_path().to_owned();
        let mut world = CodegenWorld {
            store: &mut store,
            scanner,
            output: &output,
        };
        world.publish_files(basis, &[initial]).unwrap();

        let retained = temp.path().join("retained-generated");
        let outside = temp.path().join("outside");
        fs::rename(&output.path, &retained).unwrap();
        fs::create_dir(&outside).unwrap();
        fs::write(outside.join(&relative), b"outside\n").unwrap();
        symlink(&outside, &output.path).unwrap();

        let error = world.publish_files(basis, &[replacement]).unwrap_err();
        assert!(error.to_string().contains("changed"));
        assert_eq!(
            fs::read(retained.join(&relative)).unwrap(),
            certified(b"initial\n")
        );
        assert_eq!(fs::read(outside.join(&relative)).unwrap(), b"outside\n");
        assert!(!outside.join("mod.rs").exists());
    }

    #[test]
    fn files_written_before_a_crash_are_adopted_by_the_next_publication() {
        let temp = tempfile::tempdir().unwrap();
        let (mut store, scanner, output) = publication_world(&temp);
        let basis = store.input_version().unwrap();
        let first = generated(5, b"pub const VALUE: u8 = 5;\n");
        let files = [first.clone()];
        // The files reached the disk, the rows were never committed.
        for (relative, bytes) in desired_namespace(&files).unwrap() {
            atomic_file::write(&output.path, &output.path.join(relative), &bytes, Expected::Any)
                .unwrap();
        }
        assert!(store.codegen_outputs().unwrap().is_empty());

        let mut world = CodegenWorld {
            store: &mut store,
            scanner,
            output: &output,
        };
        world.publish_files(basis, &files).unwrap();
        let outputs = world.store.codegen_outputs().unwrap();
        assert_eq!(outputs.len(), 2);
        assert_eq!(
            outputs[first.relative_path()],
            content_hash(&certified(first.bytes()))
        );
    }

    /// Txn M5: a publication cut short part-way, then a publication of a
    /// different namespace. The partial files are distill's own output,
    /// so the second publication replaces or removes them.
    #[test]
    fn a_partial_publication_does_not_wedge_a_changed_namespace() {
        let temp = tempfile::tempdir().unwrap();
        let (mut store, scanner, output) = publication_world(&temp);
        let basis = store.input_version().unwrap();
        let mut world = CodegenWorld {
            store: &mut store,
            scanner,
            output: &output,
        };
        world.publish_files(basis, &[generated(3, b"one\n")]).unwrap();

        // The next publication wrote mod.rs and the new unit, then crashed
        // before replacing sp_03 and committing its rows.
        let interrupted = desired_namespace(&[generated(2, b"new\n"), generated(3, b"two\n")])
            .unwrap();
        let added = generated(2, b"").relative_path().to_owned();
        for relative in ["mod.rs", added.as_str()] {
            atomic_file::write(
                &output.path,
                &output.path.join(relative),
                &interrupted[relative],
                Expected::Any,
            )
            .unwrap();
        }

        // The inputs changed before the restart: sp_02 is gone again.
        let third = generated(3, b"three\n");
        world.publish_files(basis, std::slice::from_ref(&third)).unwrap();
        assert!(!output.path.join(&added).exists());
        let expected = desired_namespace(std::slice::from_ref(&third)).unwrap();
        for (relative, bytes) in &expected {
            assert_eq!(&fs::read(output.path.join(relative)).unwrap(), bytes);
        }
        let recorded = world.store.codegen_outputs().unwrap();
        assert_eq!(recorded.len(), 2);
        assert_eq!(recorded[third.relative_path()], content_hash(&expected[third.relative_path()]));
    }
}

#[cfg(test)]
mod query_tests {
    //! Codegen's indexed asset query answers what the whole-namespace scan
    //! it replaced answered, errors included, and reads a small part of a
    //! large namespace.

    use super::*;
    use distill_build::query::TagSelector;
    use distill_core::id::{BundleUuid, LogicalHash, TypeUuid};
    use distill_store::bundles::{AssetRecord, BundleMeta, NamespaceSkeleton};
    use distill_store::files::{path_extension, path_name, GlobKeys, GLOBSET_META};
    use distill_store::StoreConfig;

    const SCHEMA: LogicalHash = LogicalHash([0x5c; 32]);
    const MESH: TypeUuid = TypeUuid([0x71; 16]);
    const TEXTURE: TypeUuid = TypeUuid([0x72; 16]);

    const PATHS: [&str; 12] = [
        "dir",
        "dir.txt",
        "dir-old",
        "dir/child",
        "dir/child/leaf",
        "dir0",
        "dirt/x",
        "é/ü.bundle",
        "éa",
        "a*b",
        "a{b,c}/[x]",
        "z",
    ];

    fn uuid(kind: u8, index: u32) -> [u8; 16] {
        let mut bytes = [kind; 16];
        bytes[12..].copy_from_slice(&index.to_be_bytes());
        bytes
    }

    #[derive(Clone, Copy)]
    enum Damage {
        None,
        PoisonedBundle,
        PendingTagIndex,
    }

    /// The skeleton entries of the bundles `damage` poisons.
    fn skeletons(damage: Damage) -> Vec<(BundleUuid, String, distill_store::bundles::SkeletonEntry)> {
        match damage {
            Damage::PoisonedBundle => vec![(
                BundleUuid(uuid(0x10, 5)),
                "dir0".to_owned(),
                distill_store::bundles::SkeletonEntry {
                    asset: AssetUuid(uuid(0x21, 5)),
                    local_id: "main".into(),
                    type_uuid: MESH,
                    authoring_only: false,
                    tags: BTreeMap::from([("kind".to_owned(), None)]),
                },
            )],
            Damage::None | Damage::PendingTagIndex => Vec::new(),
        }
    }

    fn namespace(filler: u32, damage: Damage) -> (tempfile::TempDir, Store) {
        let dir = tempfile::tempdir().unwrap();
        let mut store = Store::open(StoreConfig::new(dir.path().join(".distill"))).unwrap();
        store
            .input_transaction(|txn| {
                let root = txn.intern_root("main")?;
                let paths = PATHS
                    .iter()
                    .map(|path| (*path).to_owned())
                    .chain((0..filler).map(|index| format!("bulk/b{index:05}")));
                for (index, path) in paths.enumerate() {
                    let index = index as u32;
                    let bundle = BundleUuid(uuid(0x10, index));
                    txn.upsert_bundle(&BundleMeta {
                        bundle,
                        root,
                        path,
                        format_version: 1,
                        content_hash: ContentHash([index as u8; 32]),
                        origin: None,
                        import_watched: false,
                    })?;
                    for (entry, authoring_only) in [(1u8, false), (2, true)] {
                        let mut tags = BTreeMap::new();
                        tags.insert(
                            "kind".to_owned(),
                            (index % 3 != 0).then(|| ["mesh", "rock"][index as usize % 2].to_owned()),
                        );
                        if index % 4 == u32::from(entry) {
                            tags.insert("hero".into(), None);
                        }
                        txn.upsert_asset(&AssetRecord {
                            asset: AssetUuid(uuid(0x20 + entry, index)),
                            bundle,
                            local_id: if entry == 1 { "main" } else { "settings" }.into(),
                            type_uuid: if index % 2 == 0 { MESH } else { TEXTURE },
                            logical_hash: SCHEMA,
                            authoring_only,
                            tags,
                            terminal_type: None,
                        })?;
                    }
                }
                if let Damage::PendingTagIndex = damage {
                    txn.set_tag_index_pending(AssetUuid(uuid(0x21, 11)))?;
                }
                for (bundle, path, entry) in skeletons(damage) {
                    txn.poison_bundle(
                        &NamespaceSkeleton {
                            bundle,
                            root,
                            path,
                            format_version: 1,
                            content_hash: ContentHash([0xee; 32]),
                            entries: vec![entry],
                        },
                        "malformed",
                    )?;
                }
                Ok(())
            })
            .unwrap();
        (dir, store)
    }

    fn none() -> AssetQuery {
        AssetQuery {
            uuid: None,
            bundle_path: None,
            local_id: None,
            bundle_uuid: None,
            authored_type: None,
            terminal_type: None,
            tag: None,
            path_prefix: None,
            path_glob: None,
            authoring_only: None,
        }
    }

    const GLOBS: [&str; 22] = [
        "*",
        "**",
        "**/leaf",
        "*/child",
        "**/ü.bundle",
        "*.bundle",
        "*.txt",
        "d*/c*",
        "dir*",
        "dir/*",
        "dir/**",
        "**/child",
        "d?r*",
        "{dir,z}*",
        "[d]ir*",
        "dir/\\*",
        "a\\*b",
        "a{b,c}/*",
        "é/*",
        "bulk/b000?",
        "dir",
        "[",
    ];

    fn queries() -> Vec<AssetQuery> {
        let mut queries = vec![
            AssetQuery {
                terminal_type: Some(MESH),
                ..none()
            },
            AssetQuery {
                authoring_only: Some(true),
                ..none()
            },
            AssetQuery {
                authoring_only: Some(false),
                ..none()
            },
        ];
        for index in [0, 3, 5, 11] {
            queries.push(AssetQuery {
                uuid: Some(AssetUuid(uuid(0x21, index))),
                ..none()
            });
            queries.push(AssetQuery {
                uuid: Some(AssetUuid(uuid(0x22, index))),
                ..none()
            });
            queries.push(AssetQuery {
                bundle_uuid: Some(BundleUuid(uuid(0x10, index))),
                local_id: Some("main".into()),
                ..none()
            });
        }
        for local_id in ["main", "settings", "absent"] {
            queries.push(AssetQuery {
                local_id: Some(local_id.into()),
                ..none()
            });
        }
        for path in PATHS {
            queries.push(AssetQuery {
                bundle_path: Some(path.into()),
                ..none()
            });
            queries.push(AssetQuery {
                path_prefix: Some(path.into()),
                ..none()
            });
        }
        for prefix in ["", "d", "dir/", "é", "bulk/b0001"] {
            queries.push(AssetQuery {
                path_prefix: Some(prefix.into()),
                ..none()
            });
        }
        for glob in GLOBS {
            queries.push(AssetQuery {
                path_glob: Some(glob.into()),
                ..none()
            });
            queries.push(AssetQuery {
                path_glob: Some(glob.into()),
                path_prefix: Some("dir".into()),
                ..none()
            });
        }
        for type_uuid in [MESH, TEXTURE] {
            queries.push(AssetQuery {
                authored_type: Some(type_uuid),
                ..none()
            });
            // A narrow selector beside a broad one.
            for glob in ["**/child", "*/leaf", "*.txt", "**/ü.bundle"] {
                queries.push(AssetQuery {
                    path_glob: Some(glob.into()),
                    authored_type: Some(type_uuid),
                    ..none()
                });
            }
            queries.push(AssetQuery {
                local_id: Some("main".into()),
                authored_type: Some(type_uuid),
                ..none()
            });
            queries.push(AssetQuery {
                authoring_only: Some(true),
                authored_type: Some(type_uuid),
                ..none()
            });
        }
        for (tag, value) in [
            ("kind", None),
            ("kind", Some("mesh")),
            ("hero", None),
            ("hero", Some("x")),
            ("absent", None),
        ] {
            let tag = Some(TagSelector {
                tag: tag.into(),
                value: value.map(str::to_owned),
            });
            queries.push(AssetQuery {
                tag: tag.clone(),
                ..none()
            });
            queries.push(AssetQuery {
                tag,
                path_glob: Some("dir/**".into()),
                ..none()
            });
        }
        queries
    }

    #[test]
    fn asset_queries_answer_what_the_scan_answered() {
        for damage in [Damage::None, Damage::PoisonedBundle, Damage::PendingTagIndex] {
            let (_dir, store) = namespace(30, damage);
            let reader = store.reader().unwrap();
            let mut nonempty = 0;
            let mut failed = 0;
            for query in queries() {
                let indexed = query_results(&reader, &query);
                let scanned = query_results_scan(&reader, &query, &skeletons(damage));
                assert_eq!(indexed, scanned, "{query:?}");
                failed += usize::from(indexed.is_err());
                nonempty += usize::from(indexed.is_ok_and(|assets| !assets.is_empty()));
            }
            // A poison fails only the queries that reach it.
            assert!(nonempty > 30, "{nonempty}");
            if !matches!(damage, Damage::None) {
                assert!(failed > 3, "{failed}");
            }
        }
    }

    /// Every path a `globset` pattern matches starts with the pattern's
    /// literal prefix and has the final segment and extension its literal
    /// tail names, which is what lets SQL narrow to those rows.
    #[test]
    fn a_glob_matches_only_paths_with_its_keys() {
        let paths = PATHS
            .iter()
            .copied()
            .chain([
                "", "/", "d", "dir/", "dirx/y", "z/z", "é", "a{b,c}", "x/dir", "q.txt",
                "x/y.z", "a/q/b.c.d", "[x].y", "w/x.y", "a.b/c", "dir/child/x",
            ]);
        let globs = GLOBS.iter().copied().chain([
            "dir/",
            "dir/{a,b}",
            "**/dir",
            "a/**/b",
            "\\d*",
            "dir/[!a]*",
            "dir?",
            "*\\.txt",
            "**/x\\/y.z",
            "a*/b.c.d",
            "**/[x].y",
            "*/c?ild",
            "**/child/*",
        ]);
        let mut matched = 0;
        for pattern in globs {
            let Ok(glob) = globset::Glob::new(pattern) else {
                continue;
            };
            let glob = glob.compile_matcher();
            let keys = GlobKeys::of(pattern, GLOBSET_META);
            for path in paths.clone() {
                if glob.is_match(path) {
                    matched += 1;
                    assert!(path.starts_with(keys.prefix), "{pattern:?} matched {path:?}");
                    assert!(
                        keys.name.is_none_or(|name| path_name(path) == name),
                        "{pattern:?} matched {path:?}"
                    );
                    assert!(
                        keys.extension
                            .is_none_or(|extension| path_extension(path) == Some(extension)),
                        "{pattern:?} matched {path:?}"
                    );
                }
            }
        }
        assert!(matched > 20, "{matched}");
    }

    #[test]
    fn a_narrow_codegen_query_reads_little_of_a_large_namespace() {
        let (_dir, store) = namespace(20_000, Damage::None);
        let reader = store.reader().unwrap();
        for query in [
            AssetQuery {
                bundle_path: Some("bulk/b12345".into()),
                ..none()
            },
            AssetQuery {
                path_glob: Some("bulk/b1234?".into()),
                tag: Some(TagSelector {
                    tag: "kind".into(),
                    value: None,
                }),
                ..none()
            },
            AssetQuery {
                path_glob: Some("**/b12345".into()),
                authored_type: Some(TEXTURE),
                ..none()
            },
        ] {
            let before = reader.pages_fetched().unwrap();
            let indexed = query_results(&reader, &query).unwrap();
            let middle = reader.pages_fetched().unwrap();
            let scanned = query_results_scan(&reader, &query, &[]).unwrap();
            let after = reader.pages_fetched().unwrap();
            let (indexed_pages, scanned_pages) = (middle - before, after - middle);
            assert_eq!(indexed, scanned);
            assert!(!indexed.is_empty());
            println!("{query:?}: {indexed_pages} pages (scan: {scanned_pages})");
            assert!(indexed_pages <= 128, "{indexed_pages} pages");
            assert!(scanned_pages >= 100 * indexed_pages, "{scanned_pages} pages");
        }
    }
}
