//! Canonical compiled-consumer attestation (§§3, 5, 15–17).
//!
//! This module is deliberately dependency-free apart from `distill-core`'s
//! identity and hashing primitives. Every producer and consumer uses these
//! exact row types and codecs; no surface accepts caller-described opaque
//! "registry extras" bytes.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt;

use unicode_normalization::UnicodeNormalization;

use crate::canonical::{DSCA, DSRE, DSTA};
use crate::id::{LogicalHash, TypeUuid};

const VERSION: u8 = 1;

/// The byte-authoritative bundle-format-v1 control schema table.  This is a
/// release input, not generated by a build script or reconstructed from the
/// live registry.
pub const BOOTSTRAP_CONTROL_SPEC_V1_BYTES: &[u8] =
    include_bytes!("../bootstrap/control-spec-v1.dsb");

pub const BOOTSTRAP_CONTROL_COUNT: usize = 5;

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[repr(u8)]
pub enum BootstrapControlSymbol {
    SchemaLineageManifest = 1,
    Migration = 2,
    ImportRecord = 3,
    DirectoryImportRules = 4,
    PackDefinition = 5,
}

impl BootstrapControlSymbol {
    fn decode(value: u8) -> Result<Self, BootstrapSpecError> {
        match value {
            1 => Ok(Self::SchemaLineageManifest),
            2 => Ok(Self::Migration),
            3 => Ok(Self::ImportRecord),
            4 => Ok(Self::DirectoryImportRules),
            5 => Ok(Self::PackDefinition),
            value => Err(BootstrapSpecError::UnknownSymbol(value)),
        }
    }
}

/// UUIDv5(namespace URL, `https://distill.dev/bundle/v1/control/<symbol>`).
/// The DSB repeats these literal bytes and its parser checks the complete,
/// closed mapping so changing either side cannot silently reinterpret a row.
pub const SCHEMA_LINEAGE_MANIFEST_TYPE_UUID: TypeUuid = TypeUuid([
    0x46, 0x80, 0x0e, 0xc6, 0x07, 0x26, 0x5d, 0x36, 0x9a, 0x6c, 0xc5, 0xc6, 0xd3, 0xc2, 0x53, 0x37,
]);
pub const MIGRATION_TYPE_UUID: TypeUuid = TypeUuid([
    0x7c, 0x9c, 0xfd, 0xbf, 0xd0, 0xca, 0x59, 0x33, 0xb8, 0xde, 0x39, 0xa8, 0x58, 0xeb, 0x06, 0xb3,
]);
pub const IMPORT_RECORD_TYPE_UUID: TypeUuid = TypeUuid([
    0x57, 0x05, 0x38, 0x2c, 0xee, 0x65, 0x5a, 0x35, 0xa8, 0xea, 0xd5, 0x30, 0xf9, 0x8a, 0x77, 0x12,
]);
pub const DIRECTORY_IMPORT_RULES_TYPE_UUID: TypeUuid = TypeUuid([
    0xf8, 0x2a, 0xec, 0xaf, 0x0b, 0xdf, 0x52, 0x6f, 0xaf, 0x12, 0x5c, 0xb6, 0x95, 0x81, 0xc8, 0x3b,
]);
pub const PACK_DEFINITION_TYPE_UUID: TypeUuid = TypeUuid([
    0x36, 0x7c, 0xe2, 0x4c, 0xce, 0xc3, 0x5b, 0x17, 0xb4, 0x0f, 0x36, 0x2f, 0x90, 0x0c, 0xb5, 0xb0,
]);

pub const BOOTSTRAP_CONTROL_TYPE_UUIDS: [TypeUuid; BOOTSTRAP_CONTROL_COUNT] = [
    PACK_DEFINITION_TYPE_UUID,
    SCHEMA_LINEAGE_MANIFEST_TYPE_UUID,
    IMPORT_RECORD_TYPE_UUID,
    MIGRATION_TYPE_UUID,
    DIRECTORY_IMPORT_RULES_TYPE_UUID,
];

fn symbol_uuid(symbol: BootstrapControlSymbol) -> TypeUuid {
    match symbol {
        BootstrapControlSymbol::SchemaLineageManifest => SCHEMA_LINEAGE_MANIFEST_TYPE_UUID,
        BootstrapControlSymbol::Migration => MIGRATION_TYPE_UUID,
        BootstrapControlSymbol::ImportRecord => IMPORT_RECORD_TYPE_UUID,
        BootstrapControlSymbol::DirectoryImportRules => DIRECTORY_IMPORT_RULES_TYPE_UUID,
        BootstrapControlSymbol::PackDefinition => PACK_DEFINITION_TYPE_UUID,
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct SchemaNodeId(pub u32);

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum RegistryPathStep {
    Field(String),
    Variant(String),
    Elem,
    MapKey,
    MapValue,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum ReferenceStrength {
    Weak,
    Strong,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum ControlRole {
    Unrestricted,
    AuthoringOnlyRequired,
}

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum RegistryExtraFact {
    Reference {
        strength: ReferenceStrength,
        target: TypeUuid,
    },
    Blob,
    Tag,
    Skip,
    BuildOnly(bool),
    ControlRole(ControlRole),
    /// A recursive expansion edge. The target is the node assigned at the
    /// first expansion of the repeated Rust/schema type.
    BackReference {
        target: SchemaNodeId,
    },
}

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct RegistryExtraRow {
    pub node: SchemaNodeId,
    pub path: Vec<RegistryPathStep>,
    pub fact: RegistryExtraFact,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct RegistryExtrasDigest(pub [u8; 32]);

#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct RegistryExtrasV1 {
    pub rows: Vec<RegistryExtraRow>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CompiledTypeRow {
    pub type_uuid: TypeUuid,
    pub logical_hash: LogicalHash,
    pub native_layout_digest: [u8; 32],
    pub build_only: bool,
    pub registry_extras_digest: RegistryExtrasDigest,
    pub registry_extras: RegistryExtrasV1,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct CompiledAttestationDigest(pub [u8; 32]);

/// Digest of the complete, canonical `#[asset(tag)]` projection for one
/// compiled type table. This value is always derived from the rows; consumers
/// must use [`verify_tag_annotation_epoch`] rather than accepting an opaque
/// epoch supplied across a trust boundary.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct TagAnnotationEpoch(pub [u8; 32]);

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CompiledTypeTable {
    pub rows: Vec<CompiledTypeRow>,
    pub digest: CompiledAttestationDigest,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BootstrapControlSpecRowV1 {
    pub symbol: BootstrapControlSymbol,
    pub type_uuid: TypeUuid,
    /// Exact canonical logical SchemaGraph bytes, beginning at its root node.
    pub logical_schema: Vec<u8>,
    pub logical_hash: LogicalHash,
    pub registry_extras: RegistryExtrasV1,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BootstrapControlSpecV1(pub [BootstrapControlSpecRowV1; BOOTSTRAP_CONTROL_COUNT]);

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BootstrapControlTableV1([CompiledTypeRow; BOOTSTRAP_CONTROL_COUNT]);

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BundleFormatVersion {
    V1,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum BootstrapSpecError {
    UnsupportedVersion(u8),
    WrongCount(u32),
    UnknownSymbol(u8),
    DuplicateSymbol(BootstrapControlSymbol),
    DuplicateType(TypeUuid),
    SymbolUuidMismatch {
        symbol: BootstrapControlSymbol,
        expected: TypeUuid,
        observed: TypeUuid,
    },
    RowsNotStrictlySorted,
    BuildOnlyRequired,
    InvalidSchemaNode(u8),
    InvalidPrimitive,
    InvalidBackReference(u32),
    MissingRegistryFact(&'static str),
    InvalidRegistrySchemaNode(SchemaNodeId),
    SchemaEntriesNotStrictlySorted,
    NonCanonicalEncoding,
    Attestation(AttestationError),
    Truncated,
    TrailingBytes,
}

impl fmt::Display for BootstrapSpecError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{self:?}")
    }
}

impl std::error::Error for BootstrapSpecError {}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum BootstrapAuthorityMismatch {
    InvalidSpec(BootstrapSpecError),
    InvalidTable(AttestationError),
    WrongCount(usize),
    Missing(TypeUuid),
    Unequal {
        type_uuid: TypeUuid,
        field: &'static str,
    },
}

impl fmt::Display for BootstrapAuthorityMismatch {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{self:?}")
    }
}

impl std::error::Error for BootstrapAuthorityMismatch {}

impl From<AttestationError> for BootstrapSpecError {
    fn from(value: AttestationError) -> Self {
        match value {
            AttestationError::Truncated => Self::Truncated,
            AttestationError::TrailingBytes => Self::TrailingBytes,
            value => Self::Attestation(value),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum AttestationError {
    UnsupportedVersion(u8),
    Truncated,
    TrailingBytes,
    InvalidUtf8,
    NonCanonicalText,
    UnknownPathStep(u8),
    UnknownFact(u8),
    InvalidBool(u8),
    UnknownReferenceStrength(u8),
    UnknownControlRole(u8),
    ExtrasNotStrictlySorted,
    DuplicateExtraRow,
    ExtrasDigestMismatch,
    TypeRowsNotStrictlySorted,
    DuplicateType(TypeUuid),
    ProjectionMissingType(TypeUuid),
    CompiledDigestMismatch,
    TagAnnotationEpochMismatch {
        expected: TagAnnotationEpoch,
        observed: TagAnnotationEpoch,
    },
    CountOverflow,
}

impl fmt::Display for AttestationError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{self:?}")
    }
}

impl std::error::Error for AttestationError {}

impl RegistryExtrasV1 {
    /// Normalizes path labels and sorts producer rows into the sole canonical
    /// order. Normalization collisions are rejected as duplicate facts.
    pub fn canonical(mut rows: Vec<RegistryExtraRow>) -> Result<Self, AttestationError> {
        for row in &mut rows {
            for step in &mut row.path {
                match step {
                    RegistryPathStep::Field(value) | RegistryPathStep::Variant(value) => {
                        *value = value.nfc().collect();
                    }
                    RegistryPathStep::Elem
                    | RegistryPathStep::MapKey
                    | RegistryPathStep::MapValue => {}
                }
            }
        }
        let mut keyed = rows
            .into_iter()
            .map(|row| Ok((registry_row_order_key(&row)?, row)))
            .collect::<Result<Vec<_>, AttestationError>>()?;
        keyed.sort_by(|left, right| left.0.cmp(&right.0));
        if keyed.windows(2).any(|pair| pair[0].0 == pair[1].0) {
            return Err(AttestationError::DuplicateExtraRow);
        }
        let rows = keyed.into_iter().map(|(_, row)| row).collect();
        Ok(Self { rows })
    }

    /// Validates bytes/rows received across a trust boundary without sorting
    /// them on the receiver's behalf.
    pub fn validate(&self) -> Result<(), AttestationError> {
        for row in &self.rows {
            for step in &row.path {
                if let RegistryPathStep::Field(value) | RegistryPathStep::Variant(value) = step {
                    if value.nfc().collect::<String>() != *value {
                        return Err(AttestationError::NonCanonicalText);
                    }
                }
            }
        }
        let keys = self
            .rows
            .iter()
            .map(registry_row_order_key)
            .collect::<Result<Vec<_>, _>>()?;
        for pair in keys.windows(2) {
            if pair[0] == pair[1] {
                return Err(AttestationError::DuplicateExtraRow);
            }
            if pair[0] > pair[1] {
                return Err(AttestationError::ExtrasNotStrictlySorted);
            }
        }
        Ok(())
    }

    pub fn encode(&self) -> Result<Vec<u8>, AttestationError> {
        self.validate()?;
        let mut out = vec![VERSION];
        put_count(&mut out, self.rows.len())?;
        for row in &self.rows {
            out.extend_from_slice(&row.node.0.to_le_bytes());
            encode_registry_path(&mut out, &row.path)?;
            encode_registry_fact(&mut out, &row.fact);
        }
        Ok(out)
    }

    pub fn decode(bytes: &[u8]) -> Result<Self, AttestationError> {
        let mut reader = Reader::new(bytes);
        let result = Self::decode_from_reader(&mut reader)?;
        reader.finish()?;
        Ok(result)
    }

    fn decode_from_reader(reader: &mut Reader<'_>) -> Result<Self, AttestationError> {
        let version = reader.u8()?;
        if version != VERSION {
            return Err(AttestationError::UnsupportedVersion(version));
        }
        let count = reader.u32()? as usize;
        let mut rows = Vec::with_capacity(count);
        for _ in 0..count {
            let node = SchemaNodeId(reader.u32()?);
            let path_count = reader.u32()? as usize;
            let mut path = Vec::with_capacity(path_count);
            for _ in 0..path_count {
                path.push(match reader.u8()? {
                    1 => RegistryPathStep::Field(reader.text()?),
                    2 => RegistryPathStep::Variant(reader.text()?),
                    3 => RegistryPathStep::Elem,
                    4 => RegistryPathStep::MapKey,
                    5 => RegistryPathStep::MapValue,
                    value => return Err(AttestationError::UnknownPathStep(value)),
                });
            }
            let fact = match reader.u8()? {
                1 => {
                    let strength = match reader.u8()? {
                        0 => ReferenceStrength::Weak,
                        1 => ReferenceStrength::Strong,
                        value => return Err(AttestationError::UnknownReferenceStrength(value)),
                    };
                    RegistryExtraFact::Reference {
                        strength,
                        target: TypeUuid(reader.a16()?),
                    }
                }
                2 => RegistryExtraFact::Blob,
                3 => RegistryExtraFact::Tag,
                4 => RegistryExtraFact::Skip,
                5 => RegistryExtraFact::BuildOnly(reader.boolean()?),
                6 => RegistryExtraFact::ControlRole(match reader.u8()? {
                    0 => ControlRole::Unrestricted,
                    1 => ControlRole::AuthoringOnlyRequired,
                    value => return Err(AttestationError::UnknownControlRole(value)),
                }),
                7 => RegistryExtraFact::BackReference {
                    target: SchemaNodeId(reader.u32()?),
                },
                value => return Err(AttestationError::UnknownFact(value)),
            };
            rows.push(RegistryExtraRow { node, path, fact });
        }
        let result = Self { rows };
        result.validate()?;
        Ok(result)
    }

    pub fn digest(&self) -> Result<RegistryExtrasDigest, AttestationError> {
        let encoded = self.encode()?;
        let mut hash = blake3::Hasher::new();
        hash.update(&DSRE);
        // The encoded representation starts with the normative version.
        hash.update(&encoded);
        Ok(RegistryExtrasDigest(*hash.finalize().as_bytes()))
    }
}

#[derive(PartialEq, Eq, PartialOrd, Ord)]
struct RegistryRowOrderKey {
    node: u32,
    encoded_path: Vec<u8>,
    encoded_fact: Vec<u8>,
}

fn registry_row_order_key(row: &RegistryExtraRow) -> Result<RegistryRowOrderKey, AttestationError> {
    let mut encoded_path = Vec::new();
    encode_registry_path(&mut encoded_path, &row.path)?;
    let mut encoded_fact = Vec::new();
    encode_registry_fact(&mut encoded_fact, &row.fact);
    Ok(RegistryRowOrderKey {
        node: row.node.0,
        encoded_path,
        encoded_fact,
    })
}

fn encode_registry_path(
    out: &mut Vec<u8>,
    path: &[RegistryPathStep],
) -> Result<(), AttestationError> {
    put_count(out, path.len())?;
    for step in path {
        match step {
            RegistryPathStep::Field(value) => {
                out.push(1);
                put_bytes(out, value.as_bytes())?;
            }
            RegistryPathStep::Variant(value) => {
                out.push(2);
                put_bytes(out, value.as_bytes())?;
            }
            RegistryPathStep::Elem => out.push(3),
            RegistryPathStep::MapKey => out.push(4),
            RegistryPathStep::MapValue => out.push(5),
        }
    }
    Ok(())
}

fn encode_registry_fact(out: &mut Vec<u8>, fact: &RegistryExtraFact) {
    match fact {
        RegistryExtraFact::Reference { strength, target } => {
            out.push(1);
            out.push(match strength {
                ReferenceStrength::Weak => 0,
                ReferenceStrength::Strong => 1,
            });
            out.extend_from_slice(&target.0);
        }
        RegistryExtraFact::Blob => out.push(2),
        RegistryExtraFact::Tag => out.push(3),
        RegistryExtraFact::Skip => out.push(4),
        RegistryExtraFact::BuildOnly(value) => {
            out.push(5);
            out.push(u8::from(*value));
        }
        RegistryExtraFact::ControlRole(role) => {
            out.push(6);
            out.push(match role {
                ControlRole::Unrestricted => 0,
                ControlRole::AuthoringOnlyRequired => 1,
            });
        }
        RegistryExtraFact::BackReference { target } => {
            out.push(7);
            out.extend_from_slice(&target.0.to_le_bytes());
        }
    }
}

impl CompiledTypeRow {
    pub fn new(
        type_uuid: TypeUuid,
        logical_hash: LogicalHash,
        native_layout_digest: [u8; 32],
        build_only: bool,
        registry_extras: RegistryExtrasV1,
    ) -> Result<Self, AttestationError> {
        let registry_extras_digest = registry_extras.digest()?;
        Ok(Self {
            type_uuid,
            logical_hash,
            native_layout_digest,
            build_only,
            registry_extras_digest,
            registry_extras,
        })
    }

    pub fn validate(&self) -> Result<(), AttestationError> {
        if self.registry_extras.digest()? != self.registry_extras_digest {
            return Err(AttestationError::ExtrasDigestMismatch);
        }
        Ok(())
    }

    pub fn encode(&self) -> Result<Vec<u8>, AttestationError> {
        self.validate()?;
        let extras = self.registry_extras.encode()?;
        let mut out = Vec::new();
        out.extend_from_slice(&self.type_uuid.0);
        out.extend_from_slice(&self.logical_hash.0);
        out.extend_from_slice(&self.native_layout_digest);
        out.push(u8::from(self.build_only));
        out.extend_from_slice(&self.registry_extras_digest.0);
        put_bytes(&mut out, &extras)?;
        Ok(out)
    }

    pub fn decode(bytes: &[u8]) -> Result<Self, AttestationError> {
        let mut reader = Reader::new(bytes);
        let type_uuid = TypeUuid(reader.a16()?);
        let logical_hash = LogicalHash(reader.a32()?);
        let native_layout_digest = reader.a32()?;
        let build_only = reader.boolean()?;
        let registry_extras_digest = RegistryExtrasDigest(reader.a32()?);
        let registry_extras = RegistryExtrasV1::decode(reader.bytes()?)?;
        reader.finish()?;
        let result = Self {
            type_uuid,
            logical_hash,
            native_layout_digest,
            build_only,
            registry_extras_digest,
            registry_extras,
        };
        result.validate()?;
        Ok(result)
    }
}

impl CompiledTypeTable {
    pub fn canonical(mut rows: Vec<CompiledTypeRow>) -> Result<Self, AttestationError> {
        rows.sort_by_key(|row| row.type_uuid);
        validate_type_rows(&rows)?;
        let digest = compute_compiled_attestation_digest(&rows)?;
        Ok(Self { rows, digest })
    }

    pub fn from_canonical(
        rows: Vec<CompiledTypeRow>,
        digest: CompiledAttestationDigest,
    ) -> Result<Self, AttestationError> {
        validate_type_rows(&rows)?;
        let expected = compute_compiled_attestation_digest(&rows)?;
        if expected != digest {
            return Err(AttestationError::CompiledDigestMismatch);
        }
        Ok(Self { rows, digest })
    }

    pub fn validate(&self) -> Result<(), AttestationError> {
        Self::from_canonical(self.rows.clone(), self.digest).map(|_| ())
    }

    /// Independently derives the tag-annotation epoch from the compiled rows.
    pub fn tag_annotation_epoch(&self) -> Result<TagAnnotationEpoch, AttestationError> {
        compute_tag_annotation_epoch(&self.rows)
    }

    /// Recompute a boundary projection over exactly the requested runtime
    /// set union the closed five bootstrap controls. Missing requested rows
    /// are errors; callers cannot silently attest a smaller closure.
    pub fn project_with_bootstrap(
        &self,
        requested_runtime: &BTreeSet<TypeUuid>,
    ) -> Result<Self, AttestationError> {
        self.validate()?;
        let requested = requested_runtime
            .iter()
            .copied()
            .chain(BOOTSTRAP_CONTROL_TYPE_UUIDS)
            .collect::<BTreeSet<_>>();
        let mut rows = Vec::with_capacity(requested.len());
        for type_uuid in requested {
            let row = self
                .rows
                .iter()
                .find(|row| row.type_uuid == type_uuid)
                .ok_or(AttestationError::ProjectionMissingType(type_uuid))?;
            rows.push(row.clone());
        }
        Self::canonical(rows)
    }
}

impl BootstrapControlSpecV1 {
    /// Parse the checked-in format release input.  The parser consumes the
    /// logical graph and DSRE grammars directly, so no opaque digest or
    /// caller-supplied row can stand in for the literal authority bytes.
    pub fn parse(bytes: &[u8]) -> Result<Self, BootstrapSpecError> {
        let mut reader = Reader::new(bytes);
        let version = reader.u8()?;
        if version != VERSION {
            return Err(BootstrapSpecError::UnsupportedVersion(version));
        }
        let count = reader.u32()?;
        if count != BOOTSTRAP_CONTROL_COUNT as u32 {
            return Err(BootstrapSpecError::WrongCount(count));
        }

        let mut rows = Vec::with_capacity(BOOTSTRAP_CONTROL_COUNT);
        let mut symbol_bits = 0_u8;
        for _ in 0..BOOTSTRAP_CONTROL_COUNT {
            let symbol = BootstrapControlSymbol::decode(reader.u8()?)?;
            let bit = 1_u8 << (symbol as u8 - 1);
            if symbol_bits & bit != 0 {
                return Err(BootstrapSpecError::DuplicateSymbol(symbol));
            }
            symbol_bits |= bit;
            let type_uuid = TypeUuid(reader.a16()?);
            let expected = symbol_uuid(symbol);
            if type_uuid != expected {
                return Err(BootstrapSpecError::SymbolUuidMismatch {
                    symbol,
                    expected,
                    observed: type_uuid,
                });
            }

            let schema_start = reader.position;
            let mut schema_facts = LogicalSchemaFacts::default();
            validate_logical_schema_node(&mut reader, 0, &mut schema_facts)?;
            let logical_schema = bytes[schema_start..reader.position].to_vec();
            if !reader.boolean()? {
                return Err(BootstrapSpecError::BuildOnlyRequired);
            }
            let registry_extras = RegistryExtrasV1::decode_from_reader(&mut reader)?;
            let has_build_only = registry_extras.rows.iter().any(|row| {
                row.node == SchemaNodeId(0)
                    && row.path.is_empty()
                    && row.fact == RegistryExtraFact::BuildOnly(true)
            });
            let has_control_role = registry_extras.rows.iter().any(|row| {
                row.node == SchemaNodeId(0)
                    && row.path.is_empty()
                    && row.fact
                        == RegistryExtraFact::ControlRole(ControlRole::AuthoringOnlyRequired)
            });
            if !has_build_only || !has_control_role {
                return Err(BootstrapSpecError::BuildOnlyRequired);
            }
            let blob_count = registry_extras
                .rows
                .iter()
                .filter(|row| matches!(row.fact, RegistryExtraFact::Blob))
                .count();
            if blob_count < schema_facts.blobs as usize {
                return Err(BootstrapSpecError::MissingRegistryFact("Blob"));
            }
            let back_reference_count = registry_extras
                .rows
                .iter()
                .filter(|row| matches!(row.fact, RegistryExtraFact::BackReference { .. }))
                .count();
            if back_reference_count < schema_facts.back_references as usize {
                return Err(BootstrapSpecError::MissingRegistryFact("BackReference"));
            }
            for extra in &registry_extras.rows {
                if extra.node.0 >= schema_facts.aggregate_nodes {
                    return Err(BootstrapSpecError::InvalidRegistrySchemaNode(extra.node));
                }
                if let RegistryExtraFact::BackReference { target } = extra.fact {
                    if target.0 >= schema_facts.aggregate_nodes {
                        return Err(BootstrapSpecError::InvalidRegistrySchemaNode(target));
                    }
                }
            }
            let mut hash = blake3::Hasher::new();
            hash.update(b"DSLH");
            hash.update(&[VERSION]);
            hash.update(&logical_schema);
            rows.push(BootstrapControlSpecRowV1 {
                symbol,
                type_uuid,
                logical_schema,
                logical_hash: LogicalHash(*hash.finalize().as_bytes()),
                registry_extras,
            });
        }
        reader.finish()?;
        for pair in rows.windows(2) {
            if pair[0].type_uuid == pair[1].type_uuid {
                return Err(BootstrapSpecError::DuplicateType(pair[0].type_uuid));
            }
            if pair[0].type_uuid > pair[1].type_uuid {
                return Err(BootstrapSpecError::RowsNotStrictlySorted);
            }
        }
        Ok(Self(rows.try_into().expect("fixed bootstrap row count")))
    }

    pub fn embedded() -> Result<Self, BootstrapSpecError> {
        Self::parse(BOOTSTRAP_CONTROL_SPEC_V1_BYTES)
    }

    /// Encode a fully expanded bootstrap specification.  Encoding validates
    /// the result by reparsing it, so code-generation cannot write a DSB with
    /// a second, weaker interpretation of the grammar.
    pub fn encode(&self) -> Result<Vec<u8>, BootstrapSpecError> {
        let mut out = vec![VERSION];
        put_count(&mut out, BOOTSTRAP_CONTROL_COUNT).map_err(BootstrapSpecError::from)?;
        for row in &self.0 {
            out.push(row.symbol as u8);
            out.extend_from_slice(&row.type_uuid.0);
            out.extend_from_slice(&row.logical_schema);
            out.push(1);
            out.extend_from_slice(&row.registry_extras.encode()?);
        }
        if Self::parse(&out)? != *self {
            return Err(BootstrapSpecError::NonCanonicalEncoding);
        }
        Ok(out)
    }

    pub fn type_uuids(&self) -> [TypeUuid; BOOTSTRAP_CONTROL_COUNT] {
        self.0.clone().map(|row| row.type_uuid)
    }
}

impl BootstrapControlTableV1 {
    pub fn canonical(rows: Vec<CompiledTypeRow>) -> Result<Self, BootstrapAuthorityMismatch> {
        if rows.len() != BOOTSTRAP_CONTROL_COUNT {
            return Err(BootstrapAuthorityMismatch::WrongCount(rows.len()));
        }
        let table =
            CompiledTypeTable::canonical(rows).map_err(BootstrapAuthorityMismatch::InvalidTable)?;
        validate_bootstrap_logical_authority(&table.rows, BundleFormatVersion::V1)?;
        let rows: [CompiledTypeRow; BOOTSTRAP_CONTROL_COUNT] = table
            .rows
            .try_into()
            .map_err(|rows: Vec<_>| BootstrapAuthorityMismatch::WrongCount(rows.len()))?;
        Ok(Self(rows))
    }

    pub fn rows(&self) -> &[CompiledTypeRow; BOOTSTRAP_CONTROL_COUNT] {
        &self.0
    }

    pub fn compiled_table(&self) -> Result<CompiledTypeTable, AttestationError> {
        CompiledTypeTable::canonical(self.0.to_vec())
    }
}

pub fn is_bootstrap_control_type(type_uuid: TypeUuid) -> bool {
    BOOTSTRAP_CONTROL_TYPE_UUIDS
        .binary_search(&type_uuid)
        .is_ok()
}

pub fn bootstrap_control_logical_registry_v1(
) -> Result<BTreeMap<TypeUuid, LogicalHash>, BootstrapSpecError> {
    Ok(BootstrapControlSpecV1::embedded()?
        .0
        .into_iter()
        .map(|row| (row.type_uuid, row.logical_hash))
        .collect())
}

/// Validate the target-invariant half of bootstrap authority directly from
/// DSB: UUID, DSLH, build policy, and the complete DSRE table.  Target-bound
/// consumers additionally call [`validate_bootstrap_authority`] to compare
/// DSNL and therefore the complete rows.
pub fn validate_bootstrap_logical_authority(
    compiled: &[CompiledTypeRow],
    _format: BundleFormatVersion,
) -> Result<(), BootstrapAuthorityMismatch> {
    let spec =
        BootstrapControlSpecV1::embedded().map_err(BootstrapAuthorityMismatch::InvalidSpec)?;
    for expected in &spec.0 {
        let Some(actual) = compiled
            .iter()
            .find(|row| row.type_uuid == expected.type_uuid)
        else {
            return Err(BootstrapAuthorityMismatch::Missing(expected.type_uuid));
        };
        actual
            .validate()
            .map_err(BootstrapAuthorityMismatch::InvalidTable)?;
        let field = if actual.logical_hash != expected.logical_hash {
            Some("logical_hash")
        } else if !actual.build_only {
            Some("build_only")
        } else if actual.registry_extras != expected.registry_extras
            || actual.registry_extras_digest
                != expected
                    .registry_extras
                    .digest()
                    .map_err(BootstrapAuthorityMismatch::InvalidTable)?
        {
            Some("registry_extras")
        } else {
            None
        };
        if let Some(field) = field {
            return Err(BootstrapAuthorityMismatch::Unequal {
                type_uuid: expected.type_uuid,
                field,
            });
        }
    }
    Ok(())
}

pub fn validate_bootstrap_authority(
    compiled: &[CompiledTypeRow],
    expected: &BootstrapControlTableV1,
    format: BundleFormatVersion,
) -> Result<(), BootstrapAuthorityMismatch> {
    validate_bootstrap_logical_authority(compiled, format)?;
    for expected in expected.rows() {
        let Some(actual) = compiled
            .iter()
            .find(|row| row.type_uuid == expected.type_uuid)
        else {
            return Err(BootstrapAuthorityMismatch::Missing(expected.type_uuid));
        };
        let field = if actual.logical_hash != expected.logical_hash {
            Some("logical_hash")
        } else if actual.native_layout_digest != expected.native_layout_digest {
            Some("native_layout_digest")
        } else if actual.build_only != expected.build_only {
            Some("build_only")
        } else if actual.registry_extras_digest != expected.registry_extras_digest
            || actual.registry_extras != expected.registry_extras
        {
            Some("registry_extras")
        } else {
            None
        };
        if let Some(field) = field {
            return Err(BootstrapAuthorityMismatch::Unequal {
                type_uuid: expected.type_uuid,
                field,
            });
        }
    }
    Ok(())
}

#[derive(Default)]
struct LogicalSchemaFacts {
    aggregate_nodes: u32,
    blobs: u32,
    back_references: u32,
}

fn validate_logical_schema_node(
    reader: &mut Reader<'_>,
    frame_depth: u32,
    facts: &mut LogicalSchemaFacts,
) -> Result<(), BootstrapSpecError> {
    match reader.u8()? {
        0x01 => {
            let primitive = reader.text()?;
            if !matches!(
                primitive.as_str(),
                "bool"
                    | "u8"
                    | "u16"
                    | "u32"
                    | "u64"
                    | "u128"
                    | "i8"
                    | "i16"
                    | "i32"
                    | "i64"
                    | "i128"
                    | "f32"
                    | "f64"
                    | "char"
            ) {
                return Err(BootstrapSpecError::InvalidPrimitive);
            }
        }
        0x02 | 0x03 => {
            facts.aggregate_nodes = facts.aggregate_nodes.saturating_add(1);
            let _rev = reader.u32()?;
            let count = reader.u32()?;
            let mut previous: Option<Vec<u8>> = None;
            for _ in 0..count {
                let name = reader.text()?;
                if previous
                    .as_deref()
                    .is_some_and(|prior| prior >= name.as_bytes())
                {
                    return Err(BootstrapSpecError::SchemaEntriesNotStrictlySorted);
                }
                previous = Some(name.into_bytes());
                let _entry_rev = reader.u32()?;
                validate_logical_schema_node(reader, frame_depth.saturating_add(1), facts)?;
            }
        }
        0x04 | 0x06 | 0x0e => validate_logical_schema_node(reader, frame_depth, facts)?,
        0x05 => {
            let _len = reader.u64()?;
            validate_logical_schema_node(reader, frame_depth, facts)?;
        }
        0x07 => {
            validate_logical_schema_node(reader, frame_depth, facts)?;
            validate_logical_schema_node(reader, frame_depth, facts)?;
        }
        0x08 | 0x0d => {}
        0x0b => facts.blobs = facts.blobs.saturating_add(1),
        0x09 | 0x0a => {
            let _target = reader.a16()?;
        }
        0x0c => {
            let distance = reader.u32()?;
            if distance >= frame_depth {
                return Err(BootstrapSpecError::InvalidBackReference(distance));
            }
            facts.back_references = facts.back_references.saturating_add(1);
        }
        value => return Err(BootstrapSpecError::InvalidSchemaNode(value)),
    }
    Ok(())
}

pub fn compute_compiled_attestation_digest(
    rows: &[CompiledTypeRow],
) -> Result<CompiledAttestationDigest, AttestationError> {
    validate_type_rows(rows)?;
    let mut hash = blake3::Hasher::new();
    hash.update(&DSCA);
    hash.update(&[VERSION]);
    hash.update(
        &u32::try_from(rows.len())
            .map_err(|_| AttestationError::CountOverflow)?
            .to_le_bytes(),
    );
    for row in rows {
        let encoded = row.encode()?;
        hash.update(&encoded);
    }
    Ok(CompiledAttestationDigest(*hash.finalize().as_bytes()))
}

/// Encodes the closed DSTA v1 projection. The result begins with the v1 byte
/// and contains every compiled type, including types with no tag facts.
///
/// Callers cannot provide tag rows directly: this function validates the
/// complete compiled table, projects only `RegistryExtraFact::Tag`, and sorts
/// those projected records by their exact canonical bytes.
pub fn encode_tag_annotation_projection(
    rows: &[CompiledTypeRow],
) -> Result<Vec<u8>, AttestationError> {
    validate_type_rows(rows)?;

    let mut out = vec![VERSION];
    put_count(&mut out, rows.len())?;
    for row in rows {
        out.extend_from_slice(&row.type_uuid.0);

        let mut tags = row
            .registry_extras
            .rows
            .iter()
            .filter(|extra| matches!(extra.fact, RegistryExtraFact::Tag))
            .map(|extra| {
                let mut encoded_path = Vec::new();
                encode_registry_path(&mut encoded_path, &extra.path)?;
                // DSTA's fact vocabulary is deliberately separate from the
                // DSRE fact discriminants: SearchTag is fixed at 1.
                Ok((extra.node.0, encoded_path, 1_u8))
            })
            .collect::<Result<Vec<_>, AttestationError>>()?;
        tags.sort();
        if tags.windows(2).any(|pair| pair[0] == pair[1]) {
            return Err(AttestationError::DuplicateExtraRow);
        }
        put_count(&mut out, tags.len())?;
        for (node, path, fact) in tags {
            out.extend_from_slice(&node.to_le_bytes());
            out.extend_from_slice(&path);
            out.push(fact);
        }
    }
    Ok(out)
}

/// Derives `blake3("DSTA" || canonical DSTA v1 projection)` from the complete
/// compiled rows. No caller-provided epoch participates in this computation.
pub fn compute_tag_annotation_epoch(
    rows: &[CompiledTypeRow],
) -> Result<TagAnnotationEpoch, AttestationError> {
    let encoded = encode_tag_annotation_projection(rows)?;
    let mut hash = blake3::Hasher::new();
    hash.update(&DSTA);
    hash.update(&encoded);
    Ok(TagAnnotationEpoch(*hash.finalize().as_bytes()))
}

/// Recomputes DSTA from the complete compiled rows before comparing an epoch
/// received from staging, publication, or dependency revalidation.
pub fn verify_tag_annotation_epoch(
    rows: &[CompiledTypeRow],
    observed: TagAnnotationEpoch,
) -> Result<(), AttestationError> {
    let expected = compute_tag_annotation_epoch(rows)?;
    if expected != observed {
        return Err(AttestationError::TagAnnotationEpochMismatch { expected, observed });
    }
    Ok(())
}

fn validate_type_rows(rows: &[CompiledTypeRow]) -> Result<(), AttestationError> {
    for row in rows {
        row.validate()?;
    }
    for pair in rows.windows(2) {
        if pair[0].type_uuid == pair[1].type_uuid {
            return Err(AttestationError::DuplicateType(pair[0].type_uuid));
        }
        if pair[0].type_uuid > pair[1].type_uuid {
            return Err(AttestationError::TypeRowsNotStrictlySorted);
        }
    }
    Ok(())
}

fn put_count(out: &mut Vec<u8>, count: usize) -> Result<(), AttestationError> {
    out.extend_from_slice(
        &u32::try_from(count)
            .map_err(|_| AttestationError::CountOverflow)?
            .to_le_bytes(),
    );
    Ok(())
}

fn put_bytes(out: &mut Vec<u8>, bytes: &[u8]) -> Result<(), AttestationError> {
    put_count(out, bytes.len())?;
    out.extend_from_slice(bytes);
    Ok(())
}

struct Reader<'a> {
    bytes: &'a [u8],
    position: usize,
}

impl<'a> Reader<'a> {
    fn new(bytes: &'a [u8]) -> Self {
        Self { bytes, position: 0 }
    }

    fn take(&mut self, len: usize) -> Result<&'a [u8], AttestationError> {
        let end = self
            .position
            .checked_add(len)
            .ok_or(AttestationError::Truncated)?;
        let value = self
            .bytes
            .get(self.position..end)
            .ok_or(AttestationError::Truncated)?;
        self.position = end;
        Ok(value)
    }

    fn u8(&mut self) -> Result<u8, AttestationError> {
        Ok(self.take(1)?[0])
    }

    fn u32(&mut self) -> Result<u32, AttestationError> {
        Ok(u32::from_le_bytes(
            self.take(4)?.try_into().expect("checked width"),
        ))
    }

    fn u64(&mut self) -> Result<u64, AttestationError> {
        Ok(u64::from_le_bytes(
            self.take(8)?.try_into().expect("checked width"),
        ))
    }

    fn a16(&mut self) -> Result<[u8; 16], AttestationError> {
        Ok(self.take(16)?.try_into().expect("checked width"))
    }

    fn a32(&mut self) -> Result<[u8; 32], AttestationError> {
        Ok(self.take(32)?.try_into().expect("checked width"))
    }

    fn boolean(&mut self) -> Result<bool, AttestationError> {
        match self.u8()? {
            0 => Ok(false),
            1 => Ok(true),
            value => Err(AttestationError::InvalidBool(value)),
        }
    }

    fn bytes(&mut self) -> Result<&'a [u8], AttestationError> {
        let len = self.u32()? as usize;
        self.take(len)
    }

    fn text(&mut self) -> Result<String, AttestationError> {
        let value =
            std::str::from_utf8(self.bytes()?).map_err(|_| AttestationError::InvalidUtf8)?;
        if value.nfc().collect::<String>() != value {
            return Err(AttestationError::NonCanonicalText);
        }
        Ok(value.to_owned())
    }

    fn finish(self) -> Result<(), AttestationError> {
        if self.position == self.bytes.len() {
            Ok(())
        } else {
            Err(AttestationError::TrailingBytes)
        }
    }
}
